force-app/main/default/objects/Case/fields/Closed_Lost_Terminated_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closed_Lost_Terminated_Reason__c</fullName>
    <label>Closed/Lost/Terminated Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Client unresponsive/Never transacted</fullName>
            </value>
            <value>
                <fullName>Client not ready</fullName>
            </value>
            <value>
                <fullName>VANs does not meet clients needs/expectations</fullName>
            </value>
            <value>
                <fullName>No pilot customer</fullName>
            </value>
            <value>
                <fullName>Client does not want to pay API fee</fullName>
            </value>
            <value>
                <fullName>Change of Delivery Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agoda Pro Portal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>eNett Gateway</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>No eNett Product</fullName>
            </value>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>VANs Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Related_Delivery_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Delivery_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Delivery Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Phase Tickets</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/attainable_ttv_monthly__c.field-meta.xml
<CustomField>
    <fullName>attainable_ttv_monthly__c</fullName>
    <label>Attainable GDV (monthly)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Åland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
                <default>true</default>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Duration_minus_Dormant_Time__c.field-meta.xml
<CustomField>
    <fullName>Duration_minus_Dormant_Time__c</fullName>
    <formula>IF(ISNULL(Completed_Date__c), 
CASE(MOD( Implementation_Start_Date__c - DATE(1985,6,24),7), 

0 , CASE( MOD( TODAY() - Implementation_Start_Date__c ,7),1,2,2,3,3,4,4,5,5,5,6,5,1), 
1 , CASE( MOD( TODAY() - Implementation_Start_Date__c ,7),1,2,2,3,3,4,4,4,5,4,6,5,1), 
2 , CASE( MOD( TODAY() - Implementation_Start_Date__c ,7),1,2,2,3,3,3,4,3,5,4,6,5,1), 
3 , CASE( MOD( TODAY() - Implementation_Start_Date__c ,7),1,2,2,2,3,2,4,3,5,4,6,5,1), 
4 , CASE( MOD( TODAY() - Implementation_Start_Date__c ,7),1,1,2,1,3,2,4,3,5,4,6,5,1), 
5 , CASE( MOD( TODAY() - Implementation_Start_Date__c ,7),1,0,2,1,3,2,4,3,5,4,6,5,0), 
6 , CASE( MOD( TODAY() - Implementation_Start_Date__c ,7),1,1,2,2,3,3,4,4,5,5,6,5,0), 
999) 
+ 
(FLOOR(( TODAY() - Implementation_Start_Date__c )/7)*5) - Total_Dormant_Duration__c ,
CASE(MOD( Implementation_Start_Date__c - DATE(1985,6,24),7), 

0 , CASE( MOD( Completed_Date__c - Implementation_Start_Date__c ,7),1,2,2,3,3,4,4,5,5,5,6,5,1), 
1 , CASE( MOD( Completed_Date__c - Implementation_Start_Date__c ,7),1,2,2,3,3,4,4,4,5,4,6,5,1), 
2 , CASE( MOD( Completed_Date__c - Implementation_Start_Date__c ,7),1,2,2,3,3,3,4,3,5,4,6,5,1), 
3 , CASE( MOD( Completed_Date__c - Implementation_Start_Date__c ,7),1,2,2,2,3,2,4,3,5,4,6,5,1), 
4 , CASE( MOD( Completed_Date__c - Implementation_Start_Date__c ,7),1,1,2,1,3,2,4,3,5,4,6,5,1), 
5 , CASE( MOD( Completed_Date__c - Implementation_Start_Date__c ,7),1,0,2,1,3,2,4,3,5,4,6,5,0), 
6 , CASE( MOD( Completed_Date__c - Implementation_Start_Date__c ,7),1,1,2,2,3,3,4,4,5,5,6,5,0), 
999) 
+ 
(FLOOR(( Completed_Date__c - Implementation_Start_Date__c )/7)*5)- Total_Dormant_Duration__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration ( minus Dormant Time)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Hours_Man_Effort_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Hours_Man_Effort_To_Date__c</fullName>
    <label>Hours Man Effort To Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Implementation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Start_Date__c</fullName>
    <label>Implementation Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Implementation_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Implementation_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Implementation Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Delivery Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>eNett Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
                <default>true</default>
                <label>VANs</label>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Virtual Terminal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Secondary_Implemantation_Contact__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Implemantation_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Implemantation Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Secondary Implemantation Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Terminated_Delivery_Duration_Days__c.field-meta.xml
<CustomField>
    <fullName>Terminated_Delivery_Duration_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Terminated Delivery Duration Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Terminated_Delivery_Effort_Man_Hours__c.field-meta.xml
<CustomField>
    <fullName>Terminated_Delivery_Effort_Man_Hours__c</fullName>
    <defaultValue>0.00</defaultValue>
    <label>Terminated Delivery Effort Man Hours</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/VAN_currencies_top_3__c.field-meta.xml
<CustomField>
    <fullName>VAN_currencies_top_3__c</fullName>
    <label>VAN currencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>AMD</fullName>
            </value>
            <value>
                <fullName>ANG</fullName>
            </value>
            <value>
                <fullName>AOA</fullName>
            </value>
            <value>
                <fullName>ARS</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>AWG</fullName>
            </value>
            <value>
                <fullName>BBD</fullName>
            </value>
            <value>
                <fullName>BDT</fullName>
            </value>
            <value>
                <fullName>BGN</fullName>
            </value>
            <value>
                <fullName>BHD</fullName>
            </value>
            <value>
                <fullName>BIF</fullName>
            </value>
            <value>
                <fullName>BMD</fullName>
            </value>
            <value>
                <fullName>BND</fullName>
            </value>
            <value>
                <fullName>BOB</fullName>
            </value>
            <value>
                <fullName>BRL</fullName>
            </value>
            <value>
                <fullName>BSD</fullName>
            </value>
            <value>
                <fullName>BTN</fullName>
            </value>
            <value>
                <fullName>BWP</fullName>
            </value>
            <value>
                <fullName>BZD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CDF</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CLP</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>COP</fullName>
            </value>
            <value>
                <fullName>CRC</fullName>
            </value>
            <value>
                <fullName>CUC</fullName>
            </value>
            <value>
                <fullName>CVE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PopUpDialog_CaseExts.cls
public class PopUpDialog_CaseExts {

    public class closeLost extends PopUpDialogController.contExt {

        private Case cs {get; set;}
        
        public closeLost(Id regId) {
            cs = PopUpDialog_CaseExts.loadCase(regId);
        }    

        public override String runValidation() {
            if (cs.status == 'Closed/Lost Delivery') return 'You cannot close the delivery since it has already been closed.';
            return null;
        }
            
        public override String runProcess() {
            if (picklistSelection == 'None') throw new applicationException('You must select a reason to close the delivery.');
            cs.status = 'Closed/Lost Delivery';
            cs.Closed_Lost_Terminated_Reason__c = picklistSelection;
            update cs;
            return null;
        }
        
        public override String showConfirmMsg() {
            //return 'You are about to close this delivery as lost. Please select a reason from the picklist and press continue:';
            //return 'You have chosen the Close/Lost button on this delivery ticket.  Please select a reason from the list provided below.  The related Opportunity status will be set to Closed/Lost and the Won/Lost Reason field to the reason selected.';
            return 'You have chosen the Close/Lost button.  Please select a reason from the list below.  The related Opportunity status will be set to Closed/Lost and the Won/Lost Reason field to the reason selected.';            
        }
        
        public override List<SelectOption> getPicklistOptions() {
            List<SelectOption> options = new List<SelectOption>();
            options.add(new SelectOption('None','--None--'));
            options.add(new SelectOption('Other','Other'));
            options.add(new SelectOption('Client unresponsive/Never transacted','Client unresponsive/Never transacted'));
            options.add(new SelectOption('Client not ready','Client not ready'));
            options.add(new SelectOption('VANs does not meet clients needs/expectations','VANs does not meet clients needs/expectations'));
            options.add(new SelectOption('No pilot customer','No pilot customer'));
            options.add(new SelectOption('Client does not want to pay API fee','Client does not want to pay API fee'));
            
            return options;
        }        
  
    }    


    public class Terminate extends PopUpDialogController.contExt {

        private Case cs {get; set;}
        
        public Terminate(Id regId) {
            cs = PopUpDialog_CaseExts.loadCase(regId);
        }    
            
        public override String runProcess() {
            cs.status = 'Terminate';
            cs.Closed_Lost_Terminated_Reason__c = 'Change of Delivery Type';
            update cs;
            
            if (cs.Related_Delivery_Opportunity__c != null) {
                Opportunity nwOpp = duplicateOpportunity(cs.Related_Delivery_Opportunity__c);
                insert nwOpp;
            }
            return null;
        }
        
        public override String showConfirmMsg() {
            return 'You have chosen to terminate this delivery ticket.  This will set the related Opportunity status to \'Closed/Lost\' and the Won/Lost Reason to \'Change of Delivery Type\'.  A new Opportunity will also be created and the name appended with the text \'- Opp 2\'.';
        }

    }
    
    public static Opportunity duplicateOpportunity(Id oppId) {
        Opportunity opp;
        LIST<Opportunity> oppList = [SELECT Name, AccountId, Product__c, Region__c, Country__c, 
                                     OwnerId, StageName, Type, Primary_Implementation_Contact__c, 
                                     Secondary_Implemantation_Contact__c, attainable_ttv_monthly__c, 
                                     VAN_currencies_top_3__c, Hours_Man_Effort_To_Date__c, CloseDate, 
                                     Duration_minus_Dormant_Time__c, Implementation_Start_Date__c, CurrencyIsoCode 
                                     FROM Opportunity WHERE Id = :oppId LIMIT 1];

        if (oppList.isEmpty()) {
            return null;
        } else {
            opp = oppList[0];
        }

        Opportunity newOpp = new Opportunity (
            Name = opp.Name + ' - Opp 2',
            AccountId = opp.AccountId,
            Product__c = opp.Product__c,
            Region__c = opp.Region__c,
            Country__c = opp.Country__c,
            OwnerId = opp.OwnerId,
            StageName = opp.StageName,
            Type = opp.Type,
            Primary_Implementation_Contact__c = opp.Primary_Implementation_Contact__c,
            Secondary_Implemantation_Contact__c = opp.Secondary_Implemantation_Contact__c,
            CurrencyIsoCode = opp.CurrencyIsoCode,
            attainable_ttv_monthly__c = opp.attainable_ttv_monthly__c,
            VAN_currencies_top_3__c = opp.VAN_currencies_top_3__c,
            Terminated_Delivery_Effort_Man_Hours__c = opp.Hours_Man_Effort_To_Date__c,
            CloseDate = opp.CloseDate,
            Terminated_Delivery_Duration_Days__c = opp.Duration_minus_Dormant_Time__c,
            Implementation_Start_Date__c = opp.Implementation_Start_Date__c);
        return newOpp;
    }

    
    public static Case loadCase(Id recId) {
        Case cs;
        cs = [SELECT Id, status, Related_Delivery_Opportunity__c
               FROM Case
               WHERE Id = :recId];
        return cs;
    }
    
    public class applicationException extends Exception {}

}