force-app/main/default/objects/Case/fields/Delivery_Phase__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Phase__c</fullName>
    <label>Delivery Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 - Pre-Implementation Kick-off</fullName>
            </value>
            <value>
                <fullName>1 - Set Up and Configuration</fullName>
            </value>
            <value>
                <fullName>2 - VAN Training</fullName>
            </value>
            <value>
                <fullName>3 - Funding</fullName>
            </value>
            <value>
                <fullName>4 - VAN Reporting and Reconciliation</fullName>
            </value>
            <value>
                <fullName>1 - Planning &amp; Preparation</fullName>
            </value>
            <value>
                <fullName>2 - Development ( API integration)</fullName>
            </value>
            <value>
                <fullName>3 - UAT</fullName>
            </value>
            <value>
                <fullName>4 - Live testing</fullName>
            </value>
            <value>
                <fullName>5 - Production cut over</fullName>
            </value>
            <value>
                <fullName>Unassigned Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Delivery_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Ticket__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the Ticket is a Delivery Ticket. Used in WF Rule so field can be used in Sharing Settings for Cases.</description>
    <label>Delivery Ticket</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <inlineHelpText>This field will display the Delivery Type that is selected in the related Opportunity.</inlineHelpText>
    <label>Delivery Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Related_Delivery_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Delivery_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Delivery Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Phase Tickets</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/API_Delivery_Phase_0_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>API_Delivery_Phase_0_Record_Type</fullName>
    <active>true</active>
    <businessProcess>Delivery Process</businessProcess>
    <description>API Delivery Phase 0 Record Type</description>
    <label>API Delivery Phase 0 Record Type</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Desktop_Delivery_Phase_0_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Desktop_Delivery_Phase_0_Record_Type</fullName>
    <active>true</active>
    <businessProcess>Delivery Process</businessProcess>
    <label>Desktop Delivery Phase 0 Record Type</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Delivery_Phase__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Phase__c</fullName>
    <label>Delivery Phase</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Delivery - Desktop</fullName>
            </value>
            <value>
                <fullName>Delivery - API</fullName>
            </value>
            <value>
                <fullName>Delivery Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutoCreateDelivery.cls
global class AutoCreateDelivery {

    @InvocableMethod
    public static void AutoCreateDeliveryTicket (List<Id> accIds) {

System.debug('>>>>>>>>>>>>>>>> In the class');        
        List<Opportunity> OpportunityList = new LIST<Opportunity>();
        List<Case> newDeliveryList = new List<Case>();
        Id queueId;
        Id recTypeId;
        Map<string,RecordType> caseRecTypeMap = FutureCalls.mapRecordTypes('Case');
        String DelPhase;
		
        //SF-5267 Combining Delivery Queues to one Global
        //Group APACQueue = [select Id from Group where Name = 'APAC Delivery Queue' and Type = 'Queue'];
        //Group EMEAQueue = [select Id from Group where Name = 'EMEA/Americas Delivery Queue' and Type = 'Queue'];   
        Group deliveryQueue = [SELECT Id 
                              FROM Group
                              WHERE Name = 'Global Delivery Queue'
                              AND Type = 'Queue'
                              LIMIT 1];
                      
        for (Opportunity o : [  
                SELECT Id, Delivery_type__c, Name, Region__c, AccountId
                FROM Opportunity 
                WHERE AccountId IN :accIds 
                AND StageName IN ('1. Prospect', '2. Sales Qualified', '3. Contracted') 
                AND (Delivery_type__c = 'Delivery - API' OR Delivery_type__c = 'Delivery - Desktop') ] ) {

System.debug('>>>>>>>>>>>>>>>> Found Opp');        

                List<Case> existingDeliveryList = [ 
                    SELECT Id 
                    FROM Case 
                    WHERE Related_Delivery_Opportunity__c = :o.Id 
                    AND Delivery_Ticket__c = true];

                if (existingDeliveryList.isEmpty()) {
System.debug('>>>>>>>>>>>>>>>> No DT');        
					//SF-5267 Combining Delivery Queues to one Global
                    //queueId = o.Region__c == 'APAC' ? APACQueue.Id : EMEAQueue.Id;
                    queueId = deliveryQueue.Id;
                    recTypeId = o.Delivery_type__c == 'Delivery - API' ? caseRecTypeMap.get('API_Delivery_Phase_0_Record_Type').Id : caseRecTypeMap.get('Desktop_Delivery_Phase_0_Record_Type').Id;

                    DelPhase = o.Delivery_type__c == 'Delivery - API' ? 'Unassigned Delivery' : '0 - Pre-Implementation Kick-off';

                    // Create a Delivery Ticket
                    newDeliveryList.add(new Case(
                        Related_Delivery_Opportunity__c = o.Id, 
                        AccountId = o.AccountId,
                        Priority = 'Should Have',
                        Delivery_Phase__c = DelPhase,
                        RecordTypeId = recTypeId,
                        OwnerId = queueId,
                        Delivery_Type__c = o.Delivery_type__c,
                        Subject = 'Delivery - ' + o.Name)); 

                }
        }

        if (!newDeliveryList.isEmpty()) insert newDeliveryList;

    }
}