force-app/main/default/objects/Case/fields/Delivery_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Ticket__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if the Ticket is a Delivery Ticket. Used in WF Rule so field can be used in Sharing Settings for Cases.</description>
    <label>Delivery Ticket</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/eNett_Contract__c.object-meta.xml
<CustomObject>
    <label>eNett Contract</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>eNett Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eNett Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/eNett_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eNett Contract</relationshipLabel>
    <relationshipName>eNett_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Flight</fullName>
                <default>true</default>
                <label>In Flight</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/Process_Task__c.object-meta.xml
<CustomObject>
    <label>Process Task</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Process Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Tasks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Task__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>eNett_Contract__r.Account_Name__r.Name</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Delivery_Task_Open__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Task_Open__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Task Open</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Open Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Delivery_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Ticket</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Open Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/eNett_Contract__c.field-meta.xml
<CustomField>
    <fullName>eNett_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up the &#39;eNett Contract&#39; record to which this Task record is related to.</description>
    <inlineHelpText>Looks up the &#39;eNett Contract&#39; record to which this Task record is related to.</inlineHelpText>
    <label>eNett Contract</label>
    <referenceTo>eNett_Contract__c</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/eNett_Contract_Task_Open__c.field-meta.xml
<CustomField>
    <fullName>eNett_Contract_Task_Open__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>eNett Contract Task Open</label>
    <referenceTo>eNett_Contract__c</referenceTo>
    <relationshipLabel>Open Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Opportunity_Task_Open__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Task_Open__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Task Open</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Open Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PT_TaskValidationTest.cls
@isTest (seeAllData = true) public class PT_TaskValidationTest {
    @isTest static void DeliveryProcessTask1(){
        
        //Creat a case 
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('API Delivery Phase 0 Record Type').getRecordTypeId();
        Case testCase = new Case(Subject = 'testCase',
                                 RecordTypeId = recordTypeId);
        insert testCase;
        testCase.Delivery_Ticket__c = true;
        update testCase;
        
        //Test case: status changed from 'Not Completed' to 'Completed'
        Process_Task__c pt = new Process_Task__c(Subject__c = 'test',
                                                 Status__c = 'Not Started');
        insert pt;
        pt.Status__c = 'Completed';
        pt.Delivery_Ticket__c = testCase.Id;
        pt.Delivery_Task_Open__c = testCase.Id;
        update pt;
        
    }
    
    @isTest static void DeliveryProcessTask2(){
        //Creat a case 
        Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('API Delivery Phase 0 Record Type').getRecordTypeId();
        Case testCase = new Case(Subject = 'testCase',
                                 RecordTypeId = recordTypeId);
        insert testCase;
        testCase.Delivery_Ticket__c = true;
        update testCase;        
        
        //Test case: status changed from 'Completed' to new status that is not 'Completed' or 'Terminated'
        Process_Task__c pt2 = new Process_Task__c(Subject__c = 'test',
                                                  Status__c = 'Terminated');
        insert pt2;
        pt2.Status__c = 'Deferred';
        pt2.Delivery_Ticket__c = testCase.Id;
        pt2.Delivery_Task_Open__c = testCase.Id;
        update pt2;
    }
    
    @isTest static void OppProcessTask1(){
        //Create an opportunity
        Account testAcc = eNettTestUtility.createAccount('Test Account');
        Opportunity testOpp = eNettTestUtility.createOpportunity('Test Opp', testAcc.Id);
        
        //Test case: status changed from 'Not Completed' to 'Completed'
        Process_Task__c pt = new Process_Task__c(Subject__c = 'test',
                                                 Status__c = 'Not Started');
        insert pt;
        pt.Status__c = 'Completed';
        pt.Opportunity__c = testOpp.Id;
        pt.Opportunity_Task_Open__c= testOpp.Id;
        update pt;
    }
    
    @isTest static void OppProcessTask2(){
        //Create an opportunity
        Account testAcc = eNettTestUtility.createAccount('Test Account');
        Opportunity testOpp = eNettTestUtility.createOpportunity('Test Opp', testAcc.Id);
        
        //Test case: status changed from 'Not Completed' to 'Completed'
        Process_Task__c pt = new Process_Task__c(Subject__c = 'test',
                                                 Status__c = 'Terminated');
        insert pt;
        pt.Status__c = 'Deferred';
        pt.Opportunity__c = testOpp.Id;
        pt.Opportunity_Task_Open__c= testOpp.Id;
        update pt;
    }
    
    @isTest static void ContractProcessTask1(){
        //Create an opportunity
        Account testAcc = eNettTestUtility.createAccount('Test Account');
        Opportunity testOpp = eNettTestUtility.createOpportunity('Test Opp', testAcc.Id);
        eNett_Contract__c testContract = new eNett_Contract__c(Account_Name__c = testAcc.Id);
        insert testContract;
        //Test case: status changed from 'Not Completed' to 'Completed'
        Process_Task__c pt = new Process_Task__c(Subject__c = 'test',
                                                 Status__c = 'Not Started');
        insert pt;
        pt.Status__c = 'Completed';
        pt.eNett_Contract__c = testContract.Id;
        pt.eNett_Contract_Task_Open__c= testContract.Id;
        update pt;
    }
    
    @isTest static void ContractProcessTask2(){
        //Create an opportunity
        Account testAcc = eNettTestUtility.createAccount('Test Account');
        Opportunity testOpp = eNettTestUtility.createOpportunity('Test Opp', testAcc.Id);
        eNett_Contract__c testContract = new eNett_Contract__c(Account_Name__c = testAcc.Id);
        insert testContract;
        //Test case: status changed from 'Not Completed' to 'Completed'
        Process_Task__c pt = new Process_Task__c(Subject__c = 'test',
                                                 Status__c = 'Terminated');
        insert pt;
        pt.Status__c = 'Deferred';
        pt.eNett_Contract__c = testContract.Id;
        pt.eNett_Contract_Task_Open__c= testContract.Id;
        update pt;
    }
}