force-app/main/default/objects/Case/fields/Delivery_Phase__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Phase__c</fullName>
    <label>Delivery Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 - Pre-Implementation Kick-off</fullName>
            </value>
            <value>
                <fullName>1 - Set Up and Configuration</fullName>
            </value>
            <value>
                <fullName>2 - VAN Training</fullName>
            </value>
            <value>
                <fullName>3 - Funding</fullName>
            </value>
            <value>
                <fullName>4 - VAN Reporting and Reconciliation</fullName>
            </value>
            <value>
                <fullName>1 - Planning &amp; Preparation</fullName>
            </value>
            <value>
                <fullName>2 - Development ( API integration)</fullName>
            </value>
            <value>
                <fullName>3 - UAT</fullName>
            </value>
            <value>
                <fullName>4 - Live testing</fullName>
            </value>
            <value>
                <fullName>5 - Production cut over</fullName>
            </value>
            <value>
                <fullName>Unassigned Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Related_Delivery_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Delivery_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Delivery Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Phase Tickets</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Phase__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Phase__c</fullName>
    <label>Delivery Phase</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseTriggerTest.cls
@isTest (seeAllData = true) public class CaseTriggerTest{
    
    @isTest static void testRun(){
        //Data Setup
        Account testAcc = new Account (Name = 'Test Account');
        insert testAcc;
        Opportunity testOpp = new Opportunity(Name = 'Test Opp',
                                              AccountId = testAcc.Id,
                                              StageName = '1. Prospect',
                                              CloseDate = date.valueOf('2014-01-01'));
        insert testOpp;
        //Perform Test
        Opportunity testOpp2 = [SELECT Id FROM Opportunity WHERE Name ='Test Opp' LIMIT 1];
        Case testCase1 = new Case(Related_Delivery_Opportunity__c = testOpp2.Id,
                                  Subject = 'Delivery - Test Opp',
                                  Delivery_Phase__c = '0 - Pre-Implementation Kick-off',
                                  Priority = 'Critical');
        insert testCase1;
        try{
            Case testCase2 = new Case(Related_Delivery_Opportunity__c = testOpp2.Id,
                                      Subject = 'Delivery - Test Opp',
                                      Delivery_Phase__c = '0 - Pre-Implementation Kick-off',
                                      Priority = 'Critical');
            insert testCase2;  
        } catch (DmlException e){
            String message = e.getMessage();
        }
        
    }  
}