force-app/main/default/objects/Case/fields/Dormant_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Dormant_End_Date__c</fullName>
    <label>Dormant End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dormant_Reason__c.field-meta.xml
<CustomField>
    <fullName>Dormant_Reason__c</fullName>
    <inlineHelpText>This is a free text area to put in any notes regarding the Dormant status</inlineHelpText>
    <label>Dormant Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Estimated_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Completion_Date__c</fullName>
    <inlineHelpText>This is the date that the delivery owner has estimated to complete the delivery.</inlineHelpText>
    <label>Estimated Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Dormant_History__c/Delivery_Dormant_History__c.object-meta.xml
<CustomObject>
    <label>Delivery Dormant History</label>
    <nameField>
        <displayFormat>DDH-{00000}</displayFormat>
        <label>Delivery Dormant History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Dormant Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Dormant_History__c/fields/Activated_Automatically__c.field-meta.xml
<CustomField>
    <fullName>Activated_Automatically__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activated Automatically</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Delivery_Dormant_History__c/fields/Dormant_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Dormant_End_Date__c</fullName>
    <label>Dormant End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Dormant_History__c/fields/Dormant_Reason__c.field-meta.xml
<CustomField>
    <fullName>Dormant_Reason__c</fullName>
    <inlineHelpText>Please enter information about this dormant status instance</inlineHelpText>
    <label>Dormant Reason Additional Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Delivery_Dormant_History__c/fields/Related_Delivery_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Related_Delivery_Ticket__c</fullName>
    <label>Related Delivery Ticket</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Delivery Dormant Record</relationshipLabel>
    <relationshipName>Delivery_Dormant_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Attainable_TTV_annual__c.field-meta.xml
<CustomField>
    <fullName>Attainable_TTV_annual__c</fullName>
    <formula>attainable_ttv_monthly__c * 12</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attainable GDV (annual)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Compare_Annual_GDV__c.field-meta.xml
<CustomField>
    <fullName>Compare_Annual_GDV__c</fullName>
    <formula>IF( BLANKVALUE(SOM_Estimated_Annual_GDV__c, 0 )  =   BLANKVALUE(Attainable_TTV_annual__c,  0 ) , &quot;true&quot;, &quot;false&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Compare Annual GDV</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Compare_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Compare_Completion_Date__c</fullName>
    <formula>IF( BLANKVALUE(SOM_Estimated_Completion__c, TODAY() )  =   BLANKVALUE(Estimated_Completion_Date__c,  TODAY() ) ,  &quot;true&quot;, &quot;false&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Compare Completion Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dormant_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Dormant_End_Date__c</fullName>
    <formula>Related_Ticket__r.Dormant_End_Date__c</formula>
    <label>Dormant End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Estimated_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Completion_Date__c</fullName>
    <inlineHelpText>This is the date that the delivery owner has forecast for the completion of the delivery.</inlineHelpText>
    <label>Estimated Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SOM_Estimated_Annual_GDV__c.field-meta.xml
<CustomField>
    <fullName>SOM_Estimated_Annual_GDV__c</fullName>
    <label>SOM_Estimated_Annual_GDV</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SOM_Estimated_Completion__c.field-meta.xml
<CustomField>
    <fullName>SOM_Estimated_Completion__c</fullName>
    <label>SOM Estimated Completion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Log__c/Process_Log__c.object-meta.xml
<CustomObject>
    <label>Process Log</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Log__c/fields/Completed_Successfully__c.field-meta.xml
<CustomField>
    <fullName>Completed_Successfully__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Completed Successfully</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Process_Log__c/fields/Process_Failed__c.field-meta.xml
<CustomField>
    <fullName>Process_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Process Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Process_Log__c/fields/Process_Message__c.field-meta.xml
<CustomField>
    <fullName>Process_Message__c</fullName>
    <label>Process Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Process_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Log__c/fields/Trace__c.field-meta.xml
<CustomField>
    <fullName>Trace__c</fullName>
    <label>Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/StartOfMonthTasks.cls
global class StartOfMonthTasks implements Schedulable {
   /*
        If today is Start of Month then;
            For all Opportunities that are not Closed update the fields as follows 
                Opp.SOM_Estimated_Completion__c = Opp.Estimated_Completion_Date__c;
                Opp.SOM_Estimated_Annual_GDV__c = Opp.Attainable_TTV_annual__c;
             
   */
   
    public boolean overrideDate = false;
   
    global void execute(SchedulableContext SC){

        List<Delivery_Dormant_History__c> dormantHistoryList = [select id, Dormant_End_Date__c, Dormant_Reason__c from Delivery_Dormant_History__c where Dormant_End_Date__c = :date.today() and Related_Delivery_Ticket__r.Status = 'Dormant']; 
        Process_Log__c log = new Process_Log__c(Process_Name__c = 'StartOfMonthTasks Scheduled Job');
        log.Process_Message__c = 'Processing records: ';
        for (Delivery_Dormant_History__c dH : dormantHistoryList) {
            log.Process_Message__c += ' ' + dH.Id + ',';
        }
        insert log;

        try {
            for(Delivery_Dormant_History__c dormantHistory : dormantHistoryList ){
                dormantHistory.Activated_Automatically__c = true;
                dormantHistory.Dormant_Reason__c = (string.IsBlank(dormantHistory.Dormant_Reason__c) ? '' : dormantHistory.Dormant_Reason__c + '\r\n') + 'Dormant period expired, reactivating delivery automatically';
            }
            if (!dormantHistoryList.isEmpty()) update dormantHistoryList;
            log.Completed_Successfully__c = true;
            update log;
        } catch (Exception e) {
            log.trace__c = 'Type: ' + e.getTypeName() + '\n' + 'Cause: ' + e.getCause() + '\n' + 'Message: '
                           + e.getMessage() + '\n' + 'Line #: ' + e.getLineNumber() + '\n' + e.getStackTraceString();
            log.process_failed__c = true;
            update log;
        }

        if ( date.today().day() == 1 || overrideDate ){
            Process_Log__c log2 = new Process_Log__c(Process_Name__c = 'StartOfMonthTasks Scheduled Job');
            log2.Process_Message__c = 'Running start of month process';
            insert log2;
            try {
                //*** SF-1595: Modified the select 
                List<Opportunity> opportunities = new List<Opportunity>();
                for (Opportunity Opp : [select SOM_Estimated_Completion__c, Estimated_Completion_Date__c, SOM_Estimated_Annual_GDV__c, Attainable_TTV_annual__c 
                                     from Opportunity where IsClosed = false and (Compare_Completion_Date__c = 'false' or Compare_Annual_GDV__c = 'false')]) {
                    Opp.SOM_Estimated_Completion__c = Opp.Estimated_Completion_Date__c;
                    Opp.SOM_Estimated_Annual_GDV__c = Opp.Attainable_TTV_annual__c;
                    opportunities.add( Opp );

                    if ( opportunities.size() >= 100)
                    {
                        update opportunities;
                        opportunities.clear();
                    }

                }
         
                if (!opportunities.isEmpty()) update opportunities;
                log2.Completed_Successfully__c = true;
                update log2;
            } catch (Exception e) {
                log2.trace__c = 'Type: ' + e.getTypeName() + '\n' + 'Cause: ' + e.getCause() + '\n' + 'Message: '
                               + e.getMessage() + '\n' + 'Line #: ' + e.getLineNumber() + '\n' + e.getStackTraceString();
                log2.process_failed__c = true;
                update log2;
            }

        }
        
    }
   
    public static string defaultSchedule = '0 0 1 ? * *';
   
    public static void schedule(){
        StartOfMonthTasks.schedule(defaultSchedule);
    }
   
    public static void Run(){
        Run(false);
    }

    public static void Run(boolean forceCreationofTasks){
        StartOfMonthTasks tasks = new StartOfMonthTasks();
        tasks.overrideDate = forceCreationofTasks;
        tasks.execute(null);
    }

    public static void schedule(string sch){
        StartOfMonthTasks m = new StartOfMonthTasks();
        system.schedule('Start of Month Tasks', sch, m);    
    }
 
}