force-app/main/default/objects/Case/fields/On_Behalf_of_Account__c.field-meta.xml
<CustomField>
    <fullName>On_Behalf_of_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>On Behalf of Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ticket Created On Behalf of Account</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/On_Behalf_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>On_Behalf_of_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>On Behalf of Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>On Behalf of Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/TestUpdateOnBehalfofAccount.cls
@isTest
public class TestUpdateOnBehalfofAccount{
    
   
        
    static testMethod void testUpdate(){
    
        TestCreateData testData = new TestCreateData();
        
        Account acc = testData.createAccount();
        System.debug('The account id is ' + acc.Id);
        
        Contact contact = testData.createContact(acc.Id);
        System.debug('The contact id is ' + contact.Id);
        
        Case servicetkt = testData.createServiceTicket(contact.Id);
        servicetkt.RecordTypeId = '01290000000hwKc';
        servicetkt.On_Behalf_of_Contact__c = contact.Id;
        
        update servicetkt;
        
        System.debug('The On behalf of account is ' + servicetkt.On_Behalf_of_Account__c);
        System.debug('The case id is ' + servicetkt.Id);
    }
    
    
}