force-app/main/default/objects/Case/fields/Ticket_Thread_ID__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Thread_ID__c</fullName>
    <formula>&quot;[ ref:_&quot; &amp; LEFT( $Organization.Id ,5) &amp; SUBSTITUTE(RIGHT( $Organization.Id ,11), &quot;0&quot;, &quot;&quot; )&amp; &quot;._&quot; &amp; LEFT(Id,5) &amp; SUBSTITUTE(Left(RIGHT(Id,10), 5), &quot;0&quot;, &quot;&quot;) &amp; RIGHT(Id,5) &amp; &quot;:ref ]&quot;</formula>
    <inlineHelpText>Please copy this thread Id and the brackets to the end of the subject of any email related to this ticket. which are retained in the eNett Delivery mailbox.
This will allow the email to be attached to the ticket by the system.</inlineHelpText>
    <label>Ticket Thread ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Email__c/Inbound_Email__c.object-meta.xml
<CustomObject>
    <label>Inbound Email</label>
    <nameField>
        <displayFormat>EML-{000000}</displayFormat>
        <label>Inbound Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inbound_Email__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Ticket</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Inbound Emails</relationshipLabel>
    <relationshipName>Inbound_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inbound_Email__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Inbound_Email__c/fields/Headers__c.field-meta.xml
<CustomField>
    <fullName>Headers__c</fullName>
    <label>Headers</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Inbound_Email__c/fields/Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Received_Date__c</fullName>
    <label>Received Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Inbound_Email__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/TESTInboundEmail.cls
@isTest
private class TESTInboundEmail {

    static testMethod void TESTInsertTrigger() {
        Test.startTest();
        //Must Pass basic null checks
        
        System.Debug('**** Starting TestInsertTrigger ****');
        Inbound_email__c firstNullInsert = new Inbound_email__c();
        insert firstNullInsert;
        system.assertNotEquals( null, firstNullInsert.Id);

        Inbound_Email__c newEmail = new Inbound_Email__c( Subject__c = 'NoSubjectThreadId', From__c = 'inoundemail@test.com', Headers__c = 'TEST\nOF\nHEADERS', Received_Date__c = DateTime.Now());
        insert newEmail;
        system.assertNotEquals( null, newEmail.Id);
        
        newEmail = [select case__c from Inbound_Email__c where Id = :newEmail.Id];
        system.AssertEquals( null, newEmail.case__c);
        
        Case newCase = new Case(Priority = 'Not None');
        insert newCase;
        Case testCase = [select Id, Ticket_Thread_ID__c from Case where Id = :newCase.Id];
        System.Debug('**** Finding case:' + testCase);
        Inbound_Email__c newValidInsert = new Inbound_Email__c( Subject__c = 'The test of a new reference ' + testCase.Ticket_Thread_ID__c, From__c = 'inoundemail@test.com', Headers__c = 'TEST\nOF\nHEADERS', Received_Date__c = DateTime.Now());
        insert newValidInsert;
        
        newValidInsert = [select Id, case__c from Inbound_Email__c where Id = :newValidInsert.Id];
        system.assertEquals(testCase.Id, newValidInsert.case__c);
        
        Test.stopTest();
    }
    
    
    static testMethod void TESTEmailUtilities(){
        Test.startTest();
  
        // create a new email 
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        email.subject = 'Subject asdas asdasd ';
        email.plainTextBody = 'Test email';
        email.fromname = 'FirstName LastName';
        email.toAddresses = new String[] {'someaddress@email.com'};
        email.ccAddresses = new String[] {'one@email.com','two@email.com'};

        String csv = 'this is just a test';
  
        // add an attachment
        Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
        attachment.body = blob.valueOf(csv);
        attachment.fileName = 'data.csv';
        attachment.mimeTypeSubType = 'text/plain';
  
        email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment };
  
        Messaging.InboundEmail.TextAttachment tattachment = new Messaging.InboundEmail.TextAttachment();
        tattachment.body = csv;
        tattachment.fileName = 'data.csv';
        tattachment.mimeTypeSubType = 'text/plain';
  
        email.textAttachments = new Messaging.inboundEmail.TextAttachment[] { tattachment };
  
        // call the email service class and test it with the data in the testMethod
        Messaging.InboundEmailResult result = EmailUtilities.processInboundEmail( email );
        System.assert(result.success == true);
        Test.stopTest();
    } 
 
    static testMethod void testValidMethod() {
        Test.startTest();
  
        // create a new email 
        Case newCase = new Case(Priority = 'Not None');
        insert newCase;
        Case testCase = [select Id, Ticket_Thread_ID__c from Case where Id = :newCase.Id];
        System.Debug('**** Finding case:' + testCase);

        // create a new email 
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        email.subject = 'Subject asdas asdasd ' + testCase.Ticket_Thread_ID__c;
        email.plainTextBody = 'Test email';
        email.htmlBody = '<b>Plain Text</b>';
        email.fromname = 'FirstName LastName';
        email.toAddresses = new String[] {'someaddress@email.com'};
        email.ccAddresses = new String[] {'one@email.com','two@email.com'};

        String csv = 'this is just a test';
  
        // add an attachment
        Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
        attachment.body = blob.valueOf(csv);
        attachment.fileName = 'data.csv';
        attachment.mimeTypeSubType = 'text/plain';
  
        email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment };
  
        Messaging.InboundEmail.TextAttachment tattachment = new Messaging.InboundEmail.TextAttachment();
        tattachment.body = csv;
        tattachment.fileName = 'data.csv';
        tattachment.mimeTypeSubType = 'text/plain';
  
        email.textAttachments = new Messaging.inboundEmail.TextAttachment[] { tattachment };
  
        // call the email service class and test it with the data in the testMethod
        Messaging.InboundEmailResult result = EmailUtilities.processInboundEmail( email );
        System.assert(result.success == true);
        Test.stopTest();
    }   
    
    static testMethod void TEST_BUSINESS_PROCESS() {
        Test.startTest();
  
        // create a new email 
        Case newCase = new Case( Priority = 'Not None');
        insert newCase;
        Case testCase = [select Id, Ticket_Thread_ID__c from Case where Id = :newCase.Id];
        System.Debug('**** Finding case:' + testCase);

        // create a new email 
        Messaging.InboundEmail email = new Messaging.InboundEmail() ;
        email.subject = 'Subject asdas asdasd ' + testCase.Ticket_Thread_ID__c;
        email.plainTextBody = 'Test email';
        email.htmlBody = '<b>Plain Text</b>';
        email.fromname = 'FirstName LastName';
        email.toAddresses = new String[] {'someaddress@email.com'};
        email.ccAddresses = new String[] {'one@email.com','two@email.com'};

        String csv = 'this is just a test';
  
        // add an attachment
        Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
        attachment.body = blob.valueOf(csv);
        attachment.fileName = 'data.csv';
        attachment.mimeTypeSubType = 'text/plain';
  
        email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment };
  
        Messaging.InboundEmail.TextAttachment tattachment = new Messaging.InboundEmail.TextAttachment();
        tattachment.body = csv;
        tattachment.fileName = 'data.csv';
        tattachment.mimeTypeSubType = 'text/plain';
  
        email.textAttachments = new Messaging.inboundEmail.TextAttachment[] { tattachment };
  
        // call the email service class and test it with the data in the testMethod
        Messaging.InboundEmailResult result = EmailUtilities.processInboundEmail( email );
        System.assert(result.success == true);
        
        Inbound_Email__c newValidInsert = [select Id, case__c from Inbound_Email__c order by Received_Date__c desc limit 1];
        newValidInsert.case__c = testCase.id;
        update newValidInsert;
        
        Test.stopTest();
    } 
    
    static testMethod void TEST_ASSIGN_INBOUNDEMAIL_TO_CASE() {
        Test.startTest();
  
        // create a new Inbound email record with a Case Ref ID
        //1) Get the ID from Case
        Case newCase = new Case( Priority = 'Not None');
        insert newCase;
        Case testCase = [select Id, Ticket_Thread_ID__c from Case where Id = :newCase.Id];
        System.Debug('**** Finding case:' + testCase);
        System.Debug('**** Finding case Thread_ID:' + testCase.Ticket_Thread_ID__c);
        // create a new Inbound email
        String emailFromName = 'Someone';
        String emailFromAddress ='someaddress@email.com';
        String htmlBody= '<b>Plain Text</b>';
        String eamilToAddress= 'one@email.com';
        String Subject='Subject asdas asdasd ' + testCase.Ticket_Thread_ID__c;
         
        Inbound_Email__c inBoundEmail = eNettTestUtility.createInboundEmail(emailFromName, emailFromAddress, htmlBody, eamilToAddress,Subject);         
          
        Inbound_Email__c newValidInsert = [select Id, Case__c from Inbound_Email__c Where ID = :inBoundEmail.ID ];
        System.Debug('**** From Select ID:' + newValidInsert.Id);
        System.Debug('**** From Select case:' + newValidInsert.case__c);
        System.Debug('**** From Actual case:' + testCase.ID);
        System.assertEquals(newValidInsert.case__c, testCase.ID);
        
        Test.stopTest();
    } 
}