force-app/main/default/objects/eNett_Contract__c/eNett_Contract__c.object-meta.xml
<CustomObject>
    <label>eNett Contract</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>eNett Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eNett Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/eNett_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eNett Contract</relationshipLabel>
    <relationshipName>eNett_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Contract_Stage__c.field-meta.xml
<CustomField>
    <fullName>Contract_Stage__c</fullName>
    <label>Contract Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1. New</fullName>
                <default>true</default>
                <label>1. New</label>
            </value>
            <value>
                <fullName>2. Awaiting Approval by Sales</fullName>
            </value>
            <value>
                <fullName>3. Awaiting Approval by Finance</fullName>
            </value>
            <value>
                <fullName>4. Awaiting Approval by Legal</fullName>
            </value>
            <value>
                <fullName>5. Proposal / Negotiation / Signoff</fullName>
            </value>
            <value>
                <fullName>6. Awaiting eNett Signoff</fullName>
            </value>
            <value>
                <fullName>7. Contract Signed by eNett</fullName>
            </value>
            <value>
                <fullName>8. T&amp;C&#39;s Accepted</fullName>
            </value>
            <value>
                <fullName>9. Agreement not reached</fullName>
            </value>
            <value>
                <fullName>Contract Preparation</fullName>
            </value>
            <value>
                <fullName>Awaiting eNett Signoff</fullName>
            </value>
            <value>
                <fullName>Contract Signed by eNett</fullName>
            </value>
            <value>
                <fullName>Awaiting Contract Upload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Contract_Termination_Reason__c.field-meta.xml
<CustomField>
    <fullName>Contract_Termination_Reason__c</fullName>
    <label>Contract Termination Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Flight</fullName>
                <default>true</default>
                <label>In Flight</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InactivateContractsProductRemoval.cls
global class InactivateContractsProductRemoval {

    @InvocableMethod
    public static void InactivateAccountContractsProductRemoval (List<Id> accIds) {

        List<eNett_Contract__c> contractUpdateList = new LIST<eNett_Contract__c>();
        
        for (eNett_Contract__c e : [SELECT Id, Status__c FROM eNett_Contract__c WHERE Account_Name__c IN :accIds AND Status__c <> 'Inactive']) {
            e.Status__c = 'Inactive';
            e.Contract_Termination_Reason__c = 'Contract deactivated due to product Removal.';
            e.Contract_Stage__c = '9. Agreement not reached';
            contractUpdateList.add(e);
        }

        database.update(contractUpdateList, false);

    }
}