force-app/main/default/objects/eNett_Contract__c/eNett_Contract__c.object-meta.xml
<CustomObject>
    <label>eNett Contract</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>eNett Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eNett Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/eNett_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eNett Contract</relationshipLabel>
    <relationshipName>eNett_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/eNett_Product__c.field-meta.xml
<CustomField>
    <fullName>eNett_Product__c</fullName>
    <label>eNett Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Flight</fullName>
                <default>true</default>
                <label>In Flight</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InactivateContractsProductRemovalEFTTest.cls
@isTest
public class InactivateContractsProductRemovalEFTTest {
    
    @isTest static void InactivateContractsProductRemovalEFTTest(){
        
    // Data setup
    List<Id> accIds = new List<Id>();
    Account acct = new Account (Name = 'testAccount');
    insert acct;
    accIds.add(acct.Id);
     
    eNett_Contract__c e = new eNett_Contract__c(Account_Name__c = acct.id,
                                               eNett_Product__c = 'eNett EFT');
    insert e;
    // Perform test
    Test.startTest();
    InactivateContractsProductRemoval_EFT.InactivateAccountContractsProductRemoval_EFT(accIds);    
    Test.stopTest();
        
    // Verify
    eNett_Contract__c e2 = [SELECT Id, Status__c FROM eNett_Contract__c WHERE Id = :e.Id ];
    System.assertEquals('Inactive',e2.Status__c);
    }
}