force-app/main/default/objects/eNett_Contract__c/eNett_Contract__c.object-meta.xml
<CustomObject>
    <label>eNett Contract</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>eNett Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eNett Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/eNett_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eNett Contract</relationshipLabel>
    <relationshipName>eNett_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Contract_Stage__c.field-meta.xml
<CustomField>
    <fullName>Contract_Stage__c</fullName>
    <label>Contract Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1. New</fullName>
                <default>true</default>
                <label>1. New</label>
            </value>
            <value>
                <fullName>2. Awaiting Approval by Sales</fullName>
            </value>
            <value>
                <fullName>3. Awaiting Approval by Finance</fullName>
            </value>
            <value>
                <fullName>4. Awaiting Approval by Legal</fullName>
            </value>
            <value>
                <fullName>5. Proposal / Negotiation / Signoff</fullName>
            </value>
            <value>
                <fullName>6. Awaiting eNett Signoff</fullName>
            </value>
            <value>
                <fullName>7. Contract Signed by eNett</fullName>
            </value>
            <value>
                <fullName>8. T&amp;C&#39;s Accepted</fullName>
            </value>
            <value>
                <fullName>9. Agreement not reached</fullName>
            </value>
            <value>
                <fullName>Contract Preparation</fullName>
            </value>
            <value>
                <fullName>Awaiting eNett Signoff</fullName>
            </value>
            <value>
                <fullName>Contract Signed by eNett</fullName>
            </value>
            <value>
                <fullName>Awaiting Contract Upload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard T&amp;Cs</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Contract not required</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Internal Transacting</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Flight</fullName>
                <default>true</default>
                <label>In Flight</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContractBulkUpload.cls
public with sharing class ContractBulkUpload {

	//public class EContractException extends Exception{}
	
	
	//public ContractBulkUpload(){
	//    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Please select a region to update Standard T&Cs'));
	//	initPage();
	//}
	//private void initPage(){
	//    document = new Document(); 
	//	document.body = null; // clears the viewstate 
	//	region = null;
	//}
	
	///*   Static regions */
	//public List<SelectOption> getRegions() { 
 //       List<SelectOption> options = new List<SelectOption>(); 
 //       options.add(new SelectOption('APAC','APAC')); 
 //       options.add(new SelectOption('EMEA','EMEA')); 
 //       options.add(new SelectOption('Americas','Americas')); 
 //       return options; 
 //   } 
 //   /* Setters and getters */
	//public boolean getHasRegion(){
	//	return !string.IsBlank(region); 
	//}
	//public string Region{ get; set; }
	//public string getRegion(){
	//	return Region;
	//}
	//public void setRegion( string value){
	//	Region = value;
	//}
	
	//public string fileContentType = null;
	//public void setFileContentType(string value){
	//	fileContentType = value;
	//}
	//public string getFileContentType(){
	//	return fileContentType;
	//} 
	
 //   /* Action functions */
	//public PageReference LoadRegion(){
	//    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Please select the new Standard T&Cs PDF file for  ' + Region + ' and select Save'));
	//	return null;
	//}    
	//public PageReference LoadFile(){
	//	if ( string.IsBlank(fileContentType) || !FileContentType.toLowerCase().EndsWith('pdf')){
	//    	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select a PDF file to upload.'));
	//    	return null;
	//	}
	//	list<account> accounts = null;
	//	Savepoint sp = null;
	//	try
	//	{
	//		RecordType rt = [select Id from Recordtype where DeveloperName = 'Contract_Upload_PDF_Copy_of_Contract' LIMIT 1];
	
	//    	list<eNEtt_Contract__c> contracts = new list<eNEtt_Contract__c>();
	//		list<Attachment> attachments = new list<Attachment>();
	//		list<Task> tasks = new list<Task>();
	
	//		accounts = [select Id, Name from Account where Region__c = :region and Contract_Type__c = 'Standard T&Cs'];
	//		for( Account a : accounts){
	//		    contracts.add(new eNEtt_Contract__c(Account_Name__c = a.Id, Contract_Stage__c = '7. T&C\'s Accepted.', Status__c = 'Active' ));
	//		    attachments.add(new Attachment(Body = document.Body, ContentType = fileContentType, Description = 'eNett Standard T&C\'s uploaded for ' + region + ' at ' + datetime.now().format(), Name = document.Name));
	//		    tasks.add(new Task(ActivityDate = Date.Today(), Description = 'New T&C\'s added', Status = 'Closed', Subject = 'New Terms and Conditions uploaded for ' + region + ' at ' + datetime.now().format() + ' from PDF source ' + document.name, RecordTypeId = rt.Id)); 
	//		}
			
	//		List<eNEtt_Contract__c> CancelledContracts = [select Id from eNEtt_Contract__c where Status__c = 'Active' and Account_Name__c in :accounts];
	//		for(eNEtt_Contract__c contract : CancelledContracts)
	//			contract.Status__c = 'Inactive';
			
	//		sp = Database.setSavepoint();  //Set transaction control in case we fail 

 //       	database.update(CancelledContracts, true); //We failed on first error so dont check sr.isSuccess()
 //       	Database.SaveResult[] srList = Database.insert(contracts, true); 
 //       	for(integer recCount = 0; recCount < srList.size(); recCount++){
 //       		tasks[recCount].WhatId = srList[recCount].getId();
 //       		attachments[recCount].ParentId = srList[recCount].getId();
 //       	}
 //       	Database.insert(tasks, true);
 //       	Database.insert(attachments, true);
 //       }
 //       catch(Exception Ex){
 //       	if (sp != null ) Database.rollback(sp);
	//    	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'An error ocurred: ' + ex));
	//    	return null;
 //       }	 
 //       initPage();
 //   	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'T&Cs from file ' + document.name + ' uploaded to:'));
	//	for( Account a : accounts)
	//    	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, ' ' + a.Name));

	//	return null;
	//}
	
	// public Document document { 
	//    get { 
	//      if (document == null) 
	//        document = new Document(); 
	//      return document; 
	//    } 
	//    set; 
	//  } 

}