force-app/main/default/objects/eNett_Contract__c/eNett_Contract__c.object-meta.xml
<CustomObject>
    <label>eNett Contract</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>eNett Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eNett Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/eNett_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eNett Contract</relationshipLabel>
    <relationshipName>eNett_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Contract_Stage__c.field-meta.xml
<CustomField>
    <fullName>Contract_Stage__c</fullName>
    <label>Contract Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1. New</fullName>
                <default>true</default>
                <label>1. New</label>
            </value>
            <value>
                <fullName>2. Awaiting Approval by Sales</fullName>
            </value>
            <value>
                <fullName>3. Awaiting Approval by Finance</fullName>
            </value>
            <value>
                <fullName>4. Awaiting Approval by Legal</fullName>
            </value>
            <value>
                <fullName>5. Proposal / Negotiation / Signoff</fullName>
            </value>
            <value>
                <fullName>6. Awaiting eNett Signoff</fullName>
            </value>
            <value>
                <fullName>7. Contract Signed by eNett</fullName>
            </value>
            <value>
                <fullName>8. T&amp;C&#39;s Accepted</fullName>
            </value>
            <value>
                <fullName>9. Agreement not reached</fullName>
            </value>
            <value>
                <fullName>Contract Preparation</fullName>
            </value>
            <value>
                <fullName>Awaiting eNett Signoff</fullName>
            </value>
            <value>
                <fullName>Contract Signed by eNett</fullName>
            </value>
            <value>
                <fullName>Awaiting Contract Upload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Contract_Termination_Reason__c.field-meta.xml
<CustomField>
    <fullName>Contract_Termination_Reason__c</fullName>
    <label>Contract Termination Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Flight</fullName>
                <default>true</default>
                <label>In Flight</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InactivateContractsProductRemovalTest.cls
@isTest
public class InactivateContractsProductRemovalTest {
    
    @isTest static void InactiveContractTest(){
        
        // Data setup
        // List<eNett_Contract__c> testContractUpdateList = new List<eNett_Contract__c>();
        List<Id> accIds = new List<Id>();
        for (Integer i = 0; i< 5; i++){
            Account acct = new Account(Name = 'testAcct' + i);
            insert acct;
            accIds.add(acct.Id);
            eNett_Contract__c e = new eNett_Contract__c(Account_Name__c = acct.Id,
                                                        Status__c = 'Activated');
            insert e;
        }
        
        
        // Perform test
        Test.startTest();
        InactivateContractsProductRemoval.InactivateAccountContractsProductRemoval(accIds);
        Test.stopTest();
        
        // Verify 
    LIST<eNett_Contract__c> contracts = [SELECT Account_Name__c, Status__c, Contract_Termination_Reason__c, Contract_Stage__c 
                              FROM eNett_Contract__c WHERE Account_Name__c IN :accIds];
    for (Integer j =0; j < contracts.size(); j++){
       System.assertEquals('Inactive', contracts[j].Status__c);
       System.assertEquals('Contract deactivated due to product Removal.', contracts[j].Contract_Termination_Reason__c);
       System.assertEquals('9. Agreement not reached', contracts[j].Contract_Stage__c);       
    }
}
}