force-app/main/default/objects/EFT_Settlement_Approval__c/EFT_Settlement_Approval__c.object-meta.xml
<CustomObject>
    <label>EFT Settlement Approval</label>
    <nameField>
        <displayFormat>ESA-{0000000}</displayFormat>
        <label>EFT Settlement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EFT Settlement Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EFT_Settlement_Approval__c/fields/EFT_Settlement_Approval_Email__c.field-meta.xml
<CustomField>
    <fullName>EFT_Settlement_Approval_Email__c</fullName>
    <defaultValue>IF( RIGHT( $User.Username , LEN($User.Username) - LEN(&quot;@enett.com&quot;) - FIND(&quot;@enett.com.&quot;, $User.Username))= &#39;&#39;,&#39;APACCS@enett.com&#39;,&#39;salesforceadmin@enett.com&#39;)</defaultValue>
    <label>EFT Settlement Approval Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/UpdateEFTSettlemenApprovalEmail.cls
global class UpdateEFTSettlemenApprovalEmail implements Database.Batchable<sObject>, Database.Stateful {
	
    //instance member to retain state across transactions, keep track of how many records have been processed
    global Integer recordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('SELECT ID, EFT_Settlement_Approval_Email__c FROM EFT_Settlement_Approval__c');
    }
    
    global void execute(Database.BatchableContext bc, List<EFT_Settlement_Approval__c> scope){
        for (EFT_Settlement_Approval__c esa : scope){
            // populate the email field
            esa.EFT_Settlement_Approval_Email__c = 'APACCS@enett.com';
            // increment the instance member counter
            recordsProcessed = recordsProcessed + 1;
        }
        update scope;
    }
    
    global void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed + ' records have been processed.');
    }
}