force-app/main/default/objects/Due_Diligence_Escalation__c/Due_Diligence_Escalation__c.object-meta.xml
<CustomObject>
    <label>Due Diligence Escalation</label>
    <nameField>
        <displayFormat>DDE-{00000}</displayFormat>
        <label>Escalation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Due Diligence Escalation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Due_Diligence_Escalation__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Due Diligence Escalation</relationshipLabel>
    <relationshipName>Due_Diligence_Escalation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Due_Diligence_Escalation__c/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolution</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Due_Diligence_Escalation__c/fields/Resolved__c.field-meta.xml
<CustomField>
    <fullName>Resolved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Resolved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Due_Diligence_Escalation__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Due_Diligence_Escalation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PopUpDialog_DDEscalation.cls
public class PopUpDialog_DDEscalation {

    public class resolve extends PopUpDialogController.contExt {

        private Due_Diligence_Escalation__c ddEsc {get; set;}
        Id userId;
       
        public resolve(Id recId) {
            ddEsc = PopUpDialog_DDEscalation.loadDDEscalation(recId);
            userId = UserInfo.getUserId();
        }    
        
        public override String showConfirmMsg() {
            return 'Please enter the Escalation Resolution:';
        }

        public override String runProcess() {
            String return_URL = null;
            if (userTextInput == '')
                throw new applicationException('Escalation Resolution cannot be blank.');
            ddEsc.Resolved__c = true;
            ddEsc.Resolution__c = userTextInput;
            update ddEsc;
            if (ddEsc.Registration__c != null) {
                return_URL = ddEsc.Registration__c; 
            }
            return return_URL;
        }
        
        public override String runValidation() {
            if (ddEsc.Submitted_By__c == userId) { 
                return 'You cannot work on a Due Diligence Escalation that has been submitted by you.'; 
            } else if (ddEsc.OwnerId != userId) { 
                return 'Please reassign ownership to yourself to resolve the Due Diligence Escalation.';
            } else if (ddEsc.Resolved__c) {
                return 'This escalation record has already been resolved.';
            }
            return null;
        }
        
        public override Boolean showInputTextField() {
            return true;
        }

    }

    public static Due_Diligence_Escalation__c loadDDEscalation(Id recId) {
        Due_Diligence_Escalation__c ddE;
        ddE = [SELECT Id, Resolved__c, Submitted_By__c, OwnerId, Registration__c
               FROM Due_Diligence_Escalation__c
               WHERE Id = :recId];
        return ddE;
    }

    public class applicationException extends Exception {}
    
}