force-app/main/default/objects/ContentVersion/fields/Original_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Original_Record_Id__c</fullName>
    <description>This is populated by AttachmentTriggerHandler when this file is converted from an attachment</description>
    <label>Original Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Rating_Evidence__c/Risk_Rating_Evidence__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRiskAssessment</customHelpPage>
    <label>Risk Assessment</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Risk Assessment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Rating_Evidence__c/fields/Attachment_Count__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Attachment Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Risk_Rating_Evidence__c/fields/File_Attached__c.field-meta.xml
<CustomField>
    <fullName>File_Attached__c</fullName>
    <formula>Attachment_Count__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attachment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpVerification</customHelpPage>
    <label>Verification</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Verification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Attachment__c.field-meta.xml
<CustomField>
    <fullName>Attachment__c</fullName>
    <formula>Attachment_Count__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attachment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Attachment_Count__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Attachment Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Attachment_Status__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Status__c</fullName>
    <formula>if(Attachment_Count__c = 0,&quot;No Attachment&quot;,
if(Attachment_Count__c = 1,&quot;Document Attached&quot;,
&quot;Multiple Attachments&quot; ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attachment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AttachmentTriggerHandlerTest.cls
/*
 * This is a test class for AttachmentTriggerHandler
 * Ticket: SF-5145
 * Author: Ronnie Yang
 */
@isTest
public class AttachmentTriggerHandlerTest {
    private static testMethod void convertAttachmentToFileTest(){
        //create new case
        Case testCase = eNettTestUtility.createCase();
        //create new attachment under that case
        Attachment testAttachment = eNettTestUtility.createAttachment(testCase.Id);
        //assert attachment is deleted
        System.assertEquals(0, [SELECT Id 
                                FROM Attachment 
                                WHERE Id=: testAttachment.Id 
                                LIMIT 1].size());
        //assert there's contentversion inserted -- representing the version of the new file inserted
        ContentVersion newContentVersion = [SELECT Id, Title, VersionData, FirstPublishLocationId, ContentDocumentId
                                            FROM ContentVersion
                                            WHERE Original_Record_Id__c =: testAttachment.Id
                                            LIMIT 1];
        System.assertEquals(testAttachment.Name, newContentVersion.Title);
        System.assertEquals(testAttachment.Body.toString(), newContentVersion.VersionData.toString());
        System.assertEquals(testAttachment.ParentId, newContentVersion.FirstPublishLocationId);
        //assert there's contentdocument -- a document(file) can have many versions but each version can only be linked to one document
        ContentDocument newContentDocument = [SELECT Id, Title 
                                              FROM ContentDocument 
                                              WHERE Id =: newContentVersion.ContentDocumentId
                                              LIMIT 1];
        System.assertEquals(testAttachment.Name, newContentDocument.Title);
        //assert there's linkentity -- a document(file) can be linked to many records and a record can have many documents -- this is the junction object in the many-to-many relationship
        ContentDocumentLink newLinkEntity = [SELECT Id, LinkedEntityId, ContentDocumentId 
                                             FROM ContentDocumentLink 
                                             WHERE LinkedEntityId =: testCase.Id 
                                             AND ContentDocumentId =: newContentDocument.Id 
                                             LIMIT 1 ];
        System.assertNotEquals(null, newLinkEntity);
    }
    private static testMethod void refreshEvidenceCountOnInsertTest(){        
        //create new risk assessment
        Risk_Rating_Evidence__c testRiskAssessment = eNettTestUtility.createRiskAssessment(eNettTestUtility.createRegistration('Test Company',eNettTestUtility.createAccount('Test Account').Id).Id);
        //create new verificaiton
        Verification__c testVerification = eNettTestUtility.createVerification();
        
        //---verfiy count, checkbox and attachment status on Risk Assessment----
        //insert 1 attachment on Risk Assessment
        eNettTestUtility.createAttachment(testRiskAssessment.Id);
        //after insert
        testRiskAssessment = [SELECT Attachment_Count__c, File_Attached__c
                              FROM Risk_Rating_Evidence__c
                              WHERE Id =: testRiskAssessment.Id
                              LIMIT 1];
        System.assertEquals(1, testRiskAssessment.Attachment_Count__c);
        System.assertEquals(true, testRiskAssessment.File_Attached__c);
        
        //---verfiy count, checkbox and attachment status on Verification---
        //insert 1 attachment on Verification
        eNettTestUtility.createAttachment(testVerification.Id);
        testVerification = [SELECT Attachment_Status__c, Attachment_Count__c, Attachment__c
                            FROM Verification__c
                            WHERE Id =: testVerification.Id
                            LIMIT 1];
        //after insert
        System.assertEquals('Document Attached', testVerification.Attachment_Status__c);
        System.assertEquals(1, testVerification.Attachment_Count__c);
        System.assertEquals(true, testVerification.Attachment__c);
        //insert another attachment on Verification
        eNettTestUtility.createAttachment(testVerification.Id);
        testVerification = [SELECT Attachment_Status__c, Attachment_Count__c, Attachment__c
                            FROM Verification__c
                            WHERE Id =: testVerification.Id
                            LIMIT 1];
        //after insert
        System.assertEquals('Multiple Attachments', testVerification.Attachment_Status__c);
        System.assertEquals(2, testVerification.Attachment_Count__c);
        System.assertEquals(true, testVerification.Attachment__c);
    }
}