force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <label>Document Template</label>
    <nameField>
        <displayFormat>DT-{00000}</displayFormat>
        <label>Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/pocController.cls
public class pocController {

    public string renderMode {get; set;}
    public string contentType {get; set;}
    public string content {get; set;}
        
    public pocController(ApexPages.StandardController controller) {
        //ApexPages.currentPage().getParameters().get('id');
        if(ApexPages.currentPage().getParameters().get('renderAs') != null) {
            renderMode = 'pdf';
            contentType = null;
        } else {
            renderMode = null;
            contentType = null;
        }

        PageReference pageRef = new PageReference('/apex/Client_Agreement_AU_EFT_and_VANS?id=a1ZO00000096GJ0');
        String pageHTML = pageRef.getContent().toString();
        content = pageHTML + '<br/><p>' + [SELECT Content__c FROM Document_Template__c WHERE Id = 'a2AO0000000w2AI'][0].Content__c;
    }


}