force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <label>Document Template</label>
    <nameField>
        <displayFormat>DT-{00000}</displayFormat>
        <label>Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Flight</fullName>
                <default>true</default>
                <label>In Flight</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Template__c/recordTypes/Active.recordType-meta.xml
<RecordType>
    <fullName>Active</fullName>
    <active>true</active>
    <label>Active</label>
</RecordType>

force-app/main/default/objects/Document_Template__c/recordTypes/Archived.recordType-meta.xml
<RecordType>
    <fullName>Archived</fullName>
    <active>true</active>
    <label>Archived</label>
</RecordType>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Business_Number__c.field-meta.xml
<CustomField>
    <fullName>Business_Number__c</fullName>
    <label>Business Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Chargeback_Fee_With_Document__c.field-meta.xml
<CustomField>
    <fullName>Chargeback_Fee_With_Document__c</fullName>
    <label>Chargeback Fee With Document</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Chargeback_Fee_Without_Document__c.field-meta.xml
<CustomField>
    <fullName>Chargeback_Fee_Without_Document__c</fullName>
    <label>Chargeback Fee Without Document</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Bus Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/EFT_Default_Payment__c.field-meta.xml
<CustomField>
    <fullName>EFT_Default_Payment__c</fullName>
    <label>EFT Default Payment</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/EFT_Subscription_Fee__c.field-meta.xml
<CustomField>
    <fullName>EFT_Subscription_Fee__c</fullName>
    <description>The monthly price the customer will pay for EFT</description>
    <label>EFT Subscription Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/EFT_Transaction_Fee__c.field-meta.xml
<CustomField>
    <fullName>EFT_Transaction_Fee__c</fullName>
    <label>EFT Transaction Fee</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>From Lead</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/eNett_Account_Fee__c.field-meta.xml
<CustomField>
    <fullName>eNett_Account_Fee__c</fullName>
    <inlineHelpText>Replacing eNett Payments Platform Fee (VANs Subscription Fee)</inlineHelpText>
    <label>eNett Account Fee</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>From Lead</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>From Lead</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>From Lead</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>VirtualTerminal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registered_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Registered_Company_Name__c</fullName>
    <label>Registered Company Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Miss</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Mr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Standard_TCs_Template_EFT__c.field-meta.xml
<CustomField>
    <fullName>Standard_TCs_Template_EFT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Standard TCs Template EFT</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document_Template__c.Product__c</field>
            <operation>equals</operation>
            <value>eNett EFT</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Registrations (Standard TCs Template EFT)</relationshipLabel>
    <relationshipName>Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Standard_TCs_template_VANs__c.field-meta.xml
<CustomField>
    <fullName>Standard_TCs_template_VANs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Standard TCs Template VANs</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document_Template__c.Product__c</field>
            <operation>equals</operation>
            <value>VANs</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Subscription_Fee_Currency__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Fee_Currency__c</fullName>
    <label>Subscription Fee Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/VANs_Subscription_Fee__c.field-meta.xml
<CustomField>
    <fullName>VANs_Subscription_Fee__c</fullName>
    <description>The monthly price of VANs for the Customer</description>
    <label>VANs Subscription Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius, Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ClientAgreementController.cls
global without sharing class ClientAgreementController {

    global string renderMode {get; set;}
    global string contentType {get; set;}
    
    global string Id {get; private set;}
    global string Salutation {get; private set;}
    global string First_Name {get; private set;}
    global string Last_Name {get; private set;}
    global string Email {get; private set;}
    global string Products {get; private set;}    
    global string Phone {get; private set;}
    global string Registered_Company_Name {get; private set;}
    global string Business_Number {get; private set;}
    global string Country {get; private set;}
    global string Subscription_Fee_Currency {get; private set;}
    global string EFT_Subscription_Fee {get; private set;}
    global string EFT_Transaction_Fee {get; private set;}
    global string EFT_Default_Payment {get; private set;}
    global string VANs_Subscription_Fee {get; private set;}
    global string eNett_Account_Fee {get; private set;}
    global string Chargeback_Fee_With_Document {get; private set;}
    global string Chargeback_Fee_Without_Document {get; private set;}
    global Id Standard_TCs_Template_VANs {get; private set;}
    global Id Standard_TCs_Template_EFT {get; private set;}

    global ClientAgreementController() {
        if (ApexPages.currentPage().getParameters().get('renderAs') != null) {
            String renderAs = ApexPages.currentPage().getParameters().get('renderAs');
            if (renderAs == 'pdf') {
                renderMode = 'pdf';
                contentType = null;
            } else if (renderAs == 'html') {
                renderMode = null;
                contentType = 'html';
            } else {
                renderMode = null;
                contentType = null;
            }
        } else {
            renderMode = null;
            contentType = null;
        }

        if (ApexPages.currentPage().getParameters().get('Id') != null)
            loadReg(ApexPages.currentPage().getParameters().get('Id'));
    }
    
    global ClientAgreementController(Id regId) {
        loadReg(regId);
    }
    
    public void loadReg (Id regId) {
        Registration__c reg;
        if (regId != null) {
            this.id = regId;
            LIST<Registration__c> regs = [SELECT Id, Salutation__c, First_Name__c, Last_Name__c, Email__c, Phone__c,
                                          Registered_Company_Name__c, Business_Number__c, Country__c, Product__c,
                                          Subscription_Fee_Currency__c, EFT_Subscription_Fee__c, EFT_Transaction_Fee__c,
                                          EFT_Default_Payment__c, VANs_Subscription_Fee__c, Chargeback_Fee_With_Document__c,
                                          eNett_Account_Fee__c, Chargeback_Fee_Without_Document__c, 
                                          Standard_TCs_Template_EFT__c, Standard_TCs_Template_VANs__c
                                          FROM Registration__c WHERE Id = :this.Id LIMIT 1];
            if (!regs.isEmpty())
                reg = regs[0];
        }
        
        if (reg != null) {
            this.Salutation = reg.Salutation__c;
            this.First_Name = reg.First_Name__c;
            this.Last_Name = reg.Last_Name__c;
            this.Email = reg.Email__c;
            this.Phone = reg.Phone__c;
            this.Registered_Company_Name = reg.Registered_Company_Name__c;
            this.Business_Number = reg.Business_Number__c;
            this.Country = reg.Country__c;
            this.Products = reg.Product__c;            
            this.Subscription_Fee_Currency = reg.Subscription_Fee_Currency__c;
            this.EFT_Subscription_Fee = (reg.EFT_Subscription_Fee__c == null) ? '' : string.valueof(reg.EFT_Subscription_Fee__c);
            this.EFT_Transaction_Fee = (reg.EFT_Transaction_Fee__c == null) ? '' : string.valueof(reg.EFT_Transaction_Fee__c);
            this.EFT_Default_Payment = (reg.EFT_Default_Payment__c == null) ? '' : string.valueof(reg.EFT_Default_Payment__c);
            this.VANs_Subscription_Fee = (reg.VANs_Subscription_Fee__c == null) ? '' : string.valueof(reg.VANs_Subscription_Fee__c);
            this.eNett_Account_Fee = (reg.eNett_Account_Fee__c == null) ? '' : string.valueof(reg.eNett_Account_Fee__c);
            this.Chargeback_Fee_With_Document = (reg.Chargeback_Fee_With_Document__c == null) ? '' : string.valueof(reg.Chargeback_Fee_With_Document__c);
            this.Chargeback_Fee_Without_Document = (reg.Chargeback_Fee_Without_Document__c == null) ? '' : string.valueof(reg.Chargeback_Fee_Without_Document__c);
            this.Standard_TCs_Template_VANs = reg.Standard_TCs_Template_VANs__c;
            this.Standard_TCs_Template_EFT = reg.Standard_TCs_Template_EFT__c;            
        }    
    }
    
    public static string removeCarriageReturns (String s) {
        s = s.replace('\r\n', '');
        s = s.replace('\n', '');
        s = s.replace('\r', '');
        return s;        
    }
  
    public string getMergedHTML() {
        if (this.Id == null) return '';
        PageReference pageRef = getPageReference(this.Id, this.Country, this.Products, 'html');
        string pageHTML = '';
        if (pageRef != null) pageHTML = ClientAgreementController.removeCarriageReturns(pageRef.getContent().toString());
        return pageHTML;
    }    

    public Blob getMergedPDF() {
        if (this.Id == null) return null;
        PageReference pageRef = getPageReference(this.Id, this.Country, this.Products, 'pdf');
        Blob pdfBlob = null;
        if (pageRef != null) pdfBlob = pageRef.getContent();
        return pdfBlob;
    }

    public static void savePDF(Id regId, Id targetId) {
        ClientAgreementController cAC = new ClientAgreementController(regId);
        
        Attachment att = new Attachment();
        att.parentId = targetId;
        att.name = 'Client Agreement.pdf';
        att.body = cAC.getMergedPDF();
        att.contentType = 'application/pdf';
        insert att;
    }

    private static PageReference getPageReference(Id regId, String regCountry, String regProducts, String renderAs) {
        if (regid == null) return null;
        PageReference pageRef;    
        if (regCountry == 'Australia') {
            if (regProducts.contains('VANs') && regProducts.contains('eNett EFT')) {
                pageRef = new PageReference('/apex/Client_Agreement_AU_EFT_and_VANS?renderAs=' + renderAs + '&id=' + regID);
            } else if (regProducts.contains('eNett EFT')) {
                pageRef = new PageReference('/apex/Client_Agreement_AU_EFT?renderAs=' + renderAs + '&id=' + regID);
            } else {
                pageRef = new PageReference('/apex/Client_Agreement_AU_VANs?renderAs=' + renderAs + '&id=' + regID);
            }
        } else if (regCountry == 'New Zealand') {
            if (regProducts.contains('VANs') && regProducts.contains('eNett EFT')) {
                pageRef = new PageReference('/apex/Client_Agreement_NZ_EFT_and_VANS?renderAs=' + renderAs + '&id=' + regID);
            } else if (regProducts.contains('eNett EFT')) {
                pageRef = new PageReference('/apex/Client_Agreement_NZ_EFT?renderAs=' + renderAs + '&id=' + regID);
            } else {
                pageRef = new PageReference('/apex/Client_Agreement_ROW_VANS?renderAs=' + renderAs + '&id=' + regID);
            }        
        } else {
            pageRef = new PageReference('/apex/Client_Agreement_ROW_VANS?renderAs=' + renderAs + '&id=' + regID);
        }

        return pageRef;
    }

    public string getTermsAndConditionsHTML() {
        if (this.Id == null) return '';
        String s = '';
        if (this.Products.contains('VANs') && this.Standard_TCs_Template_VANs != null) {
            for (Document_Template__c dT : [SELECT Content__c FROM Document_Template__c 
                                            WHERE Id = :this.Standard_TCs_Template_VANs 
                                            AND (Status__c = 'Active' OR Status__c = 'Archived')
                                            LIMIT 1]) {
                s += dT.content__c;
            }
        }
        if (this.Products.contains('VANs') && this.Products.contains('eNett EFT')) {
            s += '<br/><br/><br/>';
        }
        if (this.Products.contains('eNett EFT') && this.Standard_TCs_Template_EFT != null) {
            for (Document_Template__c dT : [SELECT Content__c FROM Document_Template__c 
                                            WHERE Id = :this.Standard_TCs_Template_EFT 
                                            AND (Status__c = 'Active' OR Status__c = 'Archived')
                                            LIMIT 1]) {
                s += dT.content__c;
            }
        }
        return s;
    }

}