force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <label>Document Template</label>
    <nameField>
        <displayFormat>DT-{00000}</displayFormat>
        <label>Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template__c/fields/Output_Filename__c.field-meta.xml
<CustomField>
    <fullName>Output_Filename__c</fullName>
    <label>Output Filename</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GeneratePDFInvocable.cls
global class GeneratePDFInvocable {

    @InvocableMethod (label='Generate Document')
    global static void GeneratePDFInvocable (LIST<GeneratePDFRequest> requests) {
        for (GeneratePDFRequest request : requests) {
            GeneratePDFInvocable.generatePDF(request.documentTemplateId, request.parentID);
        }
    }
    
    global class GeneratePDFRequest {
        @InvocableVariable(required=true)
        public ID documentTemplateId;

        @InvocableVariable(required=true)
        public ID parentID;
    }
 
    @future(callout=true)
    private static void generatePDF(Id documentTemplateId, Id parentID) {
        PageReference pageRef = new PageReference('/apex/DocumentTemplateTest?id=' + documentTemplateId);
        Blob docBody = pageRef.getContentAsPDF();
        String filename = [SELECT Output_Filename__c FROM Document_Template__c WHERE Id = :documentTemplateId].Output_Filename__c;
        Attachment a = new Attachment(Body = docBody, Name = filename, ParentId = parentID, contentType='application/pdf');
        insert a;       
    }
 
}