force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <label>Document Template</label>
    <nameField>
        <displayFormat>DT-{00000}</displayFormat>
        <label>Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template__c/fields/Content__c.field-meta.xml
<CustomField>
    <fullName>Content__c</fullName>
    <label>Content</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <label>Document Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Flight</fullName>
                <default>true</default>
                <label>In Flight</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Template__c/recordTypes/Active.recordType-meta.xml
<RecordType>
    <fullName>Active</fullName>
    <active>true</active>
    <label>Active</label>
</RecordType>

force-app/main/default/objects/Document_Template__c/recordTypes/Archived.recordType-meta.xml
<RecordType>
    <fullName>Archived</fullName>
    <active>true</active>
    <label>Archived</label>
</RecordType>

force-app/main/default/classes/documentTemplateBeforeTriggerTest.cls
/**
* This is a test class class for the document Template Trigger. 
@author : Arun Sivanesan

@version : 1.0

@update : Arun Sivanesan updated on 25/07/2019 for adding 3 new method; if required Jira ticket number - PDS-3699
**/

@isTest 
private class documentTemplateBeforeTriggerTest {

       /**
         Method to test new template insert and Update
       **/

    static testMethod void unitTest() {
        Document_Template__c dT = new Document_Template__c(Document_Name__c = 'Test',
                                                           Status__c = 'In Flight', Content__c = 'This is Test Document');//SF-5277 17/10/2018 Jasmine - Add status to the test document template
        insert dT;
        
        dT.Document_Name__c = 'Update Test';
        dT.Content__c = 'This is Test Document Update';
        update dT;
    }
    
     /**
         Method to test new template insert and Update to Active Status and then create another new template and make it as current Active
     **/
    static testMethod void updateActiveTest() {
        Document_Template__c dT = new Document_Template__c(Document_Name__c = 'Test',
                                                           Status__c = 'In Flight');//
        insert dT;
        
        dT.Status__c = 'Active';
        update dT;
        
        Document_Template__c dT1 = new Document_Template__c(Document_Name__c = 'Test',
                                                           Status__c = 'In Flight');//
        insert dT1;

        dT1.Status__c = 'Active';
        update dT1;
        
    }
     /**
         Method to test new template insert and Update to Active Status and then Make it as Archived
     **/
         
    static testMethod void updateArchivedTest() {
        Document_Template__c dT = new Document_Template__c(Document_Name__c = 'Test',
                                                           Status__c = 'In Flight');//
        insert dT;
        
        dT.Status__c = 'Active';
        update dT;
        
        
        dT.Status__c = 'Archived';
        update dT;        
    }
     /**
         Method to test new template insert and Delete it
     **/
             
 
     static testMethod void DeleteTest() {
        Document_Template__c dT = new Document_Template__c(Document_Name__c = 'Test',
                                                           Status__c = 'In Flight');//
        insert dT;
        
        delete dT;       
    }   
    
}