force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <label>Document Template</label>
    <nameField>
        <displayFormat>DT-{00000}</displayFormat>
        <label>Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template__c/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <label>Activation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Related_Regions__c.field-meta.xml
<CustomField>
    <fullName>Related_Regions__c</fullName>
    <label>Related Regions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Flight</fullName>
                <default>true</default>
                <label>In Flight</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Client Agreement</fullName>
            </value>
            <value>
                <fullName>Terms and Conditions</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Template__c/recordTypes/Active.recordType-meta.xml
<RecordType>
    <fullName>Active</fullName>
    <active>true</active>
    <label>Active</label>
</RecordType>

force-app/main/default/classes/GetStandardTCTemplate.cls
global class GetStandardTCTemplate {

    private static MAP<String, String> templateAssignmentMap;
    
    static {
        templateAssignmentMap = new MAP<String, String>();

        for (Document_Template__c dT : [SELECT Id, Product__c, Related_Regions__c 
                                        FROM Document_Template__c
                                        WHERE Type__c = 'Terms and Conditions'
                                        AND Status__c = 'Active'
                                        AND Product__c != null
                                        ORDER BY Activation_Date__c DESC]) {
            for (String region : dT.Related_Regions__c.split(';')) {
                if (!templateAssignmentMap.containsKey(region + dT.Product__c)) templateAssignmentMap.put(region + dT.Product__c, dT.Id);
            }
        }
    }
    
    public static Id getStandardTCTemplate (String region, String product) {
        Id TemplateId = null;
        if (templateAssignmentMap.containsKey(region + product)) {
            TemplateId = templateAssignmentMap.get(region + product);
        }
        return TemplateId;
    }

    public static Id getStandardTCTemplate (String regionproduct) {
        Id TemplateId = null;
        if (templateAssignmentMap.containsKey(regionproduct)) {
            TemplateId = templateAssignmentMap.get(regionproduct);
        }
        return TemplateId;
    }

}