force-app/main/default/objects/recTypesRBA__c/recTypesRBA__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Record Types - Registration Bank Account</label>
</CustomObject>

force-app/main/default/objects/recTypesRBA__c/fields/Funding_Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Funding_Read_Only__c</fullName>
    <label>Funding Read Only</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/recTypesRBA__c/fields/Other_Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Other_Read_Only__c</fullName>
    <label>Other Read Only</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/recTypesVer__c/recTypesVer__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Record Types - Verification</label>
</CustomObject>

force-app/main/default/objects/recTypesVer__c/fields/Bank_Account_Evidence_Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Evidence_Read_Only__c</fullName>
    <label>Bank Account Evidence Read Only</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>eNett Internal</fullName>
            </value>
            <value>
                <fullName>eNett Internal Demo</fullName>
            </value>
            <value>
                <fullName>eNett Internal Transacting</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Referred Client</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration_Bank_Account__c/Registration_Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Registration Bank Account</label>
    <nameField>
        <displayFormat>RBA-{000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Bank_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payable</fullName>
            </value>
            <value>
                <fullName>Receivable</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Bank_Account__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Registration_Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Bank_Account__c/fields/Verification__c.field-meta.xml
<CustomField>
    <fullName>Verification__c</fullName>
    <formula>verFlag__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration_Bank_Account__c/recordTypes/Funding.recordType-meta.xml
<RecordType>
    <fullName>Funding</fullName>
    <active>true</active>
    <label>Funding</label>
</RecordType>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpVerification</customHelpPage>
    <label>Verification</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Verification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipName>Company_Information_Evidence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Registration_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Registration_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration Bank Account</label>
    <referenceTo>Registration_Bank_Account__c</referenceTo>
    <relationshipName>Information_Evidence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvocableMethods.cls
public class InvocableMethods {

    @InvocableMethod
    public static void SetAccountsAndVersToReadOnly(List<Id> regIds) {
    
        LIST<Registration_Bank_Account__c> bAs = new LIST<Registration_Bank_Account__c>();
        LIST<Id> bAIds = new LIST<Id>();
        recTypesRBA__c recTypesBA = recTypesRBA__c.getInstance();
        recTypesVer__c recTypesV = recTypesVer__c.getInstance();
        
        for (Registration_Bank_Account__c bA : [SELECT Id, Account_Type__c FROM Registration_Bank_Account__c WHERE Registration__c IN :regIds AND Active__c = true]) {
            //bA.Active__c = false;
            if (bA.Account_Type__c != null && bA.Account_Type__c == 'Funding') {
                bA.RecordTypeId = recTypesBA.Funding_Read_Only__c;
            } else {
                bA.RecordTypeId = recTypesBA.Other_Read_Only__c;
            }
            bAs.add(bA);
            bAIds.add(bA.Id);
        }
    
        List<Verification__c> vers = new List<Verification__c>();        
        for (Verification__c v : [SELECT Id FROM Verification__c WHERE Registration_Bank_Account__c IN :bAIds]) {
            //v.Active__c = false;
            v.RecordTypeId = recTypesV.Bank_Account_Evidence_Read_Only__c;
            vers.add(v);
        }

        update bAs;
        update vers;

    }
    
}