force-app/main/default/objects/Journal__c/Journal__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpJournals</customHelpPage>
    <label>DD Journal</label>
    <nameField>
        <label>Journal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DD Journal</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal__c/fields/Read_Only__c.field-meta.xml
<CustomField>
    <fullName>Read_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Journal__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipName>Internal_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PopUpDialog_JournalExts.cls
public class PopUpDialog_JournalExts {

    public class deleteJournal extends PopUpDialogController.contExt {

        private Journal__c jnl {get; set;}
        
        public deleteJournal(Id recId) {
            jnl = loadLead(recId);
        }    
            
        public override String runProcess() {
            String return_URL = jnl.Registration__c;
            delete jnl;
            return return_URL;
        }
  
        public override String showConfirmMsg() {
            return 'You are about to delete this journal entry.  Are you sure?';
        }

        public override String runValidation() {
            if (jnl.Read_Only__c) {
                return 'Journal records can only be deleted during Due Diligence.';
             }
            return null;
        }

    }    
    
    public static Journal__c loadLead(Id recId) {
        Journal__c jnl;
        jnl = [SELECT Id, Read_Only__c, Registration__c FROM Journal__c WHERE Id = :recId];
        return jnl;
    }
    
}