force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>eNett Internal</fullName>
            </value>
            <value>
                <fullName>eNett Internal Non Transacting</fullName>
            </value>
            <value>
                <fullName>eNett Internal Transacting</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Automatically populated. This field is only populated for accounts which are activated in client database.</inlineHelpText>
    <label>ECN</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/eNett_products__c.field-meta.xml
<CustomField>
    <fullName>eNett_products__c</fullName>
    <label>eNett Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>VirtualTerminal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <formula>Account.ECN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ECN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/Process_Task__c.object-meta.xml
<CustomObject>
    <label>Process Task</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Process Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Tasks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <label>ECN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateProcessTasksBatchTest.cls
@isTest public class CreateProcessTasksBatchTest {
    @testSetup static void SetUpData(){
        Account testAcc = eNettTestUtility.createAccount('TestAccount');
        testAcc.eNett_products__c = 'VANs';
        Test.setCreatedDate(testAcc.Id, DateTime.newInstance(2018, 09, 25));
        update testAcc;
        Process_Task__c testOppPT = new Process_Task__c (Subject__c = 'Opportunity - Qualify Opportunity',
                                                         Account__c = testAcc.Id);
        insert testOppPT;
        
        Account testAcc2 = new Account (Name = 'TestAccount2', ECN__c ='100000',eNett_products__c = 'VANs');
        insert testAcc2;
        Test.setCreatedDate(testAcc.Id, DateTime.newInstance(2018, 09, 25));
        update testAcc2;
        
        Process_Task__c testOppPT2 = new Process_Task__c (Subject__c = 'Opportunity - Qualify Opportunity',
                                                          Account__c = testAcc2.Id);
        insert testOppPT2;
        Process_Task__c testAPPT = new Process_Task__c (Subject__c = 'Approve Account',
                                                        Account__c = testAcc2.Id);
        insert testAPPT;
    }
    
    @isTest static void testTaskNotExist(){
        Test.startTest();
        CreateProcessTasksBatch cptb = new CreateProcessTasksBatch();
        Id batchJobId = Database.executeBatch(cptb);
        Test.stopTest();
        
        Account assertAcc = [SELECT ID, Account_Type__c, eNett_Products__c, (SELECT Subject__c FROM Process_Tasks__r ORDER BY Subject__c) FROM Account WHERE Name = 'TestAccount' LIMIT 1];
        System.debug('#####assertAcc ' + assertAcc);
        List<Process_Task__c> assertTask = [SELECT ID, Subject__c FROM Process_Task__c WHERE Account__c =: assertAcc.Id AND Subject__c = 'Approve Account'];
        System.assertEquals(1, assertTask.size());
    }
    
    @isTest static void testTaskExists(){
        Test.startTest();
        CreateProcessTasksBatch cptb = new CreateProcessTasksBatch();
        Id batchJobId = Database.executeBatch(cptb);
        Test.stopTest();
        
        Account assertAcc2 = [SELECT ID, Account_Type__c, eNett_Products__c, (SELECT Subject__c FROM Process_Tasks__r ORDER BY Subject__c) FROM Account WHERE Name = 'TestAccount2' LIMIT 1];
        List<Process_Task__c> assertTask = [SELECT ID, Subject__c FROM Process_Task__c WHERE Account__c =: assertAcc2.Id AND Subject__c = 'Approve Account'];
        System.assertEquals(1, assertTask.size());
    }
}