force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>Automatically populated. Status is only updated to &#39;Client&#39; once the account is activated in the client database.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Active</fullName>
                <default>true</default>
                <label>Not Active</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>eNett Internal</fullName>
            </value>
            <value>
                <fullName>eNett Internal Non Transacting</fullName>
            </value>
            <value>
                <fullName>eNett Internal Transacting</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CMPA_received__c.field-meta.xml
<CustomField>
    <fullName>CMPA_received__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This applies to VANs customer only</description>
    <inlineHelpText>This applies to VANs customer only</inlineHelpText>
    <label>CMPA received?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DD_Status__c.field-meta.xml
<CustomField>
    <fullName>DD_Status__c</fullName>
    <inlineHelpText>Automatically updated based on the progress of DD.</inlineHelpText>
    <label>DD Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting Client</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Approval In Progress</fullName>
            </value>
            <value>
                <fullName>DD Approved</fullName>
            </value>
            <value>
                <fullName>DD Declined</fullName>
            </value>
            <value>
                <fullName>Risk Rating Review</fullName>
            </value>
            <value>
                <fullName>Non Responsive</fullName>
            </value>
            <value>
                <fullName>Needs More Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/product_contracts_active__c.field-meta.xml
<CustomField>
    <fullName>product_contracts_active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Product Contracts Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reference_Registration__c.field-meta.xml
<CustomField>
    <fullName>Reference_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <inlineHelpText>Automatically updated based on the progress of the Registration.</inlineHelpText>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting Acceptance</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>New (Product)</fullName>
            </value>
            <value>
                <fullName>Rejected - Non-responsive</fullName>
            </value>
            <value>
                <fullName>Rejected - Spam/test application</fullName>
            </value>
            <value>
                <fullName>Rejected - Application N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Affiliate.recordType-meta.xml
<RecordType>
    <fullName>Affiliate</fullName>
    <active>true</active>
    <description>A company that is associated to another company (is an affiliate of another company) - Affiliate and the parent have different ABN, ACN and legal entity name</description>
    <label>Affiliate</label>
</RecordType>

force-app/main/default/classes/AccountStatusBannerExtensionTest.cls
/**
 * This class contains unit tests for validating the behavior of AccountStatusBannerExtension Apex class
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 *
 * author : Surajsingh Thakur
 * Date   : 28/12/2017 
 */
@isTest (SeeAllData = true)
private class AccountStatusBannerExtensionTest {

    static testMethod void testAccountStatusBannerExtension() {
        Account testAccount = eNettTestUtility.createAccount('Test Account');
        testAccount.DD_Status__c = 'DD Approved';
        testAccount.Account_Type__c = 'Affiliate';
        testAccount.Account_Status__c = 'Deactivated';
        //testAccount.Reference_Registration__c = 'DD Approved';
        testAccount.Registration_Status__c = 'Complete';
        testAccount.product_contracts_active__c = true;
        testAccount.CMPA_received__c = true;
        update testAccount;
        
        eNettTestUtility.createOpportunity('TestOpp',testAccount.id); 
        
        Apexpages.currentPage().getParameters().put('id',testAccount.id);
        ApexPages.StandardController sc = new ApexPages.StandardController(testAccount);
        AccountStatusBannerExtension testAccountControllerExtension = new AccountStatusBannerExtension(sc);
        
        //Assert RenderRegColumn = false
        System.assertEquals(testAccountControllerExtension.RenderRegColumn,false);
    }
}