force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>Automatically populated. Status is only updated to &#39;Client&#39; once the account is activated in the client database.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Active</fullName>
                <default>true</default>
                <label>Not Active</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <inlineHelpText>This field is automatically populated by the Client system integration.</inlineHelpText>
    <label>Job Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Master administrator</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Delivery Implementation</fullName>
            </value>
            <value>
                <fullName>Operational / Technical</fullName>
            </value>
            <value>
                <fullName>Operational / Technical SMEs</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Left Account</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <inlineHelpText>This field is automatically populated by the Eloqua integration.</inlineHelpText>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Business Owner/Proprietor</fullName>
            </value>
            <value>
                <fullName>Chairperson</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>CIO</fullName>
            </value>
            <value>
                <fullName>CMO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Travel Consultant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>From Lead</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>From Lead</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>From Lead</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>From Lead</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Miss</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Mr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SynchRegContactWithAccount.cls
public class SynchRegContactWithAccount {

    // Note: the requirements have changed for the umpteenth time, so all the contact synching code & process flows are now a rather convoluted mess.
    // This will need to be cleaned up at some point although this can't be done until the desired behaviour has been clarified.
    @InvocableMethod
    public static void SynchContactWithAccount (LIST<ID> regIds) {

        MAP<Id, Id> regToAccIdmap = new MAP<Id, Id>();      
        MAP<Id, LIST<Contact>> accIdContactsMap = new MAP<Id, LIST<Contact>>();
        MAP<Id, Boolean> accActiveMap = new MAP<Id, Boolean>();
        LIST<Id> accIds = new LIST<Id>();
        SET<Registration__c> regsWithAccount = new SET<Registration__c>();
        LIST<Contact> contactUpdates = new LIST<Contact>();
        LIST<Contact> newContacts = new LIST<Contact>();
        
        // Create set of all related Account Ids
        for (Registration__c r : [SELECT Id, Salutation__c, First_Name__c, Last_Name__c, Job_Role__c, Account__c, Email__c, Phone__c FROM Registration__c WHERE Id IN :regIds]) {
            If (r.Account__c != null) {
                accIds.add(r.Account__c);
                regsWithAccount.add(r);
            }
        }
        
        //PDS-6401 - Rework the logic to extract Contacts as below commented code throws Governance limit in subquery object extract.
        //        1) Get only the Active Contacts
        //        2) loop through list of contacts and add it to a list and then add it back accIdContactsMap
        
        // Create map of account ids and related contacts        
        for (Account a : [SELECT Id, Account_Status__c, (SELECT Id, FirstName, LastName, Job_Role__c, Phone, Email FROM Contacts WHERE Status__c = 'Active' ORDER BY CreatedDate DESC) FROM Account WHERE Id IN :accIds]) {
            LIST<Contact> accountContacts = new LIST<Contact>();
            
            for (Contact c : a.Contacts){
                accountContacts.add(c);
            }

            if (accountContacts.Size() != 0)
            {
             accIdContactsMap.put(a.Id, accountContacts);             
             if (a.Account_Status__c != null && a.Account_Status__c == 'Active') {
                    accActiveMap.put(a.Id, true);                 
                } 
             else {
                    accActiveMap.put(a.Id, false);                                        
                }
            }
        }
                
        
        // 
        Boolean matchingContact;
        Boolean matchingPrimaryFound;
        Boolean primaryFound;
        String jobRole;
        for (Registration__c reg : regsWithAccount) {
            matchingContact = false;
            matchingPrimaryFound = false;

            // Patch for SF-3495 - Changes need refactoring since convoluted!
            for (Contact c : accIdContactsMap.get(reg.Account__c)) {
                if (c.Job_Role__c != null && c.Job_Role__c.contains('Primary')) primaryFound = true;
                if (c.FirstName == reg.First_Name__c && c.LastName == reg.Last_Name__c) {
                    if (c.Job_Role__c != null && c.Job_Role__c.contains('Primary')) {
                        matchingPrimaryFound = true;
                    }                   
                }
            }
                        
            for (Contact c : accIdContactsMap.get(reg.Account__c)) {
                if (c.FirstName == reg.First_Name__c && c.LastName == reg.Last_Name__c) {
                    jobRole = (c.Job_Role__c == null) ? '' : c.Job_Role__c;
                    if (jobRole.contains('Primary') || !matchingPrimaryFound) {
                        if (!jobRole.contains('Primary') || c.Email != reg.Email__c || c.Phone != reg.Phone__c) {
                            if (!(accActiveMap.get(reg.Account__c) && primaryFound)) {
                                if (!jobRole.contains('Primary')) {
                                    c.Job_Role__c = (c.Job_Role__c == null) ? 'Primary' : c.Job_Role__c + '; Primary';
                                }
                                c.Email = reg.Email__c;
                                c.Phone = reg.Phone__c;
                                c.Title__c = reg.Job_Role__c;
                                c.Primary_Email_Address__c = reg.Email__c;
                                contactUpdates.add(c);
                            }
                        }
                    }
                    matchingContact = true;
                }               
            }
            if (!matchingContact) {
                if (!(accActiveMap.get(reg.Account__c) && primaryFound)) {
                    newContacts.add(new Contact(Salutation = reg.Salutation__c,
                                            FirstName = reg.First_Name__c,
                                            LastName = reg.Last_Name__c,
                                            Email = reg.Email__c,
                                            Primary_Email_Address__c = reg.Email__c,
                                            Phone = reg.Phone__c,
                                            Job_Role__c = 'Primary;',
                                            AccountId = reg.Account__c,
                                            Title__c = reg.Job_Role__c));
                }
            }
        }
        
        update contactUpdates;
        insert newContacts;
    }
    
}