force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>Automatically populated. Status is only updated to &#39;Client&#39; once the account is activated in the client database.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Active</fullName>
                <default>true</default>
                <label>Not Active</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Children_Yearly_Actual_USD__c.field-meta.xml
<CustomField>
    <fullName>Children_Yearly_Actual_USD__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Combined total value of yearly actual USD from all children accounts.</description>
    <label>Children Yearly Actual USD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/eNett_products__c.field-meta.xml
<CustomField>
    <fullName>eNett_products__c</fullName>
    <label>eNett Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>VirtualTerminal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Yearly_Actual__c.field-meta.xml
<CustomField>
    <fullName>Yearly_Actual__c</fullName>
    <label>Yearly Actual USD</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>A customer using VAN or EFT- client can be travel or corporate</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Customer__c/Customer__c.object-meta.xml
<CustomObject>
    <label>Customer</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer__c/fields/Annual_GDV__c.field-meta.xml
<CustomField>
    <fullName>Annual_GDV__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Annual GDV</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Customer__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ParentGDVProcessorTest.cls
/*
* This is a test class for ParentGDVProcessor
* Ticket: SF-5230
* Author: Ronnie Yang
*/
@IsTest
public class ParentGDVProcessorTest {
    @testSetup
    private static void setUp(){
        Customer__c customer = eNettTestUtility.createCustomer('Customer');
        Account parent = eNettTestUtility.createAccount('Parent');
        parent.Customer__c = customer.Id;
        Account child = eNettTestUtility.createAccountWithParent('Child', parent.Id);
        Account grandchild = eNettTestUtility.createAccountWithParent('Grandchild', child.Id);
        
        List<Account> accountsToUpdate = new List<Account>();
        accountsToUpdate.add(parent);
        accountsToUpdate.add(child);
        accountsToUpdate.add(grandchild);
        
        for(Account a : accountsToUpdate){
            a.Yearly_Actual__c = 1;
            a.eNett_Products__c = 'VANs';
            a.Account_Status__c = 'Active';
        }
        
        update accountsToUpdate;
    }
    
    private static testMethod void test(){
        Test.startTest();
        Id batchId = Database.executeBatch(new ParentGDVProcessor());
        Test.stopTest();
        Account parent = [SELECT Id, Yearly_Actual__c, Children_Yearly_Actual_USD__c
                          FROM Account
                          WHERE Name = 'Parent'
                          LIMIT 1];
        Account child = [SELECT Id, Yearly_Actual__c, Children_Yearly_Actual_USD__c
                         FROM Account
                         WHERE Name = 'Child'
                         LIMIT 1];
        Account grandchild = [SELECT Id, Yearly_Actual__c, Children_Yearly_Actual_USD__c
                              FROM Account
                              WHERE Name = 'Grandchild'
                              LIMIT 1];
        Customer__c testCustomer = [SELECT Name, Annual_GDV__c
                                    FROM Customer__c
                                    WHERE Name = 'Customer'
                                    LIMIT 1];
        System.debug(parent);
        System.debug(child);
        System.debug(grandchild);
        System.debug(testCustomer);
        System.assertEquals(1, child.Children_Yearly_Actual_USD__c);
        System.assertEquals(2, parent.Children_Yearly_Actual_USD__c);
        System.assertEquals(3, testCustomer.Annual_GDV__c);
    }
}