force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>eNett Internal</fullName>
            </value>
            <value>
                <fullName>eNett Internal Non Transacting</fullName>
            </value>
            <value>
                <fullName>eNett Internal Transacting</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task__c/Process_Task__c.object-meta.xml
<CustomObject>
    <label>Process Task</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Process Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Tasks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Account_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Email__c</fullName>
    <label>Account Owner Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Assigned_Date__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Date__c</fullName>
    <label>Assigned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <label>Related Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Related_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Related_Account_Type__c</fullName>
    <label>Related Account Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/recordTypes/VANs_Account_Approval_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>VANs_Account_Approval_Record_Type</fullName>
    <active>true</active>
    <description>This record type is for ‘Approve Account’ process tasks that decide where a registration should be assigned to. Only applicable for new accounts with &#39;VANs&#39; product.</description>
    <label>VANs Account Approval Record Type</label>
</RecordType>

force-app/main/default/classes/AccountApprovalTask.cls
/**
* This is a controller class class for the VF page - PostRefersh. 
It holds the business logic to create 'Account Approval' process task for when added VANs product.
@ticket: SF-01010
@author : Jasmine Nguyen
@version : 1.0
**/
global class AccountApprovalTask{
    @InvocableMethod (label = 'Create Account Approval Task') 
    global static void createAccountApprovalTask(List<Id> accIds){
        Group apQueue = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'Account_Approval_Queue'];
        RecordType recId = [SELECT Id FROM RecordType WHERE DeveloperName = 'VANs_Account_Approval_Record_Type'];
        List<Account> accList = [SELECT Id, Name, Owner.Email, Account_Type__c FROM Account WHERE Id IN: accIds];
        List<Process_Task__c> ptList = new List<Process_Task__c>();
        for (Account acc : accList){
            Process_Task__c accPT = new Process_Task__c (Subject__c = 'Approve Account',
                                                         Related_Account_Type__c = acc.Account_Type__c,
                                                         RecordTypeId = recId.Id,
                                                         Account__c = acc.Id,
                                                         OwnerId = apQueue.Id,
                                                         Assigned_Date__c = Date.today(),
                                                         Due_Date__c = CalculateBusinessDays.AddBusinessDays(Date.today(), 2),
                                                         Related_Account__c = acc.Name,
                                                         Account_Owner_Email__c = acc.Owner.Email);
            ptList.add(accPT);
        }
        try{
            insert ptList; 
        } catch (DMLException e){
            System.debug('The following exception has occured: ' + e.getMessage());
        }
    }
}