force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>eNett Internal</fullName>
            </value>
            <value>
                <fullName>eNett Internal Non Transacting</fullName>
            </value>
            <value>
                <fullName>eNett Internal Transacting</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>RBA_Address_Line_1__c</fullName>
    <label>Reg Bus Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>RBA_Address_Line_2__c</fullName>
    <label>Reg Bus Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_City__c.field-meta.xml
<CustomField>
    <fullName>RBA_City__c</fullName>
    <label>Reg Bus City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_Country__c.field-meta.xml
<CustomField>
    <fullName>RBA_Country__c</fullName>
    <label>Reg Bus Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_Postcode__c.field-meta.xml
<CustomField>
    <fullName>RBA_Postcode__c</fullName>
    <label>Reg Bus Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_State_Province__c.field-meta.xml
<CustomField>
    <fullName>RBA_State_Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reg Bus State Province</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RBA_Country__c</field>
            <operation>equals</operation>
            <valueField>State_Detail__c.Country_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Detail__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>A customer using VAN or EFT- client can be travel or corporate</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/classes/AsyncUpdateChildAccounts.cls
/**
 * Asynchronus queueable job to update child Accounts 
 * Author: Kishore Potla
 * Date: 17/10/2019
 * 
 * Note: Due to a complicated account hierarchy of Flight Centre customer, updating Registered Business Adderess on parent ECN
 *       will trigger AfterUpdate trigger event on all its children account. Which is throwing 'Apex CPU time limit exceeded' exception.
 *       Hence Asynchronus queueable job is written to update children accounts. 
 * 
 * [03/Jan/2020] PDS-6874: Only Additonal ECNs should have same RBA as their parent. Affiliates, Customers and any other accounts should not.
 **/
 
public class AsyncUpdateChildAccounts implements Queueable {
    private   Map<Id, Account> accMap= new Map<Id, Account>();
    
    public AsyncUpdateChildAccounts (Map<Id, Account> childrenToScan ){
        accMap = childrenToScan;
    }
    public void execute(QueueableContext context) {

        List<Account> allChildAccounts = new List<Account>();
        List<Account> updateChildAccounts = new List<Account>();
        Map<Id, Account> curLevelChildAccounts = new Map<Id, Account>();
        Set<Id> curLevelParentAccIds = new Set<Id>(accMap.keySet());
        Integer level = 0;
        while(curLevelParentAccIds.size() > 0){
            curLevelChildAccounts = getChildAccounts(curLevelParentAccIds);
            if(curLevelChildAccounts.size() > 0){
                allChildAccounts.addAll(curLevelChildAccounts.values());
                System.debug('########### Count of child Additional ECNs in hierarchy level '+ ++level + ' is ' + curLevelChildAccounts.size());
                curLevelParentAccIds.clear();
                curLevelParentAccIds.addAll(curLevelChildAccounts.keySet());
            }else{
                curLevelParentAccIds.clear();
                System.debug('########### Child Accounts check :: Last level in the Account hierarchy is reached. No more child accounts');
            }
        }
        
        //Update all child accounts registered business address with parent account's RBA
        Account parent = accMap.get(new List<Id>(accMap.keySet()).get(0));
        for(Account a : allChildAccounts){
            if(a.RBA_Address_Line_1__c != parent.RBA_Address_Line_1__c || a.RBA_Address_Line_2__c != parent.RBA_Address_Line_2__c || a.RBA_City__c != parent.RBA_City__c || 
                    a.RBA_Country__c != parent.RBA_Country__c || a.RBA_Postcode__c != parent.RBA_Postcode__c ||  a.RBA_State_Province__c != parent.RBA_State_Province__c){
                a.RBA_Address_Line_1__c = parent.RBA_Address_Line_1__c;
                a.RBA_Address_Line_2__c = parent.RBA_Address_Line_2__c;
                a.RBA_City__c = parent.RBA_City__c;
                a.RBA_Country__c = parent.RBA_Country__c;
                a.RBA_Postcode__c = parent.RBA_Postcode__c;
                a.RBA_State_Province__c = parent.RBA_State_Province__c; 
                        
                updateChildAccounts.add(a); //To update only if RBA is not same as their parent.
            }
        }
        update updateChildAccounts;
        System.debug('########### Total No. of children Accounts updated are: ' + updateChildAccounts.size());     

    }
    // Returns all child Additional ECNs of Parent Ids.
     public Map<Id, Account> getChildAccounts(Set<id> parentAccIds){
        Map<Id, Account> childAccs = new Map<Id, Account>();
        childAccs = new Map<Id, Account>([SELECT Id, RBA_Address_Line_1__c, RBA_Address_Line_2__c, RBA_City__c, 
                                           RBA_Country__c, RBA_Postcode__c, RBA_State_Province__c, Parent.Id
                                           FROM Account 
                                           WHERE Parent.Id IN:parentAccIds
                                             AND Account_Type__c = 'Additional ECN']);
        return childAccs;
    }

}