force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>Automatically populated. Status is only updated to &#39;Client&#39; once the account is activated in the client database.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Active</fullName>
                <default>true</default>
                <label>Not Active</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>eNett Internal</fullName>
            </value>
            <value>
                <fullName>eNett Internal Non Transacting</fullName>
            </value>
            <value>
                <fullName>eNett Internal Transacting</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Awaiting_CMPA__c.field-meta.xml
<CustomField>
    <fullName>Awaiting_CMPA__c</fullName>
    <formula>AND(INCLUDES(Reference_Registration__r.Product__c, &#39;VANs&#39;), 
    ISPICKVAL(Account_Type__c, &#39;Customer&#39;), 
    /*ISPICKVAL(Reference_Registration__r.Agreement_Type__c, &#39;Standard T&amp;Cs&#39;),*/
    ISPICKVAL( Contract_Type__c , &#39;Standard T&amp;Cs&#39;),
    NOT(CMPA_received__c),
	OR(NOT(ISPICKVAL(Account_Status__c, &#39;Active&#39;)), AND(Add_VANs__c, NOT(INCLUDES(eNett_products__c, &#39;VANs&#39;))))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Awaiting CMPA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CMPA_received__c.field-meta.xml
<CustomField>
    <fullName>CMPA_received__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This applies to VANs customer only</description>
    <inlineHelpText>This applies to VANs customer only</inlineHelpText>
    <label>CMPA received?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DD_Status__c.field-meta.xml
<CustomField>
    <fullName>DD_Status__c</fullName>
    <inlineHelpText>Automatically updated based on the progress of DD.</inlineHelpText>
    <label>DD Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting Client</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Approval In Progress</fullName>
            </value>
            <value>
                <fullName>DD Approved</fullName>
            </value>
            <value>
                <fullName>DD Declined</fullName>
            </value>
            <value>
                <fullName>Risk Rating Review</fullName>
            </value>
            <value>
                <fullName>Non Responsive</fullName>
            </value>
            <value>
                <fullName>Needs More Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Opportunity_Status__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Status__c</fullName>
    <description>When an opportunity is updated, a trigger is fired to update its parent account&#39;s opportunity status appropriately. This field exists so in the account view/report, users can quickly understand any new account&#39;s onboarding status.
If an opportunity of the account is open and in progress, this picklist will then display that opportunity&#39;s stage name instead of the values available.</description>
    <label>Opportunity Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Available</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Product Removed</fullName>
            </value>
            <value>
                <fullName>All Closed/Lost</fullName>
            </value>
            <value>
                <fullName>Qualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/product_contracts_active__c.field-meta.xml
<CustomField>
    <fullName>product_contracts_active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Product Contracts Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reference_Registration__c.field-meta.xml
<CustomField>
    <fullName>Reference_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <inlineHelpText>Automatically updated based on the progress of the Registration.</inlineHelpText>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting Acceptance</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>New (Product)</fullName>
            </value>
            <value>
                <fullName>Rejected - Non-responsive</fullName>
            </value>
            <value>
                <fullName>Rejected - Spam/test application</fullName>
            </value>
            <value>
                <fullName>Rejected - Application N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Affiliate.recordType-meta.xml
<RecordType>
    <fullName>Affiliate</fullName>
    <active>true</active>
    <description>A company that is associated to another company (is an affiliate of another company) - Affiliate and the parent have different ABN, ACN and legal entity name</description>
    <label>Affiliate</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>A customer using VAN or EFT- client can be travel or corporate</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <description>A Company (eNett client or non eNett client) refers eNett products to other companies.</description>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/eNett_Contract__c/eNett_Contract__c.object-meta.xml
<CustomObject>
    <label>eNett Contract</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>eNett Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eNett Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/eNett_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eNett Contract</relationshipLabel>
    <relationshipName>eNett_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>eNett Contract</relationshipLabel>
    <relationshipName>eNett_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Flight</fullName>
                <default>true</default>
                <label>In Flight</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <label>Referrer</label>
</RecordType>

force-app/main/default/classes/AccountStatusBannerExtension.cls
global class AccountStatusBannerExtension {
    private String accId {get; set;}
    private String RegStatus {get; set;}
    private String DDStatus {get; set;}
    private String ContractStatus {get; set;}
    public Id regId {get; private set;}
    public Id oppId {get; private set;}
    public Id contractId {get; private set;}
    public Boolean regShowHyperlink {get; private set;}
    public Boolean ddShowHyperlink {get; private set;}    
    public Boolean oppShowHyperlink {get; private set;}    
    public Boolean contractShowHyperlink {get; private set;}
    
    public String RegStatusColour {get; private set;}
    public String RegFontColour {get; private set;}
    public String RegBorderColour {get; private set;}
    
    public String DDStatusColour {get; private set;}
    public String DDFontColour {get; private set;}
    public String DDBorderColour {get; private set;}
    
    public String OppStatusColour {get; private set;}
    public String OppFontColour {get; private set;}
    public String OppBorderColour {get; private set;}
    
    public String ContractStatusColour {get; private set;}   
    public String ContractFontColour {get; private set;}
    public String ContractBorderColour {get; private set;}
    
    public Boolean RenderRegColumn {get; private set;}
    public Boolean RenderDDColumn {get; private set;}
    public Boolean RenderOppColumn {get; private set;}
    public Boolean RenderContractColumn {get; private set;}            
    
    private final MAP<String, String> cMap = new MAP<String, String>{'White' => '#ffffff', 
        'Green' => '#23a94b', 
        'Amber' => '#fbbc05',
        'Red' => '#c40818',
        'Grey' => '#999999',
        'LightGrey' => '#f2f2f2',
        'Black' => '#595959',
        'Purple' => '#DA70D6'};
            
            global AccountStatusBannerExtension(ApexPages.StandardController stdController) {
                accId = Apexpages.currentPage().getParameters().get('id');
                Account a = [SELECT Id, DD_Status__c, Account_Type__c, Account_Status__c, Reference_Registration__c, Registration_Status__c, 
                             product_contracts_active__c, CMPA_received__c, Awaiting_CMPA__c, Opportunity_Status__c,
                             (select id, StageName from Opportunities ORDER BY LastModifiedDate DESC LIMIT 50),
                             (select id, Status__c from eNett_Contract__r ORDER BY LastModifiedDate DESC LIMIT 50)
                             FROM Account WHERE Id = :accId LIMIT 1][0];
                regId =  a.Reference_Registration__c;
                oppId = null; 
                contractId = a.eNett_Contract__r.isEmpty() ? null : a.eNett_Contract__r[0].id;
                RegStatus = a.Registration_Status__c != null ? a.Registration_Status__c : '';
                DDStatus = a.DD_Status__c != null ? a.DD_Status__c : '';
                
                MAP<Id, Boolean> viewAccessMap = new MAP<Id, Boolean>();
                SET<Id> recIds = new Set<Id>();
                if (regId != null) recIds.add(regId);
                if (contractId != null) recIds.add(contractId);
                for (UserRecordAccess rAcc : [SELECT RecordId, HasReadAccess FROM UserRecordAccess WHERE UserId = :UserInfo.getUserId() AND RecordId IN :recIds]) {
                    viewAccessMap.put(rAcc.RecordId, rAcc.HasReadAccess);
                }
                
                Integer contractInflight_count = 0;
                Integer contractActive_count = 0;
                Integer contractInactive_count = 0;
                for (eNett_Contract__c cnt : a.eNett_Contract__r) {
                    if (cnt.Status__c == 'In Flight') contractInflight_count += 1;
                    if (cnt.Status__c == 'Active') contractActive_count += 1;
                    if (cnt.Status__c == 'Inactive') contractInactive_count += 1;
                }
                Integer contract_count = contractInflight_count + contractActive_count + contractInactive_count;
                
                
                
                if (viewAccessMap.containsKey(regId)) {
                    regShowHyperlink = viewAccessMap.get(regId);
                    ddShowHyperlink = viewAccessMap.get(regId);
                } else {
                    regShowHyperlink = false;
                    ddShowHyperlink = false;
                }
                
                oppShowHyperlink = false;
                contractShowHyperlink = false;
                
                if (RegStatus == 'Complete') {
                    RegStatusColour = cMap.get('Green');
                } else if (RegStatus == 'Rejected - Non-responsive' || RegStatus == 'Rejected - Spam/test application' || RegStatus == 'Rejected - Application N/A') {
                    RegStatusColour = cMap.get('Red');        
                } else {
                    RegStatusColour = cMap.get('Amber');
                }
                
                if (DDStatus == 'DD Approved') {
                    DDStatusColour = cMap.get('Green');
                } else if (DDStatus == 'DD Declined') {
                    DDStatusColour = cMap.get('Red');
                } else {
                    DDStatusColour = cMap.get('Amber');
                }
                
                //2018-06-14
                //Since we are introducing Opportunity Status field on Account, we can just load the colours of the banner based on that field.
                //However older accounts are not populated with this field, I added the first condition for backward comp
                Integer oppProspect_count = 0;
                Integer oppClosedLost_count = 0;
                Integer oppClosedRemoved_count = 0;
                Integer opp_count = a.Opportunities.isEmpty() ? 0 : a.Opportunities.size();  

                if (String.isBlank(a.Opportunity_Status__c)){
                    for (Opportunity opp : a.Opportunities) {
                        if (opp.StageName == '1. Prospect') oppProspect_count += 1;
                        if (opp.StageName == '7. Closed/Lost') oppClosedLost_count += 1;
                        if (opp.StageName == '8. Closed/Lost - Product Removed') oppClosedRemoved_count += 1;            
                    }
                    if (opp_count == 0 || oppClosedRemoved_count == opp_count)// If NA or Product Removed
                        OppStatusColour = cMap.get('LightGrey');    
                    else if (oppClosedLost_count == opp_count)   // If all Closed/Lost
                        OppStatusColour = cMap.get('Red');
                    else if (oppProspect_count > 0) 
                        OppStatusColour = cMap.get('Amber');
                    else 
                        OppStatusColour = cMap.get('Green');
                }
                else if (a.Opportunity_Status__c == 'Not Available' || a.Opportunity_Status__c == 'Product Removed' )
                    OppStatusColour = cMap.get('LightGrey');    
                else if (a.Opportunity_Status__c == 'All Closed/Lost')
                    OppStatusColour = cMap.get('Red');
                else if (a.Opportunity_Status__c == 'Qualified') 
                    OppStatusColour = cMap.get('Green');
                else
                    OppStatusColour = cMap.get('Amber');
                
                
                if (UpdateActiveProductCheckboxesOnAccount.getUpdatedProductContractsActiveCheckbox(accId)) {
                    if (a.Awaiting_CMPA__c) {
                        ContractStatusColour = cMap.get('Amber');
                    } else {
                        ContractStatusColour = cMap.get('Green');
                    }
                } else if (contractInflight_count > 0) {
                    ContractStatusColour = cMap.get('Amber');
                } else {
                    ContractStatusColour = cMap.get('LightGrey');
                }
                
                RenderRegColumn = false;
                RenderDDColumn = false;
                RenderOppColumn = true;
                RenderContractColumn = true;
                
                if (a.Account_Type__c == 'Affiliate' || a.Account_Type__c == 'Customer' || a.Account_Type__c == 'Service Provider') {
                    RenderRegColumn = true;
                }
                
                if (a.Account_Type__c == 'Affiliate' || a.Account_Type__c == 'Customer' || a.Account_Type__c == 'Service Provider') {
                    RenderDDColumn = true;
                }
                
                if (a.Account_Type__c == 'Service Provider' || a.Account_Type__c == 'Referrer') {
                    RenderOppColumn = false;
                }
                
                if (a.Account_Type__c == 'Additional ECN') {
                    RenderContractColumn = false;
                }          
                
                if (a.Account_Status__c == 'Deactivated') {
                    RenderRegColumn = false;
                    RenderDDColumn = false;
                    RenderOppColumn = false;
                    RenderContractColumn = false;
                }
                
                RegFontColour = GetTextColour(RegStatusColour);
                RegBorderColour = GetBorderColour(RegStatusColour);
                
                DDFontColour = GetTextColour(DDStatusColour);
                DDBorderColour = GetBorderColour(DDStatusColour);
                
                OppFontColour = GetTextColour(OppStatusColour);
                OppBorderColour = GetBorderColour(OppStatusColour);
                
                ContractFontColour = GetTextColour(ContractStatusColour);
                ContractBorderColour = GetBorderColour(ContractStatusColour);       
            }
    
    private String GetTextColour(String StatusColour) {
        if (StatusColour == cMap.get('LightGrey')) {
            return cMap.get('Black');
        } else {
            return cMap.get('White');
        }
    }
    
    private String GetBorderColour(String StatusColour) {
        if (StatusColour == cMap.get('White')) {
            return StatusColour; //return cMap.get('Grey');
        } else {
            return StatusColour;
        }
    }   
    
}