force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>eNett Internal</fullName>
            </value>
            <value>
                <fullName>eNett Internal Non Transacting</fullName>
            </value>
            <value>
                <fullName>eNett Internal Transacting</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Creation_Type__c.field-meta.xml
<CustomField>
    <fullName>Creation_Type__c</fullName>
    <label>Creation Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
                <default>true</default>
                <label>Internal</label>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Automatically populated. This field is only populated for accounts which are activated in client database.</inlineHelpText>
    <label>ECN</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/eNett_products__c.field-meta.xml
<CustomField>
    <fullName>eNett_products__c</fullName>
    <label>eNett Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>VirtualTerminal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Parent__c.field-meta.xml
<CustomField>
    <fullName>Legal_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>LegalAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>RBA_Address_Line_1__c</fullName>
    <label>Reg Bus Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>RBA_Address_Line_2__c</fullName>
    <label>Reg Bus Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_City__c.field-meta.xml
<CustomField>
    <fullName>RBA_City__c</fullName>
    <label>Reg Bus City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_Country__c.field-meta.xml
<CustomField>
    <fullName>RBA_Country__c</fullName>
    <label>Reg Bus Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_Postcode__c.field-meta.xml
<CustomField>
    <fullName>RBA_Postcode__c</fullName>
    <label>Reg Bus Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Affiliate.recordType-meta.xml
<RecordType>
    <fullName>Affiliate</fullName>
    <active>true</active>
    <description>A company that is associated to another company (is an affiliate of another company) - Affiliate and the parent have different ABN, ACN and legal entity name</description>
    <label>Affiliate</label>
</RecordType>

force-app/main/default/classes/AsyncUpdateChildAccountsTest.cls
/**
 * Test class to test Asynchronus queueable job to update child Accounts 
 * Queueable Job class: AsyncUpdateChildAccounts.apxc
 * Author: Kishore Potla
 * Date: 21/10/2019
 * 
 * [03/Jan/2020] PDS-6874: Only Additonal ECNs should have same RBA as their parent.
 * 
 * */

@isTest(SeeAllData=TRUE)
public class AsyncUpdateChildAccountsTest {
	
    public static void setup(){
        Account parentAccount = new Account(Name = 'Test Parent Account',
                                  ECN__c = '100001',
                                  RBA_Address_Line_1__c = '111 XXXX Street',
                                  RBA_Address_Line_2__c = '',
                                  RBA_City__c = 'South Brisbane',
                                  RBA_Country__c = 'Australia',
                                  RBA_Postcode__c = '2000',
                                  eNett_products__c = 'eNett EFT',
                                  OwnerID = Userinfo.getUserId()
                                 );
        
        insert parentAccount;
    }
    
    /* Test cases to test queueable apex job for the below scenario. 
     * When R.B.Address of an Account is udpated, in the AfterUpdate event of AccountTrigger, 
     *    a Queueable apex job will be submitted to update the same R.B.Address to all its Additional ECN child accounts
     * 
     * [03/Jan/2020] PDS-6874: Only Additonal ECNs should have same RBA as their parent. Affiliates, Customers and any other accounts should not.
     * 
     **/
    
    @isTest
    public static void testAsyncUpdateChildAccounts_Affiliates(){
    	
        AsyncUpdateChildAccountsTest.setup();
        Account parentAccount = [Select id, OwnerId from Account Where ECN__c = '100001'];
        Account childAffiliate = new Account(Name = 'Test Child Affiliate Account',
                                  ECN__c = '100002',
                                  parentid = parentAccount.id,
                                  Legal_Parent__c = parentAccount.id,
                                  RBA_Address_Line_1__c = '111 XXXX Street',
                                  RBA_Address_Line_2__c = '',
                                  RBA_City__c = 'South Brisbane',
                                  RBA_Country__c = 'Australia',
                                  RBA_Postcode__c = '2000',
                           		  Account_Type__c = 'Affiliate',
                                  eNett_products__c = 'eNett EFT',
                                  Creation_type__c = 'Internal'
                                 );
        
        insert childAffiliate;
        
        test.startTest();
        //Updating RBA on parent account will trigger queueable apex job to update RBA on all Additional ECN childs in hiearchy.
        parentAccount.RBA_Address_Line_1__c = '111 XXXX Street_updated';
        update parentAccount;
        test.stopTest();
        
        childAffiliate = [Select RBA_Address_Line_1__c from Account Where ECN__c = '100002'];
        System.assertEquals('111 XXXX Street',childAffiliate.RBA_Address_Line_1__c);
    }
    
    @isTest
    public static void testAsyncUpdateChildAccounts_AdditionalECNs(){
    	
        AsyncUpdateChildAccountsTest.setup();
        Account parentAccount = [Select id, OwnerId from Account Where ECN__c = '100001'];
        Account childAddiECN = new Account(Name = 'Test Child Additional ECN Account',
                                  ECN__c = '100003',
                                  parentid = parentAccount.id,
                                  Legal_Parent__c = parentAccount.id,
                                  RBA_Address_Line_1__c = '111 XXXX Street',
                                  RBA_Address_Line_2__c = '',
                                  RBA_City__c = 'South Brisbane',
                                  RBA_Country__c = 'Australia',
                                  RBA_Postcode__c = '2000',
                           		  Account_Type__c = 'Additional ECN',
                                  eNett_products__c = 'eNett EFT',
                                  Creation_type__c = 'Internal'
                                 );
        insert childAddiECN;
        
        test.startTest();
        //Updating RBA on parent account will trigger queueable apex job to update RBA on all Additional ECN childs in hiearchy.
        parentAccount.RBA_Address_Line_1__c = '111 YYYY Street_updated';
        update parentAccount;
        test.stopTest();
        
        childAddiECN = [Select RBA_Address_Line_1__c from Account Where ECN__c = '100003'];
        System.assertEquals('111 YYYY Street_updated',childAddiECN.RBA_Address_Line_1__c);
    }
}