force-app/main/default/objects/Account/fields/Account_Group__c.field-meta.xml
<CustomField>
    <fullName>Account_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Group</label>
    <referenceTo>Account_Group__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>DD Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Last_Transaction__c</fullName>
    <label>Latest Settled Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Group__c/Account_Group__c.object-meta.xml
<CustomObject>
    <label>Account Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TestTriggerUpdateAccountGroup.cls
@isTest
private class TestTriggerUpdateAccountGroup {
    static testMethod void runTest() {
        
      Account_Group__c accGrp=new Account_Group__C();
      accGrp.Name='TestGroup';
      insert accGrp; 
      
      Account acc=new Account();
      acc.Name='TestAccount';
      acc.Account_Group__C=accGrp.Id;
      insert acc;
      
      acc.Due_Diligence_Completed__c=date.newInstance(2014, 08, 20);
      acc.Last_Transaction__c=date.newInstance(2014, 08, 22);
      update acc;  
    }
}