force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>Automatically populated. Status is only updated to &#39;Client&#39; once the account is activated in the client database.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Active</fullName>
                <default>true</default>
                <label>Not Active</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Affiliate.recordType-meta.xml
<RecordType>
    <fullName>Affiliate</fullName>
    <active>true</active>
    <description>A company that is associated to another company (is an affiliate of another company) - Affiliate and the parent have different ABN, ACN and legal entity name</description>
    <label>Affiliate</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Financial_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Financial_Email_Address__c</fullName>
    <label>Financial Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <inlineHelpText>This field is automatically populated by the Client system integration.</inlineHelpText>
    <label>Job Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Master administrator</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Delivery Implementation</fullName>
            </value>
            <value>
                <fullName>Operational / Technical</fullName>
            </value>
            <value>
                <fullName>Operational / Technical SMEs</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Secondary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email_Address__c</fullName>
    <label>Secondary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard T&amp;Cs</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>DKK</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>HUF</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>MXN</fullName>
            </value>
            <value>
                <fullName>NZD</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>ZAR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>From Lead</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>From Lead</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>From Lead</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>From Lead</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Miss</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Mr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreatePrimaryContactsForAffiliates.cls
public class CreatePrimaryContactsForAffiliates {

    @InvocableMethod
    public static void CreatePrimaryContactsForAffiliates(LIST<Id> regIds) {
    
        MAP<Id, Registration__c> accIdRegMap = new MAP<Id, Registration__c>();
        LIST<Contact> newContacts = new LIST<Contact>();

        for (Registration__c reg : [SELECT Id, Account__c, first_name__c, last_name__c, email__c, currency__c, job_role__c, phone__c, Salutation__c
                                    FROM Registration__c WHERE Id IN :regIds AND Account__c != null AND Agreement_Type__c = 'Affiliate']) {         
            accIdRegMap.put(reg.account__c, reg);       
        }
        
        // Filter out active accounts that already have primary contacts
        for (Account acc : [SELECT Id, Account_Status__c, (SELECT Id FROM Contacts WHERE Job_Role__c INCLUDES ('Primary')) FROM Account WHERE Id IN :accIdRegMap.keySet()]) {
            if (acc.Account_Status__c == 'Active' && acc.Contacts.size() > 0) 
                accIdRegMap.remove(acc.id);
        }
        
        // 
        for (Registration__c reg : accIdRegMap.values()) {           
            Contact cont = new Contact(Salutation = reg.Salutation__c,
                                       LastName = reg.last_name__c,
                                       AccountId = reg.account__c,
                                       CurrencyIsoCode = reg.currency__c,
                                       Email = reg.email__c,
                                       Financial_Email_Address__c = reg.email__c,
                                       FirstName = reg.first_name__c,
                                       Job_Role__c = 'Primary;Secondary;Financial',
                                       Phone = reg.phone__c,
                                       Primary_Email_Address__c = reg.email__c,
                                       Secondary_Email_Address__c = reg.email__c,
                                       Title = 'hello2' //reg.job_role__c
                                      );
            newContacts.add(cont);
        }

        insert newContacts;
    }

}