force-app/main/default/objects/Account/fields/Account_ECN__c.field-meta.xml
<CustomField>
    <fullName>Account_ECN__c</fullName>
    <formula>Name  &amp; &quot;( &quot;  &amp;  ECN__c  &amp; &quot; )&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account (ECN)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Automatically populated. This field is only populated for accounts which are activated in client database.</inlineHelpText>
    <label>ECN</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>External Registration</fullName>
            </value>
            <value>
                <fullName>Internal Registration - Re Reg</fullName>
            </value>
            <value>
                <fullName>Internal Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/eNett_Contract__c.object-meta.xml
<CustomObject>
    <label>eNett Contract</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>eNett Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eNett Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/eNett_Contract__c/fields/Account_ECN__c.field-meta.xml
<CustomField>
    <fullName>Account_ECN__c</fullName>
    <formula>Account_Name__r.ECN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account ECN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eNett Contract</relationshipLabel>
    <relationshipName>eNett_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard T&amp;Cs</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Contract not required</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Internal Transacting</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Cross_Currency_Details__c.field-meta.xml
<CustomField>
    <fullName>Cross_Currency_Details__c</fullName>
    <inlineHelpText>Please input the proposed cross currency fee here if you ticked the field above</inlineHelpText>
    <label>Cross Currency Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Cross_Currency_Fee_0_81__c.field-meta.xml
<CustomField>
    <fullName>Cross_Currency_Fee_0_81__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please tick this field if the cross currency fee you are proposing is less than 0.81%</inlineHelpText>
    <label>Cross Currency Fee &lt; 0.81%</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Deletion_of_Marketing_Clause__c.field-meta.xml
<CustomField>
    <fullName>Deletion_of_Marketing_Clause__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Tick for Yes</inlineHelpText>
    <label>Deletion of Marketing Clause</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Exclusivity__c.field-meta.xml
<CustomField>
    <fullName>Exclusivity__c</fullName>
    <inlineHelpText>Please input the percentage of exclusivity here if you have chosen “yes – percentage” above</inlineHelpText>
    <label>Exclusivity %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Exclusivity_Clause__c.field-meta.xml
<CustomField>
    <fullName>Exclusivity_Clause__c</fullName>
    <label>Exclusivity Clause</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes - All Cards</fullName>
            </value>
            <value>
                <fullName>Yes - Virtual Cards</fullName>
            </value>
            <value>
                <fullName>Yes - Percentage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <inlineHelpText>Please input the fixed percentage share here (usually around 0.5)</inlineHelpText>
    <label>Fixed % Amount</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Incentive_Type__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Type__c</fullName>
    <label>Incentive Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>% of Interchange</fullName>
            </value>
            <value>
                <fullName>Fixed % (BPS)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Rebate_Type__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Type__c</fullName>
    <label>Rebate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flat</fullName>
            </value>
            <value>
                <fullName>Tiered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Review_Period_Months_if_applicable__c.field-meta.xml
<CustomField>
    <fullName>Review_Period_Months_if_applicable__c</fullName>
    <inlineHelpText>Entering a value greater than &quot;0&quot; in this field will set the T&amp;C Modification checkbox and redirect the Contract for Regional Sales and Legal Approval.</inlineHelpText>
    <label>Review Period (Months - if applicable)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Short_Term_Incentive_Details__c.field-meta.xml
<CustomField>
    <fullName>Short_Term_Incentive_Details__c</fullName>
    <inlineHelpText>Please input the proposed short term incentive here if you have ticked the field above</inlineHelpText>
    <label>Short Term Incentive Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Subscription_Fee__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Fee__c</fullName>
    <inlineHelpText>Enter “zero” if you are waiving the subscription fee, otherwise enter the value to be charged.</inlineHelpText>
    <label>Subscription Fee</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/T_C_Modification_Details__c.field-meta.xml
<CustomField>
    <fullName>T_C_Modification_Details__c</fullName>
    <inlineHelpText>Please use this for other clauses that are not highlighted above, such as Virtual Terminal exemption.</inlineHelpText>
    <label>Other T&amp;C Modifications</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Technology_Fund_Details__c.field-meta.xml
<CustomField>
    <fullName>Technology_Fund_Details__c</fullName>
    <inlineHelpText>Please input the proposed technology fund details here if you have ticked the field above</inlineHelpText>
    <label>Technology Fund Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Tier_1_Fixed_Range_From__c.field-meta.xml
<CustomField>
    <fullName>Tier_1_Fixed_Range_From__c</fullName>
    <inlineHelpText>Please input the volume details here</inlineHelpText>
    <label>Tier 1 Fixed Range From</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Tier_1_Fixed_Range_To__c.field-meta.xml
<CustomField>
    <fullName>Tier_1_Fixed_Range_To__c</fullName>
    <inlineHelpText>Please input the volume details here</inlineHelpText>
    <label>Tier 1 Fixed Range To</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Tier_1_Int_Range_From__c.field-meta.xml
<CustomField>
    <fullName>Tier_1_Int_Range_From__c</fullName>
    <inlineHelpText>Please input the volume details here</inlineHelpText>
    <label>Tier 1 Interchange Range From</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Tier_1_Int_Range_To__c.field-meta.xml
<CustomField>
    <fullName>Tier_1_Int_Range_To__c</fullName>
    <inlineHelpText>Please input the volume details here</inlineHelpText>
    <label>Tier 1 Interchange Range To</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Tier_1_Interchange_Share__c.field-meta.xml
<CustomField>
    <fullName>Tier_1_Interchange_Share__c</fullName>
    <label>Tier 1 % Interchange Share</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Tier_2_Fixed_Share__c.field-meta.xml
<CustomField>
    <fullName>Tier_2_Fixed_Share__c</fullName>
    <inlineHelpText>Please provide this data in the following format – e.g. 20% should be added in as 0.2.</inlineHelpText>
    <label>Tier 2 Fixed % Share (BPS)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Tier_2_Int_Range_From__c.field-meta.xml
<CustomField>
    <fullName>Tier_2_Int_Range_From__c</fullName>
    <inlineHelpText>Please input the volume details here</inlineHelpText>
    <label>Tier 2 Interchange Range From</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Tier_2_Int_Range_To__c.field-meta.xml
<CustomField>
    <fullName>Tier_2_Int_Range_To__c</fullName>
    <inlineHelpText>Please input the volume details here</inlineHelpText>
    <label>Tier 2 Interchange Range To</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Tier_2_Interchange_Share__c.field-meta.xml
<CustomField>
    <fullName>Tier_2_Interchange_Share__c</fullName>
    <label>Tier 2 % Interchange Share</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Tiered_Rebate_Calculation_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Tiered_Rebate_Calculation_Frequency__c</fullName>
    <label>Tiered Rebate Calculation Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Trial_Period__c.field-meta.xml
<CustomField>
    <fullName>Trial_Period__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trial Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Trial_Period_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Trial_Period_Term_Months__c</fullName>
    <label>Trial Period Term (Months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Volume_Commitments__c.field-meta.xml
<CustomField>
    <fullName>Volume_Commitments__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Tick for Yes</inlineHelpText>
    <label>Volume Commitments</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Volume_Commitments_Details__c.field-meta.xml
<CustomField>
    <fullName>Volume_Commitments_Details__c</fullName>
    <inlineHelpText>Please input the proposed volume commitment details here if you have ticked the field above – please note that these may be linked to a tech fund or a short term incentive</inlineHelpText>
    <label>Volume Commitments Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Waive_Subscription_Fee_Details__c.field-meta.xml
<CustomField>
    <fullName>Waive_Subscription_Fee_Details__c</fullName>
    <inlineHelpText>If you are waiving the fee or reducing the fee, enter term of discount here.</inlineHelpText>
    <label>Waive Subscription Fee Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/WUBS__c.field-meta.xml
<CustomField>
    <fullName>WUBS__c</fullName>
    <inlineHelpText>Tick for Yes</inlineHelpText>
    <label>WUBS</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>WUBS - no</fullName>
            </value>
            <value>
                <fullName>WUBS - yes (eNett Paying)</fullName>
            </value>
            <value>
                <fullName>WUBS - yes (client Paying)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TaskUtil.cls
public class TaskUtil {  

    //public static Task createContractTask(String Owner, String RTypeId, String Account, String ECN, String Subject, String ContractId, Integer Days) {
    //    Return new Task(    OwnerId = Owner,
    //                        RecordTypeId = RTypeId,
    //                        Related_Account__c = Account,
    //                        ECN__c = ECN,                            
    //                        Priority = 'Normal', 
    //                        Status = 'In Progress', 
    //                        Subject = Subject, 
    //                        Type = 'Task',
    //                        IsReminderSet = true, 
    //                        ReminderDateTime = System.now()+Days,
    //                        WhatId = ContractId,
    //                        ActivityDate = System.today()+Days ); 
    //}

    //public static Task createOpportunityTask(String Owner, String RTypeId, String Account, String DeliveryType, String ECN, String Subject, String OpportunityId, Datetime DueDate) {  
    //    Return new Task(    OwnerId = Owner,
    //                        RecordTypeId = RTypeId,
    //                        Related_Account__c = Account,
    //                        ECN__c = ECN,                            
    //                        Delivery_Type__c = DeliveryType,
    //                        Priority = 'Normal', 
    //                        Status = 'In Progress', 
    //                        Subject = Subject, 
    //                        Type = 'Task',
    //                        WhatId = OpportunityId,
    //                        IsReminderSet = true,
    //                        ReminderDateTime = DueDate,
    //                        ActivityDate = DueDate.date() );
    //}

    //public static Task createQualifyOpportunityTask(String Owner, String RTypeId, String Account, String DeliveryType, String RegoType, String ContractType, String ECN, String Subject, String OpportunityId, Datetime DueDate) {  
    //    Return new Task(    OwnerId = Owner,
    //                        RecordTypeId = RTypeId,
    //                        Related_Account__c = Account,
    //                        ECN__c = ECN,                            
    //                        Delivery_Type__c = DeliveryType,
    //                        Registration_Type__c = RegoType,
    //                        Contract_Type__c = ContractType,
    //                        Priority = 'Normal', 
    //                        Status = 'In PRogress', 
    //                        Subject = Subject, 
    //                        Type = 'Task',
    //                        WhatId = OpportunityId,
    //                        IsReminderSet = true,
    //                        ReminderDateTime = DueDate,
    //                        ActivityDate = DueDate.date() );
    //}

    //public static Task createDealArrangementTask(String Owner, String RTypeId, eNEtt_Contract__c c, String Subject, String ContractId, Integer Days) {  
    //    Return new Task(    OwnerId = Owner,
    //                        // Subject & Task Information
    //                        Subject = Subject, 
    //                        Type = 'Task',
    //                        WhatId = ContractId,
    //                        Related_Account__c = c.Account_Name__r.Name,
    //                        ActivityDate = System.today()+Days,
    //                        Status = 'In Progress', 
    //                        Priority = 'Normal', 
    //                        ECN__c = c.Account_ECN__c,
    //                        // Required Information
    //                        Rebate_Type__c = c.Rebate_Type__c,
    //                        Incentive_Type__c = c.Incentive_Type__c,
    //                        Interchange_Amount__c = c.Interchange_Amount__c,
    //                        Fixed_Amount__c = c.Fixed_Amount__c,
    //                        Agreement_Term_Years__c = c.Agreement_Term_Years__c,
    //                        Review_Period_Months_if_applicable__c = c.Review_Period_Months_if_applicable__c, 
    //                        // Trial Information
    //                        Trial_Period__c = c.Trial_Period__c,
    //                        Trial_Period_Term_Months__c = c.Trial_Period_Term_Months__c,
    //                        // Exclusivity Information
    //                        Exclusivity_Clause__c = c.Exclusivity_Clause__c, 
    //                        Exclusivity__c = c.Exclusivity__c,
    //                        // Additional Information
    //                        Non_local_Settlement_Currency__c = c.Non_local_Settlement_Currency__c,
    //                        Deletion_of_Marketing_Clause__c = c.Deletion_of_Marketing_Clause__c,
    //                        Non_standard_Funding_Fund_on_Auth__c = c.Non_standard_Funding_Fund_on_Auth__c,
    //                        Cross_Currency_Fee_0_81__c = c.Cross_Currency_Fee_0_81__c,
    //                        Cross_Currency_Details__c = c.Cross_Currency_Details__c,
    //                        Waive_Subscription_Fee_Details__c = c.Waive_Subscription_Fee_Details__c,
    //                        Subscription_Fee__c = c.Subscription_Fee__c,
    //                        Chargeback_Processing_Fee__c = c.Chargeback_Processing_Fee__c,
    //                        Short_Term_Incentive__c = c.Short_Term_Incentive__c,
    //                        Short_Term_Incentive_Details__c = c.Short_Term_Incentive_Details__c,
    //                        Technology_Fund_API_Integration__c = c.Technology_Fund_API_Integration__c,
    //                        Technology_Fund_Details__c = c.Technology_Fund_Details__c,
    //                        Volume_Commitments__c = c.Volume_Commitments__c,
    //                        Volume_Commitments_Details__c = c.Volume_Commitments_Details__c,
    //                        WUBS__c = c.WUBS__c,
    //                        T_C_Modification_Details__c = c.T_C_Modification_Details__c,
    //                        // Tiered Information
    //                        Tiered_Rebate_Calculation_Frequency__c = c.Tiered_Rebate_Calculation_Frequency__c,
    //                        Tier_1_Interchange_Share__c = c.Tier_1_Interchange_Share__c,
    //                        Tier_1_Fixed_Share__c = c.Tier_1_Fixed_Share__c,
    //                        Tier_1_Int_Range_From__c = c.Tier_1_Int_Range_From__c,
    //                        Tier_1_Int_Range_To__c = c.Tier_1_Int_Range_To__c,
    //                        Tier_1_Fixed_Range_From__c = c.Tier_1_Fixed_Range_From__c,
    //                        Tier_1_Fixed_Range_To__c = c.Tier_1_Fixed_Range_To__c,
    //                        Tier_2_Interchange_Share__c = c.Tier_2_Interchange_Share__c,
    //                        Tier_2_Fixed_Share__c = c.Tier_2_Fixed_Share__c,
    //                        Tier_2_Int_Range_From__c = c.Tier_2_Int_Range_From__c,
    //                        Tier_2_Int_Range_To__c = c.Tier_2_Int_Range_To__c,
    //                        Tier_2_Fixed_Range_From__c = c.Tier_2_Fixed_Range_From__c,
    //                        Tier_2_Fixed_Range_To__c = c.Tier_2_Fixed_Range_To__c,
    //                        Tier_3_Interchange_Share__c = c.Tier_3_Interchange_Share__c,
    //                        Tier_3_Fixed_Share__c = c.Tier_3_Fixed_Share__c,
    //                        Tier_3_Int_Range_From__c = c.Tier_3_Int_Range_From__c,
    //                        Tier_3_Int_Range_To__c = c.Tier_3_Int_Range_To__c,
    //                        Tier_3_Fixed_Range_From__c = c.Tier_3_Fixed_Range_From__c,
    //                        Tier_3_Fixed_Range_To__c = c.Tier_3_Fixed_Range_To__c,
    //                        SLA_Required__c = c.SLA_Required__c, // SF-1430
    //                        // Sysytem & Reminder Information
    //                        IsReminderSet = true, 
    //                        ReminderDateTime = System.now()+Days,
    //                        RecordTypeId = RTypeId );
    //}

    //public static void updateContractFields (Task t, eNEtt_Contract__c c, Map<String,RecordType> rt) {
    //    if (t.RecordTypeId == rt.get('Contract_Deal_Arrangement').Id) {
    //        c.Rebate_Type__c = t.Rebate_Type__c;
    //        c.Incentive_Type__c = t.Incentive_Type__c;
    //        c.Interchange_Amount__c = t.Interchange_Amount__c;
    //        c.Fixed_Amount__c = t.Fixed_Amount__c;
    //        c.Agreement_Term_Years__c = t.Agreement_Term_Years__c;
    //        c.Review_Period_Months_if_applicable__c = t.Review_Period_Months_if_applicable__c;
    //        c.Trial_Period__c = t.Trial_Period__c;
    //        c.Trial_Period_Term_Months__c = t.Trial_Period_Term_Months__c;
    //        c.Exclusivity_Clause__c = t.Exclusivity_Clause__c; 
    //        c.Exclusivity__c = t.Exclusivity__c; 
    //        c.Non_local_Settlement_Currency__c = t.Non_local_Settlement_Currency__c;
    //        c.Deletion_of_Marketing_Clause__c = t.Deletion_of_Marketing_Clause__c;
    //        c.Non_standard_Funding_Fund_on_Auth__c = t.Non_standard_Funding_Fund_on_Auth__c;
    //        c.Cross_Currency_Fee_0_81__c = t.Cross_Currency_Fee_0_81__c;
    //        c.Cross_Currency_Details__c = t.Cross_Currency_Details__c;
    //        c.Waive_Subscription_Fee_Details__c = t.Waive_Subscription_Fee_Details__c;
    //        c.Subscription_Fee__c = t.Subscription_Fee__c;
    //        c.Chargeback_Processing_Fee__c = t.Chargeback_Processing_Fee__c;
    //        c.Short_Term_Incentive__c = t.Short_Term_Incentive__c;
    //        c.Short_Term_Incentive_Details__c = t.Short_Term_Incentive_Details__c;
    //        c.Technology_Fund_API_Integration__c = t.Technology_Fund_API_Integration__c;
    //        c.Technology_Fund_Details__c = t.Technology_Fund_Details__c;
    //        c.Volume_Commitments__c = t.Volume_Commitments__c;
    //        c.Volume_Commitments_Details__c = t.Volume_Commitments_Details__c;
    //        c.WUBS__c = t.WUBS__c;
    //        c.T_C_Modification_Details__c = t.T_C_Modification_Details__c;
    //        c.Tiered_Rebate_Calculation_Frequency__c = t.Tiered_Rebate_Calculation_Frequency__c; 
    //        c.Tier_1_Interchange_Share__c = t.Tier_1_Interchange_Share__c;
    //        c.Tier_1_Fixed_Share__c = t.Tier_1_Fixed_Share__c;
    //        c.Tier_1_Int_Range_From__c = t.Tier_1_Int_Range_From__c;
    //        c.Tier_1_Int_Range_To__c = t.Tier_1_Int_Range_To__c;
    //        c.Tier_1_Fixed_Range_From__c = t.Tier_1_Fixed_Range_From__c;
    //        c.Tier_1_Fixed_Range_To__c = t.Tier_1_Fixed_Range_To__c;
    //        c.Tier_2_Interchange_Share__c = t.Tier_2_Interchange_Share__c;
    //        c.Tier_2_Fixed_Share__c = t.Tier_2_Fixed_Share__c;
    //        c.Tier_2_Int_Range_From__c = t.Tier_2_Int_Range_From__c;
    //        c.Tier_2_Int_Range_To__c = t.Tier_2_Int_Range_To__c;
    //        c.Tier_2_Fixed_Range_From__c = t.Tier_2_Fixed_Range_From__c;
    //        c.Tier_2_Fixed_Range_To__c = t.Tier_2_Fixed_Range_To__c;
    //        c.Tier_3_Interchange_Share__c = t.Tier_3_Interchange_Share__c;
    //        c.Tier_3_Fixed_Share__c = t.Tier_3_Fixed_Share__c;
    //        c.Tier_3_Int_Range_From__c = t.Tier_3_Int_Range_From__c;
    //        c.Tier_3_Int_Range_To__c = t.Tier_3_Int_Range_To__c; 
    //        c.Tier_3_Fixed_Range_From__c = t.Tier_3_Fixed_Range_From__c;
    //        c.Tier_3_Fixed_Range_To__c = t.Tier_3_Fixed_Range_To__c; 
    //        c.SLA_Required__c = t.SLA_Required__c; // SF-1430
    //        }
    //}

}