force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>eNett Internal</fullName>
            </value>
            <value>
                <fullName>eNett Internal Non Transacting</fullName>
            </value>
            <value>
                <fullName>eNett Internal Transacting</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/eNett_products__c.field-meta.xml
<CustomField>
    <fullName>eNett_products__c</fullName>
    <label>eNett Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>VirtualTerminal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Affiliate.recordType-meta.xml
<RecordType>
    <fullName>Affiliate</fullName>
    <active>true</active>
    <description>A company that is associated to another company (is an affiliate of another company) - Affiliate and the parent have different ABN, ACN and legal entity name</description>
    <label>Affiliate</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>A customer using VAN or EFT- client can be travel or corporate</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Process_Task__c/Process_Task__c.object-meta.xml
<CustomObject>
    <label>Process Task</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Process Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Tasks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Assigned_Date__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Date__c</fullName>
    <label>Assigned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <label>Related Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Related_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Related_Account_Type__c</fullName>
    <label>Related Account Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/recordTypes/VANs_Account_Approval_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>VANs_Account_Approval_Record_Type</fullName>
    <active>true</active>
    <description>This record type is for ‘Approve Account’ process tasks that decide where a registration should be assigned to. Only applicable for new accounts with &#39;VANs&#39; product.</description>
    <label>VANs Account Approval Record Type</label>
</RecordType>

force-app/main/default/classes/CreateProcessTasksBatch.cls
global class CreateProcessTasksBatch implements Database.Batchable<sObject> {
    
    //Query to gather accounts that meet the criteria
    global integer recordsProcessed = 0;
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('SELECT Id, Account_Type__c, Name, eNett_Products__c, CreatedDate, (SELECT Subject__c FROM Process_Tasks__r ORDER BY Subject__c) FROM Account WHERE eNett_Products__c INCLUDES (\'VANs\')'+ 
                                        'AND (Account_Type__c = \'Customer\' OR Account_Type__c = \'Affiliate\') AND CreatedDate >= 2018-01-01T00:00:00Z AND CreatedDate <= 2018-10-05T00:00:00Z');
    }
    
    //Loop through each account's process tasks and check that none of them is an 'Approve Account' task
    global void execute (Database.BatchableContext bc, List<Account> scope){
        Group apQueue = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'Account_Approval_Queue'];
        RecordType recId = [SELECT Id FROM RecordType WHERE DeveloperName = 'VANs_Account_Approval_Record_Type'];
        Set<Account> accsNeedPT = new Set<Account>();
        Integer taskExist = 0;
        if (!scope.isEmpty()){
            for (Account acc : scope){
                for (Process_Task__c pt : acc.Process_Tasks__r){
                    if (pt.Subject__c == 'Approve Account'){
                        taskExist ++;
                    }
                }
                if (taskExist == 0){
                    accsNeedPT.add(acc);
                }
                taskExist = 0;
            }
        }
        
        //Create process tasks
        List<Process_Task__c> ptList = new List<Process_Task__c>();
        for (Account acc : accsNeedPT){
            Process_Task__c pt = new Process_Task__c(Subject__c = 'Approve Account',
                                                     Related_Account_Type__c = acc.Account_Type__c,
                                                     RecordTypeId = recId.Id,
                                                     Account__c = acc.Id,
                                                     OwnerId = apQueue.Id,
                                                     Assigned_Date__c = Date.today(),
                                                     Due_Date__c = CalculateBusinessDays.AddBusinessDays(Date.today(), 2),
                                                     Related_Account__c = acc.Name,
                                                     Status__c = 'Backlog');
            ptList.add(pt);
        }
        
        //DML Operation starts
        if (ptList.size() > 0){
            SavePoint sp = Database.setSavepoint();
            try{
                Database.DMLOptions dmo = new Database.DMLOptions();
                dmo.OptAllOrNone = false;
                
                List<Database.SaveResult> saveResults = Database.insert(ptList, dmo);
                for (Database.SaveResult sr : saveResults){
                    if (!sr.isSuccess()){
                        for (Database.Error err : sr.getErrors()){
                            System.debug('####ERROR WHILE PROCESSING ACCOUNT: ' + err.getMessage());
                            System.debug('####ERROR STATUS CODE: ' + err.getStatusCode());
                            System.debug('####ERROR FIELDS: ' + err.getFields());
                        }
                    } else {
                        recordsProcessed++;
                    }
                }
            } catch (Exception e){
                Database.rollback(sp);
                System.debug('####ERROR ENCOUNTERED: ' + e.getMessage());
                throw e; 
            }
        }        
    }
    
    //send out an email once the process is completed
    global void finish (Database.BatchableContext bc){
		System.debug(recordsProcessed + 'records have been processed.');
    }
}