force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>Automatically populated. Status is only updated to &#39;Client&#39; once the account is activated in the client database.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Active</fullName>
                <default>true</default>
                <label>Not Active</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Financial_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Financial_Contact_Email__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Financial job role</description>
    <label>Financial Contact Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Financial_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Financial_Contact_First_Name__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Financial job role</description>
    <label>Financial Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Financial_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Financial_Contact_Last_Name__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Financial job role</description>
    <label>Financial Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Email_Address__c</fullName>
    <label>Primary Contact Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_First_Name__c</fullName>
    <label>Primary Contact First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Last_Name__c</fullName>
    <label>Primary Contact Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Contact_Email__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Secondary job role</description>
    <label>Secondary Contact Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Contact_First_Name__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Secondary job role</description>
    <label>Secondary Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Contact_Last_Name__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Secondary job role</description>
    <label>Secondary Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Financial_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Financial_Email_Address__c</fullName>
    <label>Financial Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <inlineHelpText>This field is automatically populated by the Client system integration.</inlineHelpText>
    <label>Job Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Master administrator</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Delivery Implementation</fullName>
            </value>
            <value>
                <fullName>Operational / Technical</fullName>
            </value>
            <value>
                <fullName>Operational / Technical SMEs</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Secondary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email_Address__c</fullName>
    <label>Secondary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/AccountContactInfoProcessor.cls
/**
* This batchable process loop through each account that has at least one contact and make sure the secondary/financial contact info is up to date.
@author : Ronnie Yang
@ticket : SF-5132
**/

global class AccountContactInfoProcessor implements Database.Batchable<sObject>, Database.Stateful {
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    
    // get all active accounts with contacts
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, (SELECT Id,FirstName, LastName, Job_Role__c, Primary_Email_Address__c, Secondary_Email_Address__c, Financial_Email_Address__c FROM Contacts) FROM Account WHERE Account_Status__c = \'Active\'');
    }
    
    //looping through all these active accounts and update the info on account
    global void execute(Database.BatchableContext bc, List<Account> accs){
        String p_firstName;
        String p_lastName;
        String p_email;
        String s_firstName;
        String s_lastName;
        String s_email;
        String f_firstName;
        String f_lastName;
        String f_email;
        for (Account a: accs){
            //as there can only be one primary, secondary or financial contact, we can loop through every contact and not worry about string being overwritten.
            for(Contact c: a.Contacts){
                if(c.Job_Role__c != null){
                    if (c.Job_Role__c.contains('Primary')){
                        p_firstName = !String.isEmpty(c.FirstName) ? c.FirstName : '';
                        p_lastName = c.LastName;
                        p_email = !String.isEmpty(c.Primary_Email_Address__c) ? c.Primary_Email_Address__c : '' ;
                    }
                    if (c.Job_Role__c.contains('Secondary')){
                        s_firstName = !String.isEmpty(c.FirstName) ? c.FirstName : '';
                        s_lastName = c.LastName;
                        s_email = !String.isEmpty(c.Secondary_Email_Address__c) ? c.Secondary_Email_Address__c : '';
                    }
                    if (c.Job_Role__c.contains('Financial')){
                        f_firstName = !String.isEmpty(c.FirstName) ? c.FirstName : '';
                        f_lastName = c.LastName;
                        f_email = !String.isEmpty(c.Financial_Email_Address__c) ? c.Financial_Email_Address__c : '';
                    }
                }
            }
            //update the contact values on account if it's applicable
            if(!String.isEmpty(p_lastName)){
                a.Primary_Contact_First_Name__c = p_firstName;
                a.Primary_Contact_Last_Name__c = p_lastName;
                a.Primary_Contact_Email_Address__c = p_email;
            }
            if(!String.isEmpty(s_lastName)){
                a.Secondary_Contact_First_Name__c = s_firstName;
                a.Secondary_Contact_Last_Name__c = s_lastName;
                a.Secondary_Contact_Email__c = s_email;
            }
            if(!String.isEmpty(f_lastName)){
                a.Financial_Contact_First_Name__c = f_firstName;
                a.Financial_Contact_Last_Name__c = f_lastName;
                a.Financial_Contact_Email__c = f_email;
            }
            System.debug(a);
        }
        update accs;
    }    
    
    global void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed+ ' Processed');
    }    
}