force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <inlineHelpText>Automatically populated. Status is only updated to &#39;Client&#39; once the account is activated in the client database.</inlineHelpText>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Active</fullName>
                <default>true</default>
                <label>Not Active</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Automatic_DD_Checklist_Created__c.field-meta.xml
<CustomField>
    <fullName>Automatic_DD_Checklist_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automatic DD Checklist Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DD_Status__c.field-meta.xml
<CustomField>
    <fullName>DD_Status__c</fullName>
    <inlineHelpText>Automatically updated based on the progress of DD.</inlineHelpText>
    <label>DD Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting Client</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Approval In Progress</fullName>
            </value>
            <value>
                <fullName>DD Approved</fullName>
            </value>
            <value>
                <fullName>DD Declined</fullName>
            </value>
            <value>
                <fullName>Risk Rating Review</fullName>
            </value>
            <value>
                <fullName>Non Responsive</fullName>
            </value>
            <value>
                <fullName>Needs More Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Reference_Registration__c.field-meta.xml
<CustomField>
    <fullName>Reference_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/X3_Months_to_Re_DD_Due__c.field-meta.xml
<CustomField>
    <fullName>X3_Months_to_Re_DD_Due__c</fullName>
    <formula>If(INCLUDES(eNett_products__c,&quot;VANs&quot;),(DATE(YEAR(DATEVALUE(DD_Completed_Date__c)) + CASE(Due_Diligence_Risk_Rating__c,&#39;Low&#39;,3,&#39;Medium&#39;,2,1),MONTH(DATEVALUE(DD_Completed_Date__c)),DAY(DATEVALUE(DD_Completed_Date__c)))) - 90,NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>3 Months to Re DD Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/DD_Status__c.field-meta.xml
<CustomField>
    <fullName>DD_Status__c</fullName>
    <inlineHelpText>Automatically populated based on the buttons available during DD. ie Pressing Decline button sets the DD status to Declined.</inlineHelpText>
    <label>DD Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting Client</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Approval in Progress</fullName>
            </value>
            <value>
                <fullName>DD Approved</fullName>
            </value>
            <value>
                <fullName>DD Declined</fullName>
            </value>
            <value>
                <fullName>Risk Rating Review</fullName>
            </value>
            <value>
                <fullName>Non Responsive</fullName>
            </value>
            <value>
                <fullName>Needs More Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutomaticReDDHandler.cls
global class AutomaticReDDHandler implements Schedulable {
    
    global void execute(SchedulableContext SC) {
        LIST<Account> accsForUpdate = new LIST<Account>();

        for (Account a : [SELECT id 
                          FROM Account 
                          WHERE Automatic_DD_Checklist_Created__c = false 
                          AND X3_Months_to_Re_DD_Due__c <= TODAY 
                          AND Account_Status__c = 'Active' 
                          AND Reference_Registration__r.DD_Status__c = 'DD Approved'
                          LIMIT 50]) {
            a.Automatic_DD_Checklist_Created__c = true;
            accsForUpdate.add(a);
        }
    
        database.update(accsForUpdate, false);
    }

}