force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Automatically ticked if the account has been activated in client database.</inlineHelpText>
    <label>Client Database Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration_Bank_Account__c/Registration_Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Registration Bank Account</label>
    <nameField>
        <displayFormat>RBA-{000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PopUpDialog_RegBankAccountExts.cls
public class PopUpDialog_RegBankAccountExts {

    public class deactivate extends PopUpDialogController.contExt {

        private Registration_Bank_Account__c rBA {get; set;}

        public deactivate(Id recId) {
            rBA = PopUpDialog_RegBankAccountExts.loadRegBankAccount(recId);
        }       
        
        public override String runProcess() {
            rBA.Active__c = false;
            update rBA;
            return null;
        }
  
        public override String showConfirmMsg() {
            return 'You are about to deactivate the Registration Bank Account for this Registration. Are you sure you want to continue?';
        }

    }
    
    public static Registration_Bank_Account__c loadRegBankAccount(Id recId) {
        Registration_Bank_Account__c regBA;
        regBA = new Registration_Bank_Account__c(id = recId);
        return regBA;
    }

}