force-app/main/default/objects/Account/fields/active_EFT_contract__c.field-meta.xml
<CustomField>
    <fullName>active_EFT_contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>active EFT contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/active_NA_contract__c.field-meta.xml
<CustomField>
    <fullName>active_NA_contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>active N/A contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/active_VANs_contract__c.field-meta.xml
<CustomField>
    <fullName>active_VANs_contract__c</fullName>
    <defaultValue>false</defaultValue>
    <label>active VANs contract</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/product_contracts_active__c.field-meta.xml
<CustomField>
    <fullName>product_contracts_active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Product Contracts Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reference_Registration__c.field-meta.xml
<CustomField>
    <fullName>Reference_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/eNett_Contract__c.object-meta.xml
<CustomObject>
    <label>eNett Contract</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>eNett Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eNett Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/eNett_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eNett Contract</relationshipLabel>
    <relationshipName>eNett_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/eNett_Product__c.field-meta.xml
<CustomField>
    <fullName>eNett_Product__c</fullName>
    <label>eNett Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Flight</fullName>
                <default>true</default>
                <label>In Flight</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>VirtualTerminal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateActiveProductCheckboxesOnAccount.cls
global class UpdateActiveProductCheckboxesOnAccount {

    @InvocableMethod
    global static void UpdateActiveProductCheckboxesOnAccount (LIST<Id> accIds) {
        MAP<Id, Account> accUpdateMap = UpdateActiveProductCheckboxes(accIds);
        update accUpdateMap.values();        
    }
    
    public static Boolean getUpdatedProductContractsActiveCheckbox(Id accId) {
        MAP<Id, Account> accUpdateMap = UpdateActiveProductCheckboxes(new LIST<Id>{accId});
        Boolean prodContractsActive = accUpdateMap.containskey(accId) ? accUpdateMap.get(accId).product_contracts_active__c : false;
        return prodContractsActive;
    }
    
    private static MAP<Id, Account> UpdateActiveProductCheckboxes (LIST<Id> accIds) {
        MAP<Id, Account> accUpdateMap = new MAP<Id, Account>();
        
        for (Id accId : accIds) {
            accUpdateMap.put(accId, new Account(Id = accId, 
                                                active_VANs_contract__c = false, 
                                                active_EFT_contract__c = false,
                                                active_NA_contract__c = false,
                                                product_contracts_active__c = false)
                            );
        }

        Account acc;        
        for (eNett_Contract__c ct : [SELECT Id, eNett_Product__c, Account_Name__c FROM eNett_Contract__c 
                                     WHERE Account_Name__c IN: accIds AND Status__c = 'Active']) {
            acc = accUpdateMap.get(ct.Account_Name__c);
            if (ct.eNett_Product__c == 'VANs') acc.active_VANs_contract__c = true;
            if (ct.eNett_Product__c == 'eNett EFT') acc.active_EFT_contract__c = true;
            if (ct.eNett_Product__c == 'NA') acc.active_NA_contract__c = true;            
        }
       
        SET<String> regProducts;
        for (Account a :[SELECT Id, Reference_Registration__r.Product__c FROM Account WHERE Id IN :accIds]) {  //AND Reference_Registration__r.Product__c != null]) {
            acc = accUpdateMap.get(a.Id);
            regProducts = new Set<String>();
            if (a.Reference_Registration__c != null && a.Reference_Registration__r.Product__c != null) {                
                regProducts = new Set<String>(a.Reference_Registration__r.Product__c.split(';'));
                if (regProducts.contains('VANs') && regProducts.contains('eNett EFT') && acc.active_VANs_contract__c && acc.active_EFT_contract__c) {
                    acc.product_contracts_active__c = true;
                } else if (regProducts.contains('VANs') && !regProducts.contains('eNett EFT') && acc.active_VANs_contract__c) {
                    acc.product_contracts_active__c = true;
                } else if (!regProducts.contains('VANs') && regProducts.contains('eNett EFT') && acc.active_EFT_contract__c) {
                    acc.product_contracts_active__c = true;
                } else if (!regProducts.contains('VANs') && !regProducts.contains('eNett EFT') && regProducts.contains('NA') && acc.active_NA_contract__c) {
                    acc.product_contracts_active__c = true;
                }
            }
            
            // For Channel accounts only
            if (a.Reference_Registration__c == null && (acc.active_VANs_contract__c || acc.active_NA_contract__c))
                acc.product_contracts_active__c = true;
        }   
        
        return accUpdateMap;
    }
    
}