force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Automatically ticked if the account has been activated in client database.</inlineHelpText>
    <label>Client Database Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Due_Diligence_Risk_Rating__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Risk_Rating__c</fullName>
    <inlineHelpText>Populated by the AML team during the due diligence process.</inlineHelpText>
    <label>Risk Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Risk_Rating__c.field-meta.xml
<CustomField>
    <fullName>Risk_Rating__c</fullName>
    <inlineHelpText>Automatically populated based on the risk rating selected in the Risk Assessment record.</inlineHelpText>
    <label>Risk Rating</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Rating_Evidence__c/Risk_Rating_Evidence__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRiskAssessment</customHelpPage>
    <label>Risk Assessment</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Risk Assessment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Rating_Evidence__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipName>Risk_Rating_Evidence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Risk_Rating_Evidence__c/fields/Risk_Rating__c.field-meta.xml
<CustomField>
    <fullName>Risk_Rating__c</fullName>
    <label>Risk Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RiskRatingsUtility.cls
global class RiskRatingsUtility {
    
    webservice static Boolean checkRiskRatingDowngrade (Id RegId, Id AccId) {
        
        LIST<Risk_Rating_Evidence__c> rrs;
        LIST<Account> accs;
        
        rrs = [SELECT Risk_Rating__c FROM Risk_Rating_Evidence__c WHERE Registration__c = :RegId AND Active__c = true ORDER BY Name DESC LIMIT 1];      
        accs = [SELECT Due_Diligence_Risk_Rating__c FROM Account WHERE Id = :AccId];
        
        // If Risk Rating downgraded from high => return true
        if (!accs.isEmpty() && !rrs.isEmpty() && accs[0].Due_Diligence_Risk_Rating__c == 'High' && rrs[0].Risk_Rating__c != 'High') {
            return true;
        } else {
            return false;
        }
    }

}