force-app/main/default/objects/Account/fields/Allow_Change_to_Reporting_Parent__c.field-meta.xml
<CustomField>
    <fullName>Allow_Change_to_Reporting_Parent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allow Change to Reporting Parent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ultimate_Parent__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent__c</fullName>
    <formula>IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Name)), Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Name)), Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.Name)), Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Name)), Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Name)), Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Name)), Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Name)), Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Name)), Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Name)),Parent.Id,
Id)))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ultimate Parent</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HierarchyChartControllerTest.cls
@isTest public class HierarchyChartControllerTest {
	
    @isTest static void testRun(){
        
        //Data Setup
        Account testParentAcc = eNettTestUtility.createAccount('Parent');
        Account testChildAcc = eNettTestUtility.createAccountWithECN('Child', '2');
        testChildAcc.Allow_Change_to_Reporting_Parent__c = true;
        testChildAcc.ParentId = testParentAcc.Id;
        update testChildAcc;
        System.debug('#####parent: ' + testChildAcc.Ultimate_Parent__c);
        update testChildAcc;
        String name = 'Parent';
        
        //Perform Test
        test.startTest();
        HierarchyChartController testCtrl = new HierarchyChartController(new ApexPages.StandardController(testChildAcc));
       	testCtrl.getUpar();
        HierarchyChartController.loadAccounts(name);
        test.stopTest();
    }
}