force-app/main/default/objects/Account/fields/AML_Contact_Creation__c.field-meta.xml
<CustomField>
    <fullName>AML_Contact_Creation__c</fullName>
    <label>AML Contact Creation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Internal_Account_Approval__c.field-meta.xml
<CustomField>
    <fullName>Internal_Account_Approval__c</fullName>
    <inlineHelpText>This field will be set when the associated Task Approval picklist is set to either Approved or Declined.  Until then, the field will remain in the Pending status.</inlineHelpText>
    <label>Internal Account Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <inlineHelpText>Automatically updated based on the progress of the Registration.</inlineHelpText>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting Acceptance</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>New (Product)</fullName>
            </value>
            <value>
                <fullName>Rejected - Non-responsive</fullName>
            </value>
            <value>
                <fullName>Rejected - Spam/test application</fullName>
            </value>
            <value>
                <fullName>Rejected - Application N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/T_C_Completed__c.field-meta.xml
<CustomField>
    <fullName>T_C_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Automatically populated if the T&amp;Cs were completed by the client.</inlineHelpText>
    <label>T&amp;C Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Left Account</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/eNett_Contract__c/eNett_Contract__c.object-meta.xml
<CustomObject>
    <label>eNett Contract</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>eNett Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eNett Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/eNett_Contract__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard T&amp;Cs</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Contract not required</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Internal Transacting</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Flight</fullName>
                <default>true</default>
                <label>In Flight</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard T&amp;Cs</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Contract not required</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Internal Transacting</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <businessProcess>eNett sales</businessProcess>
    <description>Contract progression: Negotiation, Terms Approved Internally, Pending Client Approval, Contract Signed/ On Hold</description>
    <label>Contract</label>
</RecordType>

force-app/main/default/objects/Process_Task__c/Process_Task__c.object-meta.xml
<CustomObject>
    <label>Process Task</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Process Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Tasks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Task__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Account_Decline_Reason__c.field-meta.xml
<CustomField>
    <fullName>Account_Decline_Reason__c</fullName>
    <label>Account Approval/Decline Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/AML_Contact_Creation__c.field-meta.xml
<CustomField>
    <fullName>AML_Contact_Creation__c</fullName>
    <label>AML Contact Creation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard T&amp;Cs</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Contract not required</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Internal Transacting</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Delivery_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Ticket</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Open Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/eNett_Contract__c.field-meta.xml
<CustomField>
    <fullName>eNett_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up the &#39;eNett Contract&#39; record to which this Task record is related to.</description>
    <inlineHelpText>Looks up the &#39;eNett Contract&#39; record to which this Task record is related to.</inlineHelpText>
    <label>eNett Contract</label>
    <referenceTo>eNett_Contract__c</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Estimated_Effort_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Effort_Minutes__c</fullName>
    <label>Estimated Effort Minutes</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Internal_Account_Approval__c.field-meta.xml
<CustomField>
    <fullName>Internal_Account_Approval__c</fullName>
    <label>Internal Account Approval</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <description>Used to reference Record Type Developer Name in buttons, formulas, triggers or classes.</description>
    <formula>RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <formula>TEXT(Opportunity__r.Account.Reference_Registration__r.Registration_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registration Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PopUpDialog_ProcessTaskExts.cls
public class PopUpDialog_ProcessTaskExts {
    
    public class completeTask extends PopUpDialogController.contExt {
        
        private Process_Task__c pt {get; set;}
        
        public completeTask(Id recId) {
            pt = PopUpDialog_ProcessTaskExts.loadProcessTask(recId);
        }    
        
        public override String showConfirmMsg() {
            return 'Are you sure you wish to complete the task?'; // This should be null but VF page will need updating first to support this.
        }
        
        public override String runProcess() {
            String return_URL = null;
            pt.status__c = 'Completed';
            update pt;
            if (pt.Delivery_Ticket__c != null) {
                return_URL = pt.Delivery_Ticket__c;
            }
            return return_URL;
        }
        
        public override String runValidation() {
            if (pt.Estimated_Effort_Minutes__c == null || pt.Estimated_Effort_Minutes__c == 0) {
                return 'Please enter Estimated Effort Minutes for this task.';
            } else {
                return null;
            }
        }
        
    }
    
    public class completeInternalAccountContactTask extends PopUpDialogController.contExt {
        
        private Process_Task__c pt {get; set;}
        
        public completeInternalAccountContactTask(Id recId) {
            pt = PopUpDialog_ProcessTaskExts.loadProcessTask(recId);
        }    
        
        public override String showConfirmMsg() {
            return 'Are you sure you wish to complete the task?';
        }
        
        public override String runProcess() {
            String return_URL = null;
            pt.status__c = 'Completed';
            pt.AML_Contact_Creation__c = 'Completed';            
            update pt;
            if (pt.Account__c != null) return_URL = pt.Account__c;
            return return_URL;
        }
        
    }
    
    public class approveInternalTransactingAccount extends PopUpDialogController.contExt {
        
        private Process_Task__c pt {get; set;}
        
        public approveInternalTransactingAccount(Id recId) {
            pt = PopUpDialog_ProcessTaskExts.loadProcessTask(recId);
        }    
        
        public override String showConfirmMsg() {
            return 'You are about to approve the new Internal Account, press Continue or Cancel to abort.';
        }
        
        public override String runProcess() {
            String return_URL = null;
            pt.status__c = 'Completed';
            pt.Internal_Account_Approval__c = 'Approved';         
            update pt;
            if (pt.Account__c != null) return_URL = pt.Account__c;
            return return_URL;
        }
        
    }    
    
    public class completeOpportunityTask extends PopUpDialogController.contExt {
        
        private Process_Task__c pt {get; set;}
        
        public completeOpportunityTask(Id recId) {
            pt = PopUpDialog_ProcessTaskExts.loadProcessTask(recId);
        }    
        
        public override String runValidation() {
            if (pt.Contract_Type__c == 'Standard T&Cs' && !string.isblank(pt.Registration_Status__c) && pt.Registration_Status__c != 'Complete') {
                return 'The Registration data entry has not been completed. Please ensure Registration is complete prior to completing this task.';
            } else {
                return null;
            }
        }
        
        public override String showConfirmMsg() {
            if (pt.Contract_Type__c == 'Standard T&Cs' && !pt.Account__r.T_C_Completed__c) {
                return 'By proceeding with this action, this will automatically send an email to the Client with a link requesting them to select the Standard T&Cs contract acceptance checkbox. <br/><br/>Are you sure you want to proceed?';
            } else {
                return 'Are you sure you wish to complete the Opportunity Task?';
            }
        }
        
        public override String runProcess() {
            String return_URL = null;
            pt.status__c = 'Completed';
            update pt;
            if (pt.Opportunity__c!= null) {
                return_URL = pt.Opportunity__c;
            }
            return return_URL;
        }
    }  
    
    
    public class completeContractTask extends PopUpDialogController.contExt {
        
        private Process_Task__c pt {get; set;}
        
        public completeContractTask(Id recId) {
            pt = PopUpDialog_ProcessTaskExts.loadProcessTask(recId);
        }    
        
        public override String showConfirmMsg() {
            return 'Are you sure you wish to complete the Contract Task?';
        }
        
        public override String runProcess() {
            String return_URL = null;
            pt.status__c = 'Completed';
            update pt;
            if (pt.eNett_Contract__c != null) {
                return_URL = pt.eNett_Contract__c;
            }
            return return_URL;
        }
        
    }
    //SF-5269 11/10/2018 Jasmine - Create a method to approve 'Approve Account' task, this method only allows people who belong to 'Account Approval Queue' to approve this type of task
    public class approveApproveAccountTask extends PopUpDialogController.contExt {
        
        private Process_Task__c pt {get; set;}
        private Boolean isUserValid {get; set;}
        
        List<Group> accountApprovalQueue = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName ='Account_Approval_Queue' LIMIT 1];
        
        Map<Id, GroupMember> queueMember = new Map<Id, GroupMember>([SELECT UserOrGroupId FROM GroupMember WHERE GroupId =: accountApprovalQueue]);
        
        String currentUserId = UserInfo.getUserId();
        
        public override String showConfirmMsg() {
            return 'You are about to approve a new account. Enter the reason for approval if necessary.';
        }
        
        public approveApproveAccountTask(Id recId) {
            pt = PopUpDialog_ProcessTaskExts.loadProcessTask(recId);
        }    
        
        public override String runValidation() {
            //SF-5370 19/11/2018 Jasmine - Fix the issue where users are unable to approve process tasks whenin the Account Approval Queue
            //String message = null;
            String message = 'You do not have permission to approve this kind of process tasks. Please contact the administrator for assistance.';
            for (GroupMember gm: queueMember.values()){
                if (gm.UserOrGroupId == currentUserId){
                    isUserValid = true;
                    message = null;
                }
                //SF-5370 19/11/2018 Jasmine - Fix the issue where users are unable to approve process tasks whenin the Account Approval Queue
                /*else{
isUserValid = false;
System.debug('#####isUserValid: ' + isUserValid);
message = 'You do not have permission to approve this kind of process tasks. Please contact the administrator for assistance.';
}*/
            }
            return message;
        }
        
        public override String runProcess() {
            String return_URL = null;
            pt.status__c = 'Completed';
            pt.Internal_Account_Approval__c = 'Approved';
            //SF-5424 added approval reasons
            pt.Account_Decline_Reason__c = 'Approved -- ' + userTextInput;
            update pt;
            return_URL = pt.Id;
            return return_URL;
        }
        
        //SF-5424 Ronnie -- allow users to input approval reasons
        public override Boolean showInputTextField() {
            return true;
        }      
        
    }  
    
    //SF-5424 based on approveApproveAccountTask
    public class declineApproveAccountTask extends PopUpDialogController.contExt {
        
        private Process_Task__c pt {get; set;}
        private Boolean isUserValid {get; set;}
        
        List<Group> accountApprovalQueue = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName ='Account_Approval_Queue' LIMIT 1];
        
        Map<Id, GroupMember> queueMember = new Map<Id, GroupMember>([SELECT UserOrGroupId FROM GroupMember WHERE GroupId =: accountApprovalQueue]);
        
        String currentUserId = UserInfo.getUserId();
        
        public override String showConfirmMsg() {
            return 'You are about to decline a new account. Enter the reason for decline.';
        }
        
        public declineApproveAccountTask(Id recId) {
            pt = PopUpDialog_ProcessTaskExts.loadProcessTask(recId);
        }    
        
        public override String runValidation() {
            String message = 'You do not have permission to approve this kind of process tasks. Please contact the administrator for assistance.';
            for (GroupMember gm: queueMember.values()){
                if (gm.UserOrGroupId == currentUserId){
                    isUserValid = true;
                    message = null;
                }
            }
            return message;
        }
        
        public override String runProcess() {
            String return_URL = null;
            if (userTextInput == '')
                throw new applicationException('Reason cannot be blank.');
            
            pt.status__c = 'Completed';
            pt.Internal_Account_Approval__c = 'Declined';
            pt.Account_Decline_Reason__c = 'Declined -- ' + userTextInput;
            update pt;
            return_URL = pt.Id;
            return return_URL;
        }
        
        public override Boolean showInputTextField() {
            return true;
        }      
        
    }  
    
    public static Process_Task__c loadProcessTask(Id recId) {
        Process_Task__c prTask;
        prTask = [SELECT Id, Account__c, Estimated_Effort_Minutes__c, Delivery_Ticket__c, Contract_Type__c, Opportunity__c, eNett_Contract__c, Record_Type__c, Registration_Status__c, Account__r.T_C_Completed__c
                  FROM Process_Task__c
                  WHERE Id = :recId];
        return prTask;
    }
    
    public class applicationException extends Exception {}
    
}