force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>DD Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>This field is used by the Salesforce integrator and should not be modified unless you understand the data-flow consequences</description>
    <inlineHelpText>WARNING This field is used by the Salesforce integrator.</inlineHelpText>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>No. Just don&#39;t.</description>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>hey you there stop that.</description>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>Account Completed DD</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Implementation_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Implementation_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Implementation Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Delivery Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>eNett Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
                <default>true</default>
                <label>VANs</label>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Virtual Terminal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestAssignUnassignedEnett.cls
@isTest
public class TestAssignUnassignedEnett{
    
    static testMethod void testUpdate(){
        setUpTestData();
    }
        
    public static void setUpTestData(){
       /* Opportunity testOpp = new Opportunity (Name = 'Test Region', AccountId = '0019000001F89F1', Region__c= 'Americas', 
                                                Product__c = 'VANs', Type = 'New', CurrencyIsoCode = 'EUR', StageName = 'Proposal', CloseDate = Date.today(),  Primary_Implementation_Contact__c = '003N000000KDFRE');
        Insert testOpp;
        System.debug('The owner is ' + testOpp.owner);
        
        Opportunity testOppEmea = new Opportunity (Name = 'Test Region', AccountId = '001N000000O6mYg', Region__c= 'EMEA', 
                                                Product__c = 'VANs', Type = 'New', CurrencyIsoCode = 'EUR', StageName = 'Proposal', CloseDate = Date.today(),  Primary_Implementation_Contact__c = '003N000000KDFRE');
        Insert testOppEmea ;
        
        System.debug('The owner is ' + testOppEmea.owner); */
        
        Datetime dt = DateTime.parse('10/10/2014 12:00 AM');

        Account testaccount = new Account(Name = 'Account Test', Legal_Name__c = 'Account Test', 
        Client_Status__c = 'Prospect', IntegratorModifiedDate__c = system.now(), IsApi__c = true, Due_Diligence_Completed__c = dt);
        insert testaccount;

        Contact contactperson = new Contact(FirstName = 'Firsttest', LastName = 'Lastest', AccountId = testaccount.id, IsApi__c = true);
        insert contactperson ;
        
        Opportunity Opp = new Opportunity(Name= 'Test Opp', AccountId = testaccount.id, Product__c = 'VANs', 
        Type = 'New', CloseDate = date.valueOf('2014-01-01'), 
        StageName = '1. Prospect', CurrencyIsoCode = 'USD', Region__c= 'Americas');
        
        /*insert Opp;
        
        Opportunity unOpp = new Opportunity(Name= 'Test Opp', AccountId = testaccount.id, Product__c = 'VANs', 
        Type = 'New', CloseDate = date.valueOf('2014-01-01'), 
        StageName = '1. Prospect', CurrencyIsoCode = 'USD', Region__c= 'APAC');
    
        insert unOpp;
        
        System.debug('The owner is ' + Opp.owner);*/
        
    }
}