force-app/main/default/objects/Account/fields/Client_internal_classification__c.field-meta.xml
<CustomField>
    <fullName>Client_internal_classification__c</fullName>
    <description>Total Company GDV  This field was previously a picklist type (Referrer, TTV &lt;$50m, TTV $50m - $1b, TTV &gt;$1b).</description>
    <inlineHelpText>Please enter the classification as a whole numerical value.  Abbreviated values are permitted (B - Billion, M - Million, K - Thousand) Eg 1M - Will automatically be converted to 1,000,000.</inlineHelpText>
    <label>Total GDV p.a.</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Referrer_Name__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Name__c</fullName>
    <label>Introducer / Referrer Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>About Payments</fullName>
            </value>
            <value>
                <fullName>Adyen</fullName>
            </value>
            <value>
                <fullName>Agoda</fullName>
            </value>
            <value>
                <fullName>Air Asia</fullName>
            </value>
            <value>
                <fullName>Axess International Network, Inc</fullName>
            </value>
            <value>
                <fullName>Blue Team Travel Network SRL</fullName>
            </value>
            <value>
                <fullName>CCRA International</fullName>
            </value>
            <value>
                <fullName>CEE Travel System</fullName>
            </value>
            <value>
                <fullName>Club Travel SA</fullName>
            </value>
            <value>
                <fullName>Computop</fullName>
            </value>
            <value>
                <fullName>Conferma</fullName>
            </value>
            <value>
                <fullName>Contac Services</fullName>
            </value>
            <value>
                <fullName>Cornerstone</fullName>
            </value>
            <value>
                <fullName>Dolphin Dynamics</fullName>
            </value>
            <value>
                <fullName>Flightgenius</fullName>
            </value>
            <value>
                <fullName>Gant Travel Management</fullName>
            </value>
            <value>
                <fullName>Gateway</fullName>
            </value>
            <value>
                <fullName>Geo Travel Network Di Geo Spa</fullName>
            </value>
            <value>
                <fullName>Globalcollect</fullName>
            </value>
            <value>
                <fullName>Globalstar</fullName>
            </value>
            <value>
                <fullName>Hitchhiker</fullName>
            </value>
            <value>
                <fullName>Hotelzon</fullName>
            </value>
            <value>
                <fullName>IGA Voyages</fullName>
            </value>
            <value>
                <fullName>Juniper</fullName>
            </value>
            <value>
                <fullName>Manor</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Mr Orange</fullName>
            </value>
            <value>
                <fullName>Multicom</fullName>
            </value>
            <value>
                <fullName>Navitas</fullName>
            </value>
            <value>
                <fullName>Orchestra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Delivery - Desktop</fullName>
            </value>
            <value>
                <fullName>Delivery - API</fullName>
            </value>
            <value>
                <fullName>Delivery Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>eNett Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
                <default>true</default>
                <label>VANs</label>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Virtual Terminal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Referrer_Name__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Name__c</fullName>
    <inlineHelpText>Confirm status of referral with Country Manager before selecting</inlineHelpText>
    <label>Introducer / Referrer Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>About Payments</fullName>
            </value>
            <value>
                <fullName>Adyen</fullName>
            </value>
            <value>
                <fullName>Agoda</fullName>
            </value>
            <value>
                <fullName>Air Asia</fullName>
            </value>
            <value>
                <fullName>Axess International Network, Inc</fullName>
            </value>
            <value>
                <fullName>CCRA International</fullName>
            </value>
            <value>
                <fullName>CEE Travel System</fullName>
            </value>
            <value>
                <fullName>Club Travel SA</fullName>
            </value>
            <value>
                <fullName>Computop</fullName>
            </value>
            <value>
                <fullName>Conferma</fullName>
            </value>
            <value>
                <fullName>Contac Services</fullName>
            </value>
            <value>
                <fullName>Cornerstone</fullName>
            </value>
            <value>
                <fullName>Dolphin Dynamics</fullName>
            </value>
            <value>
                <fullName>Flightgenius</fullName>
            </value>
            <value>
                <fullName>Gant Travel Management</fullName>
            </value>
            <value>
                <fullName>Gateway</fullName>
            </value>
            <value>
                <fullName>Geo SPA</fullName>
            </value>
            <value>
                <fullName>Globalcollect</fullName>
            </value>
            <value>
                <fullName>HitchHiker</fullName>
            </value>
            <value>
                <fullName>Hotelzon</fullName>
            </value>
            <value>
                <fullName>IGA Voyages</fullName>
            </value>
            <value>
                <fullName>Juniper</fullName>
            </value>
            <value>
                <fullName>Lloyd &amp; Co. Pty Ltd</fullName>
            </value>
            <value>
                <fullName>Manor</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Mr Orange</fullName>
            </value>
            <value>
                <fullName>Multicom</fullName>
            </value>
            <value>
                <fullName>Navitas</fullName>
            </value>
            <value>
                <fullName>Orchestra</fullName>
            </value>
            <value>
                <fullName>PayU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Status_Timer__c/Opportunity_Status_Timer__c.object-meta.xml
<CustomObject>
    <label>Opportunity Status Timer</label>
    <nameField>
        <displayFormat>OST-{00000000}</displayFormat>
        <label>Opportunity Status Timer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Status Timers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Status_Timer__c/fields/Prior_Status__c.field-meta.xml
<CustomField>
    <fullName>Prior_Status__c</fullName>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Status_Timer__c/fields/RelatedOpportunity__c.field-meta.xml
<CustomField>
    <fullName>RelatedOpportunity__c</fullName>
    <label>RelatedOpportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Status Timers</relationshipLabel>
    <relationshipName>Opportunity_Status_Timers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TEST_Trigger_OpportunityStatusTimer.cls
@isTest
private class TEST_Trigger_OpportunityStatusTimer {
    
    @isTest static void TEST_Trigger_OpportunityStatusTimer() {

        /***********************************************
            Insert an Account
        ***********************************************/
        
        Account testAccount = new Account(
                                    Name = 'Account Test', 
                                    Legal_Name__c = 'Account Test', 
                                    Client_Status__c = 'Prospect', 
                                    Region__c = 'APAC',
                                    Customer_Sector__c = 'Agent',                                   
                                    //Client_internal_classification__c = 12000000,
                                    Referrer_Name__c = 'Mastercard',
                                    IsApi__c = true); 
        insert testAccount;
 
        System.assert(testAccount.Id != null, 'Account not inserted.');


        /*********************************************************************************
            Create an Opportunity with Status = "1. Prospect"
        *********************************************************************************/

        Opportunity Opp1 = new Opportunity(
                                    Name= 'Test Opp',
                                    AccountId = testAccount.Id ,
                                    Product__c = 'VANs',
                                    Type = 'New',
                                    CloseDate = date.valueOf('2014-01-01'),
                                    StageName = '1. Prospect',
                                    CurrencyIsoCode = 'USD',
                                    Delivery_Type__c = null);
        /*insert Opp1;

        // WF Sets to Stage 7 when the Account is DD Completed ?
        List<Opportunity> chkOpp = 
            [Select Id, StageName from Opportunity where id = :opp1.Id];


        List<Opportunity_Status_Timer__c> oppTimer0 = 
            [Select Id, Prior_Status__c, Name, Elapsed_Time_Days__c, Elapsed_Time_Hours__c from Opportunity_Status_Timer__c 
                where RelatedOpportunity__c = :opp1.Id];
        */

        /*------------------------------------------------
          Change the Opp Stage to "1. Prospect"
        ------------------------------------------------*/
        /*
        Opp1.StageName = '1. Prospect';
        Update Opp1;

        List<Opportunity_Status_Timer__c> oppTimer1 = 
            [Select Id, Prior_Status__c, Name, Elapsed_Time_Days__c, Elapsed_Time_Hours__c from Opportunity_Status_Timer__c 
             where RelatedOpportunity__c = :opp1.Id];
        */

 
        /*------------------------------------------------
          Change the Opp Stage to "2. Meeting Held"
        ------------------------------------------------*/
//        Opp1.StageName = '2. Sales Qualified';
//        Update Opp1;
//        List<Opportunity_Status_Timer__c> oppTimer2 = 
//            [Select Id, Prior_Status__c, Name, Elapsed_Time_Days__c, Elapsed_Time_Hours__c from Opportunity_Status_Timer__c 
//             where RelatedOpportunity__c = :opp1.Id];


        /*------------------------------------------------
           Change the Opp Stage to "1. Sales Qualified"
        ------------------------------------------------*/
//        Opp1.StageName = '1. Prospect';
//        Update Opp1;
//        List<Opportunity_Status_Timer__c> oppTimer3 = 
//            [Select Id, Prior_Status__c, Name, Elapsed_Time_Days__c, Elapsed_Time_Hours__c from Opportunity_Status_Timer__c 
//             where RelatedOpportunity__c = :opp1.Id];

        /*------------------------------------------------
          Change the Opp Stage to "3. Sales Qualified"
        ------------------------------------------------*/
//        Opp1.StageName = '3. Sales Qualified';
//        Update Opp1;
//        List<Opportunity_Status_Timer__c> oppTimer4 = 
//            [Select Id, Prior_Status__c, Name, Elapsed_Time_Days__c, Elapsed_Time_Hours__c from Opportunity_Status_Timer__c 
//             where RelatedOpportunity__c = :opp1.Id];       

    }
}