force-app/main/default/objects/Account/fields/Client_internal_classification__c.field-meta.xml
<CustomField>
    <fullName>Client_internal_classification__c</fullName>
    <description>Total Company GDV  This field was previously a picklist type (Referrer, TTV &lt;$50m, TTV $50m - $1b, TTV &gt;$1b).</description>
    <inlineHelpText>Please enter the classification as a whole numerical value.  Abbreviated values are permitted (B - Billion, M - Million, K - Thousand) Eg 1M - Will automatically be converted to 1,000,000.</inlineHelpText>
    <label>Total GDV p.a.</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Referrer_Change_History__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Change_History__c</fullName>
    <label>Referrer Change History</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Referrer_Change_Justification__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Change_Justification__c</fullName>
    <inlineHelpText>Mandatory field if the referrer has been changed.</inlineHelpText>
    <label>Referrer Change Justification</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Referrer_Name__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Name__c</fullName>
    <label>Introducer / Referrer Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>About Payments</fullName>
            </value>
            <value>
                <fullName>Adyen</fullName>
            </value>
            <value>
                <fullName>Agoda</fullName>
            </value>
            <value>
                <fullName>Air Asia</fullName>
            </value>
            <value>
                <fullName>Axess International Network, Inc</fullName>
            </value>
            <value>
                <fullName>Blue Team Travel Network SRL</fullName>
            </value>
            <value>
                <fullName>CCRA International</fullName>
            </value>
            <value>
                <fullName>CEE Travel System</fullName>
            </value>
            <value>
                <fullName>Club Travel SA</fullName>
            </value>
            <value>
                <fullName>Computop</fullName>
            </value>
            <value>
                <fullName>Conferma</fullName>
            </value>
            <value>
                <fullName>Contac Services</fullName>
            </value>
            <value>
                <fullName>Cornerstone</fullName>
            </value>
            <value>
                <fullName>Dolphin Dynamics</fullName>
            </value>
            <value>
                <fullName>Flightgenius</fullName>
            </value>
            <value>
                <fullName>Gant Travel Management</fullName>
            </value>
            <value>
                <fullName>Gateway</fullName>
            </value>
            <value>
                <fullName>Geo Travel Network Di Geo Spa</fullName>
            </value>
            <value>
                <fullName>Globalcollect</fullName>
            </value>
            <value>
                <fullName>Globalstar</fullName>
            </value>
            <value>
                <fullName>Hitchhiker</fullName>
            </value>
            <value>
                <fullName>Hotelzon</fullName>
            </value>
            <value>
                <fullName>IGA Voyages</fullName>
            </value>
            <value>
                <fullName>Juniper</fullName>
            </value>
            <value>
                <fullName>Manor</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Mr Orange</fullName>
            </value>
            <value>
                <fullName>Multicom</fullName>
            </value>
            <value>
                <fullName>Navitas</fullName>
            </value>
            <value>
                <fullName>Orchestra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <description>A Company (eNett client or non eNett client) refers eNett products to other companies.</description>
    <label>Referrer</label>
</RecordType>

force-app/main/default/classes/TEST_Trigger_ReferrerHistoryTracking.cls
@isTest
private class TEST_Trigger_ReferrerHistoryTracking {
    
    @isTest static void TEST_Trigger_ReferrerHistoryTracking() {

        /***********************************************
            Insert an Account
        ***********************************************/
        
        Account testAccount = new Account(
                                    Name = 'Account Test', 
                                    Legal_Name__c = 'Account Test', 
                                    Client_Status__c = 'Prospect', 
                                    Region__c = 'APAC',
                                    Customer_Sector__c = 'Agent',                                   
                                    //Client_internal_classification__c = 12000000,
                                    Referrer_Name__c = 'Mastercard',
                                    IsApi__c = true); 
        insert testAccount;

        System.assert(testAccount.Id != null, 'Account not inserted.');


        /**************************************************************************************
            Update the Referrer providing NO justification
            We should get an exception
        **************************************************************************************/

        Account theAcct = 
            [Select Id, Referrer_Name__c, Referrer_Change_Justification__c, Referrer_Change_History__c 
                from Account where id = :testAccount.Id LIMIT 1];

        theAcct.Referrer_Name__c = 'Agoda';

        /*try
        {
            update theAcct;
            System.Assert(true == false, 'An exception should have been thrown by the trigger but was not.'); 
        }
        catch(DmlException e)
        {
            System.Assert(e.getMessage().contains('Please enter or modify the Referrer Change Justification'), e.getMessage());
            System.Debug('********** We received the ERROR we expected.');
        } */


        /**************************************************************************************
            Now set the justification. Record should save successfully.
        **************************************************************************************/

        theAcct.Referrer_Change_Justification__c = 'The Origninal Justification';

        update theAcct;

        Account theAcctUpd = 
            [Select Id, Referrer_Name__c, Referrer_Change_Justification__c, Referrer_Change_History__c 
                from Account where id = :testAccount.Id LIMIT 1];

        System.Debug('********** ReferrerName = ' + theAcctUpd.Referrer_Name__c);
        System.Debug('********** ReferrerChangeJust = ' + theAcctUpd.Referrer_Change_Justification__c);
        System.Debug('********** ReferrerChangeJustHist = ' + theAcctUpd.Referrer_Change_History__c);


        /**************************************************************************************
            Update again for full code coverage.
        **************************************************************************************/


        theAcctUpd.Referrer_Name__c = 'Mastercard';
        theAcctUpd.Referrer_Change_Justification__c = 'The subsequent Justification';

        update theAcctUpd;

        Account theAcctUpd2 = 
            [Select Id, Referrer_Name__c, Referrer_Change_Justification__c, Referrer_Change_History__c 
                from Account where id = :testAccount.Id LIMIT 1];

        System.Debug('********** ReferrerName = ' + theAcctUpd2.Referrer_Name__c);
        System.Debug('********** ReferrerChangeJust = ' + theAcctUpd2.Referrer_Change_Justification__c);
        System.Debug('********** ReferrerChangeJustHist = ' + theAcctUpd2.Referrer_Change_History__c);
        
    }
}