force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>DD Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>This field is used by the Salesforce integrator and should not be modified unless you understand the data-flow consequences</description>
    <inlineHelpText>WARNING This field is used by the Salesforce integrator.</inlineHelpText>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <inlineHelpText>This field will display the Delivery Type that is selected in the related Opportunity.</inlineHelpText>
    <label>Delivery Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dormant_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Dormant_End_Date__c</fullName>
    <label>Dormant End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dormant_Reason__c.field-meta.xml
<CustomField>
    <fullName>Dormant_Reason__c</fullName>
    <inlineHelpText>This is a free text area to put in any notes regarding the Dormant status</inlineHelpText>
    <label>Dormant Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dormant_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Dormant_Start_Date__c</fullName>
    <label>Dormant Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agoda Pro Portal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>eNett Gateway</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>No eNett Product</fullName>
            </value>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>VANs Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Related_Delivery_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Delivery_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Delivery Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Phase Tickets</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>No. Just don&#39;t.</description>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>hey you there stop that.</description>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Delivery_Dormant_History__c/Delivery_Dormant_History__c.object-meta.xml
<CustomObject>
    <label>Delivery Dormant History</label>
    <nameField>
        <displayFormat>DDH-{00000}</displayFormat>
        <label>Delivery Dormant History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Dormant Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Dormant_History__c/fields/Dormant_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Dormant_End_Date__c</fullName>
    <label>Dormant End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Dormant_History__c/fields/Dormant_Reason__c.field-meta.xml
<CustomField>
    <fullName>Dormant_Reason__c</fullName>
    <inlineHelpText>Please enter information about this dormant status instance</inlineHelpText>
    <label>Dormant Reason Additional Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Delivery_Dormant_History__c/fields/Dormant_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Dormant_Start_Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Dormant Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Delivery_Dormant_History__c/fields/Related_Delivery_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Related_Delivery_Ticket__c</fullName>
    <label>Related Delivery Ticket</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Delivery Dormant Record</relationshipLabel>
    <relationshipName>Delivery_Dormant_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_Dormant_Reason__c.field-meta.xml
<CustomField>
    <fullName>Current_Dormant_Reason__c</fullName>
    <label>Current Dormant Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_Dormant_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Current_Dormant_Start_Date__c</fullName>
    <label>Current Dormant Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Delivery - Desktop</fullName>
            </value>
            <value>
                <fullName>Delivery - API</fullName>
            </value>
            <value>
                <fullName>Delivery Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dormant_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Dormant_End_Date__c</fullName>
    <formula>Related_Ticket__r.Dormant_End_Date__c</formula>
    <label>Dormant End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dormant_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Dormant_Start_Date__c</fullName>
    <formula>Related_Ticket__r.Dormant_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dormant Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>Account Completed DD</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Implementation_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Implementation_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Implementation Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Delivery Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>eNett Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
                <default>true</default>
                <label>VANs</label>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Virtual Terminal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TESTDormantInformation.cls
@isTest
private class TESTDormantInformation {
    static testMethod void runTESTDormantInformation () {

        Datetime dt = DateTime.parse('10/10/2014 12:00 AM');
        Date dormantenddate = Date.Today().addDays(2); 

        Account testaccount = new Account(Name = 'Account Test', Legal_Name__c = 'Account Test', Client_Status__c = 'Prospect', IntegratorModifiedDate__c = system.now(), IsApi__c = true, Due_Diligence_Completed__c = dt);
        insert testaccount;
        
        Contact contactperson = new Contact(FirstName = 'Firsttest', LastName = 'Lastest', AccountId = testaccount.id , IsApi__c = true);
        insert contactperson ;
        
        Datetime ddt = testaccount.Due_Diligence_Completed__c;
        Date DueDiligenceDate = ddt.date();
        
        Opportunity Opp1 = new Opportunity(Name= 'Test Opp', AccountId = testaccount.id , Product__c = 'VANs', Type = 'New', CloseDate = date.valueOf('2014-01-01'), StageName = '1. Prospect', CurrencyIsoCode = 'USD', Primary_Implementation_Contact__c =contactperson.Id, Delivery_Type__c = null, Current_Dormant_Start_Date__c = null, Current_Dormant_reason__c = '');
        /*insert Opp1;
         
        Case DeliveryTicket = new Case(AccountId = testaccount.id, Subject = Opp1.name, Related_Delivery_Opportunity__c = Opp1.id, ContactId = contactperson.Id , Status = 'Active', Priority = 'Not None');
        insert DeliveryTicket; 
        
        Delivery_Dormant_History__c firstinstancedormant = New Delivery_Dormant_History__c(Related_Delivery_Ticket__c = DeliveryTicket.id, Dormant_Start_Date__c = Date.today(), Dormant_End_Date__c= null, Dormant_Reason__c = 'reason notes');
        insert firstinstancedormant;
        System.Debug('the dormant end date here is ' + firstinstancedormant.Dormant_End_Date__c);
                
        
        firstinstancedormant.Dormant_End_Date__c = dormantenddate;
        update firstinstancedormant;
        System.Debug('the updated dormant end date here is ' + firstinstancedormant.Dormant_End_Date__c);
        */

        }
}