force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Changes</fullName>
            </value>
            <value>
                <fullName>Activations</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Browser Issue</fullName>
            </value>
            <value>
                <fullName>Client Report</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Delivery/Implementation</fullName>
            </value>
            <value>
                <fullName>Dropped Call</fullName>
            </value>
            <value>
                <fullName>EFT Account Changes</fullName>
            </value>
            <value>
                <fullName>EFT Payment Processing</fullName>
            </value>
            <value>
                <fullName>EFT Refunds</fullName>
            </value>
            <value>
                <fullName>EFT Training Request</fullName>
            </value>
            <value>
                <fullName>ePP</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>FreeNett Payment Processing</fullName>
            </value>
            <value>
                <fullName>Gateway Payment Processing</fullName>
            </value>
            <value>
                <fullName>Gateway Payment Status</fullName>
            </value>
            <value>
                <fullName>Gateway Refund</fullName>
            </value>
            <value>
                <fullName>Gateway Reporting</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Issues</fullName>
            </value>
            <value>
                <fullName>JIRA</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>New Request</fullName>
            </value>
            <value>
                <fullName>Notification</fullName>
            </value>
            <value>
                <fullName>Offboarding</fullName>
            </value>
            <value>
                <fullName>Outage</fullName>
            </value>
            <value>
                <fullName>Password</fullName>
            </value>
            <value>
                <fullName>Payment Status</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Product Request</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Abandon Registration</fullName>
            </value>
            <value>
                <fullName>Account Suspension</fullName>
            </value>
            <value>
                <fullName>Actual Chargeback</fullName>
            </value>
            <value>
                <fullName>Add Email</fullName>
            </value>
            <value>
                <fullName>Add Email Address</fullName>
            </value>
            <value>
                <fullName>Add FeeNett product</fullName>
            </value>
            <value>
                <fullName>Add new Currency</fullName>
            </value>
            <value>
                <fullName>Ad-Hoc</fullName>
            </value>
            <value>
                <fullName>Amend Customised Reports</fullName>
            </value>
            <value>
                <fullName>Amend Limits</fullName>
            </value>
            <value>
                <fullName>Amend Merchant Name</fullName>
            </value>
            <value>
                <fullName>Amend Report Subscription</fullName>
            </value>
            <value>
                <fullName>Amend VAN Issue</fullName>
            </value>
            <value>
                <fullName>API Configuration</fullName>
            </value>
            <value>
                <fullName>API Investigation</fullName>
            </value>
            <value>
                <fullName>Authorisation Cancellation</fullName>
            </value>
            <value>
                <fullName>Bank Account (DDR)</fullName>
            </value>
            <value>
                <fullName>Bank Fax - Auth Reversal</fullName>
            </value>
            <value>
                <fullName>Bank Fax - Auth Verification</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Bank Query- Code Cancelation</fullName>
            </value>
            <value>
                <fullName>Bank Query- Confirm Transaction</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Business Details</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Cancel VAN issue</fullName>
            </value>
            <value>
                <fullName>Certificate Change</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
            </value>
            <value>
                <fullName>Change Email Address</fullName>
            </value>
            <value>
                <fullName>Change Report Subscription</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Final_Solution__c.field-meta.xml
<CustomField>
    <fullName>Final_Solution__c</fullName>
    <label>Final Solution</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hidden_CC_Address__c.field-meta.xml
<CustomField>
    <fullName>Hidden_CC_Address__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <label>Hidden CC Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hidden_Refresh_area__c.field-meta.xml
<CustomField>
    <fullName>Hidden_Refresh_area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Hidden Refresh area</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agoda Pro Portal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>eNett Gateway</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>No eNett Product</fullName>
            </value>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>VANs Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>hey you there stop that.</description>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Stop_Status__c/Stop_Status__c.object-meta.xml
<CustomObject>
    <description>A case status in which the &quot;clock should stop,&quot; i.e. time calculated in business hours should not be added to the &quot;Time With Support&quot; field.</description>
    <label>Stop Status</label>
    <nameField>
        <label>Stop Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stop Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TESTFirstResponsetimeforKPITimer.cls
@isTest
private class TESTFirstResponsetimeforKPITimer {
    static testMethod void runTestFirstResponsetimeforKPITimerforTicket() {
    
    Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator (no expiry)']; 
    
      Account account = new Account(Name = 'Account Test 3', Legal_Name__c = 'Account Test3', Client_Status__c = 'Prospect', IsApi__c = true);
      insert account;
      Contact contact = new Contact(FirstName = 'Testa', LastName = 'Testaw', Account = [select id from Account where Account.Name = 'Account Test 3'], IsApi__c = true);
      insert contact;
      Stop_Status__c ss = new Stop_Status__c(Name = 'Pending');
      insert ss;
      
        Case cnew=new Case(Contact = [select id from contact Order by createddate Desc LIMIT 1], Origin = 'Email', Status = 'New',  Subject = 'New problem to solve for helpdesk', Priority = 'Critical', Product__c = 'VANs', Category__c = 'Sales', Description__c = 'Campaign', Hidden_Refresh_area__c = 1, Hidden_CC_Address__c = 'benchen70@gmail.com;b@gmail.com;c@gmail.com;d@gmail.com;internalservice@enett.com;f@gmail.com;g@gmail.com;h@gmail.com;j@gmail.com;k@gmail.com');

        insert cnew;

        Task tnew = new Task(Subject = 'Call - Connected', WhatId = cnew.Id, Status = 'Not Started', Type = 'Task', Priority = 'Normal', OwnerId = '00590000000riL4', RecordTypeId = '01290000000hwz1');
        //insert tnew;
        //tnew.Estimated_Effort_Minutes__c = 4;
        //tnew.status = 'Completed';
		//update tnew;
		        
        cnew.Final_Solution__c = 'Thank you very much. This is now resolved.';
        cnew.Status = 'Closed';
        update cnew;
      
}
}