force-app/main/default/objects/Account/fields/Client_internal_classification__c.field-meta.xml
<CustomField>
    <fullName>Client_internal_classification__c</fullName>
    <description>Total Company GDV  This field was previously a picklist type (Referrer, TTV &lt;$50m, TTV $50m - $1b, TTV &gt;$1b).</description>
    <inlineHelpText>Please enter the classification as a whole numerical value.  Abbreviated values are permitted (B - Billion, M - Million, K - Thousand) Eg 1M - Will automatically be converted to 1,000,000.</inlineHelpText>
    <label>Total GDV p.a.</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>DD Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>This field is used by the Salesforce integrator and should not be modified unless you understand the data-flow consequences</description>
    <inlineHelpText>WARNING This field is used by the Salesforce integrator.</inlineHelpText>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/KPI_Met__c.field-meta.xml
<CustomField>
    <fullName>KPI_Met__c</fullName>
    <formula>If( KPI_Timer_Minutes__c &lt;= 240, True, False)</formula>
    <label>KPI Met</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>No. Just don&#39;t.</description>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>hey you there stop that.</description>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/serviceEmailToCase.cls
@isTest
public class serviceEmailToCase{
    
   
    Case serviceTicket;
    
    static testMethod void testUpdate(){
    
        Account testaccount = new Account(Name = 'Account Test', Legal_Name__c = 'Account Test', 
        Client_Status__c = 'Prospect', IntegratorModifiedDate__c = system.now(), IsApi__c = true, Due_Diligence_Completed__c = System.today()-56 ); //, Client_internal_classification__c = 100000 );
        insert testaccount;

        Contact contactperson = new Contact(FirstName = 'Firsttest', LastName = 'Lastest', AccountId = testaccount.id, IsApi__c = true);
        insert contactperson ; 
        
        System.debug('Start');

        String queueId = [select Id from Group where Name = 'New Ticket Queue' and Type = 'Queue'].Id;

                
        
        Case serviceCase = new Case (Subject = 'Test Subject', Origin = 'Email', Type = 'Task', Status = 'New', ContactId = contactperson.Id, OwnerId = queueId);
        insert serviceCase;
        
        // Update the case owner to New Ticket Assignement Queue
        serviceCase.OwnerId = queueId;
        update serviceCase;
        
        System.debug('The Queue Case Owner id is ' + [Select OwnerId from Case where Case.Id = :serviceCase.Id]);
        
        
                    
        String profileId =  [select id from profile where name='Stefanini Service Desk User'].Id; 
        String roleId = [select id from UserRole where name='Global Service Desk Level 1'].Id;   
        String stefId = [select Id from User where ProfileId = :profileId AND UserRoleId = :roleId LIMIT 1].Id;
        
        System.debug('Inserted Stefanini User' + stefId );
        
        //Updating the Case owner to Stefanini user  
        serviceCase.OwnerId = stefId;
        update serviceCase;
        
        //System.debug('The User Case Owner id is ' + [Select OwnerId from Case where Case.Id = :serviceCase.Id]);
        
        //Checking the case status and KPI
        Case testCase = [Select Status, KPI_Met__c from Case where Case.Id = :serviceCase.Id];
        //System.assertEquals('Open', testCase.Status, 'Error: The Case status has not changed to open');
        
        //System.debug('The Status is ' + testCase.Status + ' and KPI is ' + testCase.KPI_Met__c );
        //System.debug('The Case Status is ' + serviceCase.Status + ' and KPI is ' + serviceCase.KPI_Met__c );
        
        
        // Case escalation to Service Desk 1
        
        queueId = [select Id from Group where Name = 'Global Service Desk Level 1' and Type = 'Queue'].Id;     
        testCase.OwnerId = queueId;
        update testCase ;
            
        System.assertEquals(queueId, testCase.OwnerId, 'Error: The Case Owner Id is not Case Escalation Service Desk 1');
        //System.debug('The queue id is ' + queueId + ' and the queue case owner id is ' + [Select OwnerId from Case where Case.Id = :testCase.Id] + ' the case status is ' + testCase.Status  );        
        
        List<GroupMember> users = [Select UserOrGroupId From GroupMember where GroupId =:queueId LIMIT 1];
        //System.debug('The size is ' + users.size());
        return;
        
        //Assigning to queue members if queue members are present
        if(users.size() > 0){
          for(GroupMember gm: users){
              queueId = gm.Id;
          }
          testCase.OwnerId = queueId;
          update testCase ;
        }
        
        // Case escalation to Service Desk 2
        queueId = [select Id from Group where Name = 'Global Service Desk Level 2' and Type = 'Queue'].Id;     
        System.debug('The queue Id is ' + queueId);
        testCase.OwnerId = queueId;
        update testCase ;
        
        //System.debug('The queue id in Service Desk Level 2 ' + queueId + ' and the queue case owner id is ' + [Select OwnerId from Case where Case.Id = :testCase.Id] + ' the case status is ' + testCase.Status  );        
        System.assertEquals(queueId, testCase.OwnerId, 'Error: TheCase is not assigned to Global Service Desk Level 2');
        
        
    
    }
    
    
}