force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>DD Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>This field is used by the Salesforce integrator and should not be modified unless you understand the data-flow consequences</description>
    <inlineHelpText>WARNING This field is used by the Salesforce integrator.</inlineHelpText>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Final_Solution__c.field-meta.xml
<CustomField>
    <fullName>Final_Solution__c</fullName>
    <label>Final Solution</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agoda Pro Portal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>eNett Gateway</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>No eNett Product</fullName>
            </value>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>VANs Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>No. Just don&#39;t.</description>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>hey you there stop that.</description>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/TestCreateData.cls
@isTest
public class TestCreateData{
    
   
    Case serviceTicket;
    Case delTicket;
    Account acc;
    Contact contact;
    
    
    public Account createAccount(){
    
        acc = new Account(Name = 'Account Test', Legal_Name__c = 'Account Test', 
        Client_Status__c = 'Prospect', IntegratorModifiedDate__c = system.now(), IsApi__c = true, Due_Diligence_Completed__c = System.today()-56);
        insert acc;
        
        System.debug('The account in test data is ' + acc.Id);
        
        return acc;
    }
    
    //Creates Contact but requires the account Id to be passed.
    public Contact createContact(String accId ){
    
        contact = new Contact(FirstName = 'Firsttest', LastName = 'Lastest', AccountId = accId , IsApi__c = true);
        insert contact ; 
        System.debug('The contact in test data is ' + contact.Id);
        return contact;
    }
    
    //Creates case based on the Contact Id. The owner of the case is New Ticket Queue 
    public Case createServiceTicket(String contactId ){
    
        String queueId = [select Id from Group where Name = 'New Ticket Queue' and Type = 'Queue'].Id;
        serviceTicket = new Case (Subject = 'Test Subject', Origin = 'Email', Type = 'Task', RecordTypeId = '01290000000hwKc', Status = 'New', ContactId = contactId, OwnerId = queueId);
        insert serviceTicket;
        
        System.debug('The ticket id in test data is ' + serviceTicket.Id);

        return serviceTicket;
    }
    
    //Creates phone case based on the Contact Id. The owner of the case is New Ticket Queue 
    public Case createPhoneServiceTicket(String contactId ){
    
        String queueId = [select Id from Group where Name = 'New Ticket Queue' and Type = 'Queue'].Id;
        Case phoneServiceTicket = new Case (Subject = 'Test Subject', Origin = 'Phone', RecordTypeId = '01290000000hwKc', Type = 'Task', Status = 'Open', ContactId = contactId, OwnerId = queueId);
        insert phoneServiceTicket ;
        
        System.debug('The ticket id in test data is ' + phoneServiceTicket.Id);

        return phoneServiceTicket;
    }
    
    //Creates a Stefinini User
    public String createStefaniniUser(){
    
        String stefId = [select Id from User where UserRoleId = :[select id from UserRole where name='Global Service Desk Level 1'].Id LIMIT 1].Id;
        return stefId;
    }
    
    // This is used to close the service ticket
    public Case closeServiceTicket(Case testCase){
    
        testCase.Final_Solution__c = 'Updated the final solution';
        testCase.Product__c = 'VANs';
        testCase.Status = 'Closed';
        update testCase;
        return testCase;
    }
    
    // This is used to create a solution 
    public Solution createSolution(){
    
        Solution solBank = new Solution ( Status = 'Final', SolutionName = 'This is a test solution');
        insert solBank;
        return solBank;
    }
    
    public Case reopenCase(Case testCase){
    
        testCase.Status = 'Closed';
        update testCase;
        return testCase;
    }
    
    static testMethod void testUpdate(){   
    
    }
    
    
}