force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Commercial_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Commercial Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Commercial Parent Account)</relationshipLabel>
    <relationshipName>CommercialParentAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Automatically populated. This field is only populated for accounts which are activated in client database.</inlineHelpText>
    <label>ECN</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Parent__c.field-meta.xml
<CustomField>
    <fullName>Legal_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>LegalAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>A customer using VAN or EFT- client can be travel or corporate</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Case/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <inlineHelpText>This field will display the Delivery Type that is selected in the related Opportunity.</inlineHelpText>
    <label>Delivery Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agoda Pro Portal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>eNett Gateway</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>No eNett Product</fullName>
            </value>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>VANs Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Trading_As__c.field-meta.xml
<CustomField>
    <fullName>Trading_As__c</fullName>
    <formula>Account.Trading_As__c</formula>
    <label>Trading As</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Customer_Experience_Surveys__c.field-meta.xml
<CustomField>
    <fullName>Customer_Experience_Surveys__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This is checked by default to all active clients -- representing the contact&#39;s willingness to receive customer experience surveys.</description>
    <inlineHelpText>Represents if this contact wishes to receive customer experience surveys.</inlineHelpText>
    <label>Customer Experience Surveys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Financial_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Financial_Email_Address__c</fullName>
    <label>Financial Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>hey you there stop that.</description>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <inlineHelpText>This field is automatically populated by the Client system integration.</inlineHelpText>
    <label>Job Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Master administrator</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Delivery Implementation</fullName>
            </value>
            <value>
                <fullName>Operational / Technical</fullName>
            </value>
            <value>
                <fullName>Operational / Technical SMEs</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Secondary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email_Address__c</fullName>
    <label>Secondary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <inlineHelpText>This field is automatically populated by the Eloqua integration.</inlineHelpText>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Business Owner/Proprietor</fullName>
            </value>
            <value>
                <fullName>Chairperson</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>CIO</fullName>
            </value>
            <value>
                <fullName>CMO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Travel Consultant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Inbound_Email__c/Inbound_Email__c.object-meta.xml
<CustomObject>
    <label>Inbound Email</label>
    <nameField>
        <displayFormat>EML-{000000}</displayFormat>
        <label>Inbound Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inbound_Email__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inbound Emails</relationshipLabel>
    <relationshipName>Inbound_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <formula>Company</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Legal Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Trading_As__c.field-meta.xml
<CustomField>
    <fullName>Trading_As__c</fullName>
    <label>Trading As</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <businessProcess>Leads eNett</businessProcess>
    <description>eNett Customer using our products - customer can be travel or corporate</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <formula>Account.ECN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ECN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>eNett Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
                <default>true</default>
                <label>VANs</label>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Virtual Terminal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <businessProcess>eNett sales</businessProcess>
    <description>Contract progression: Negotiation, Terms Approved Internally, Pending Client Approval, Contract Signed/ On Hold</description>
    <label>Contract</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/eNett.recordType-meta.xml
<RecordType>
    <fullName>eNett</fullName>
    <active>true</active>
    <businessProcess>eNett sales</businessProcess>
    <label>eNett</label>
</RecordType>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>VirtualTerminal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/eNettTestUtility.cls
/**
* This class contains utility methods for creating test data for unit tests development
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
* 
* See the Apex Language Reference for more information about Testing and Code Coverage.
*
* author : Surajsingh Thakur
* Date   : 27/12/2017 
*/

public without sharing class eNettTestUtility {
    
    //Create Test User
    public static User createUser(String profileName){
        
        Profile givenProfile = [SELECT Id FROM Profile WHERE Name = :profileName]; 
        
        User testUser = new User(Alias = 'tuser', Email='testuser@testenett.com', 
                                 EmailEncodingKey='UTF-8', LastName='TestUser', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_AU', ProfileId = givenProfile.Id, 
                                 TimeZoneSidKey='Australia/Sydney', UserName='testuser@testenett.com');
        
        insert testUser;
        return testUser;
    }
    
    //Create Test Lead
    public static Lead createLead(String lastName){
        
        Lead testLead = new Lead( LastName = lastName,FirstName='Jay',Company='Wingo Ducks',Phone='(707) 555-0328');
        
        insert testLead;
        return testLead;
    }
    
    //Create Test Account
    public static Account createAccount(String accountName){
        Account testAccount = new Account(Name = accountName, Legal_Name__c = accountName, Trading_As__c = accountName, ECN__c = '000001', Client_Status__c = 'Prospect', IsApi__c = true);
        
        insert testAccount;
        return testAccount;
    }
    
    //Create Test Account with Parent
    public static Account createAccountWithParent(String accountName, ID accountID){
        Account testAccount = new Account(Name = accountName, Legal_Name__c = accountName, Trading_As__c = accountName, Client_Status__c = 'Prospect', IsApi__c = true);
        testAccount.ParentID = accountID;
        testAccount.Commercial_Parent_Account__c = accountID;
        testAccount.Legal_Parent__c = accountID;
        
        insert testAccount;
        return testAccount;
    }
    
    //Create Test Account with ECN
    public static Account createAccountWithECN(String accountName, String ECN){
        Account testAccount = new Account(Name = accountName, Legal_Name__c = accountName, Trading_As__c = accountName, ECN__c = ECN, Client_Status__c = 'Prospect', IsApi__c = true);
        
        insert testAccount;
        return testAccount;
    }
    
    //Create Test Contact
    public static Contact createContact(ID accountID){
        Contact testContact = new Contact(FirstName = 'Enett', 
                                          LastName = 'Contact', 
                                          AccountID = accountID, 
                                          Job_Role__c = 'Primary; Secondary; Financial',
                                          Primary_Email_Address__c = 'primary@email.com',
                                          Secondary_Email_Address__c = 'seoncdary@email.com',
                                          Financial_Email_Address__c = 'financial@email.com',
                                          Salutation = 'Ms',
                                          Title__c = 'CEO',
                                          IsApi__c = true,
                                          Customer_Experience_Surveys__c = true);
        insert testContact; 
        return testContact;
        
    }
    
    //Create Test Opportunity
    public static Opportunity createOpportunity(String opportunityName, ID accountID){
        Opportunity testOpportunity = new Opportunity( Name= opportunityName ,AccountId = accountID ,Product__c = 'VANs',Type = 'New', CloseDate = date.valueOf('2014-01-01'), StageName = '1. Prospect',CurrencyIsoCode = 'USD',Delivery_Type__c = null, Opportunity_Qualify_Created__c = null);
        
        insert testOpportunity;
        return testOpportunity;
    }
    
    //Create Test Registration
    public static Registration__c createRegistration(String companyName, ID accountID){
        Registration__c testReg = new Registration__c(Registered_Company_Name__c = companyName, Account__c = accountID, Product__c = 'VANs; eNett EFT');
        
        insert testReg;
        return testReg;
    }
    
    //Create Test Registration without Parent Account
    public static Registration__c createRegistration(String companyName){
        Registration__c testReg = new Registration__c(Registered_Company_Name__c = companyName, Product__c = 'VANs; eNett EFT');
        
        insert testReg;
        return testReg;
    }
    
    //Create Test Registration Bank Account
    public static Registration_Bank_Account__c createRegistrationBankAccount(ID registrationID){
        Registration_Bank_Account__c testRegistrationBankAccount = new Registration_Bank_Account__c(Registration__c = registrationID, Bank_Code__c = '1', Account_Number__c = '1');
        insert testRegistrationBankAccount;
        return testRegistrationBankAccount;
    }
    
    //Create Test eNett Contract 
    public static eNEtt_Contract__c createENettContract(ID accountID){
        eNEtt_Contract__c testContract = new eNEtt_Contract__c( Account_Name__c = accountID, VAN_Currencies__c = 'some random value', Contract_Type__c ='Standard T&Cs');
        
        insert testContract;
        return testContract;
    }
    
    //Create Test Case 
    public static Case createCase(){
        Case testCase = new Case(Priority = 'Call');
        
        insert testCase;
        return testCase;
    }
    
    //Create Test Case with Parent
    public static Case createCase(Id parentId){
        Case testCase = new Case(Priority = 'Call', ParentId = parentId);
        
        insert testCase;
        return testCase;
    }
    
    //Create Test Beneficial Owner
    public static Beneficial_Owner__c createBeneficialOwner(ID registrationID){
        Beneficial_Owner__c testBeneficialOwner = new Beneficial_Owner__c(Registration__c = registrationID);
        
        insert testBeneficialOwner;
        return testBeneficialOwner;
    }
    
    //Create Test Verification
    public static Verification__c createVerification(){
        Verification__c testVerification = new Verification__c();
        
        insert testVerification;
        return testVerification;
    }
    
    //Create Test Risk Assessment
    public static Risk_Rating_Evidence__c createRiskAssessment(ID registrationId){
        Risk_Rating_Evidence__c testRiskAssessment = new Risk_Rating_Evidence__c(Registration__c = registrationId);
        
        insert testRiskAssessment;
        return testRiskAssessment;
    }
    
    //Create Test Attachment (Note that this will now be converted to File anyway after insert by trigger -- original attachment deleted)
    public static Attachment createAttachment(ID parentID){
        Attachment testAttachment = new Attachment();    
        testAttachment.Name = 'Unit Test Attachment';
        Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
        testAttachment.body = bodyBlob;
        testAttachment.parentId = parentID;
        insert testAttachment;
        return testAttachment;
    }
    
    //Create Test File without Parent
    public static ContentDocument createFile(){
        ContentVersion testFileVersion = new ContentVersion(Title = 'Unit Test File',
                                                            PathOnClient = '/testfile',
                                                            VersionData = Blob.valueOf('Unit Test File Body'));
        insert testFileVersion;
        ContentVersion insertedVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: testFileVersion.Id LIMIT 1];
        return [SELECT Id FROM ContentDocument where Id =: insertedVersion.ContentDocumentId LIMIT 1];
    }
    
    //Create Test File with Parent
    public static ContentDocument createFile(ID parentID){
        ContentVersion testFileVersion = new ContentVersion(Title = 'Unit Test File',
                                                            PathOnClient = '/testfile',
                                                            VersionData = Blob.valueOf('Unit Test File Body'), 
                                                            FirstPublishLocationId = parentID);
        insert testFileVersion;
        ContentVersion insertedVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: testFileVersion.Id LIMIT 1];
        return [SELECT Id FROM ContentDocument where Id =: insertedVersion.ContentDocumentId LIMIT 1];
    }
    
    //Create Test Email Message
    public static EmailMessage createEmailMessage(){
        EmailMessage testEmail = new EmailMessage();
        insert testEmail;
        return testEmail;
    }
    
    //Create Test Email Message with Parent
    public static EmailMessage createEmailMessage(Id parentId){
        EmailMessage testEmail = new EmailMessage(ParentId = parentId);
        insert testEmail;
        return testEmail;
    }
    
    //Create Test Note
    public static Note createNote(){
        Note testNote = new Note();
        insert testNote;
        return testNote;
    }
    
    //Create Customer
    public static Customer__c createCustomer(String customerName){
        Customer__c testCustomer = new Customer__c(Name = customerName);
        
        insert testCustomer;
        return testCustomer;
    }
    
    //Create InboundEmail
    public static Inbound_Email__c createInboundEmail(String emailFromName, String emailFromAddress, String htmlBody, String eamilToAddress, String Subject){
        Inbound_Email__c testInboundEmail = new Inbound_Email__c(From__c= emailFromName,fromAddress__c= emailFromAddress,htmlBody__c = htmlBody, To__c = eamilToAddress,  Subject__c=Subject );
        
        insert testInboundEmail ;
        return testInboundEmail ;
    }
}