force-app/main/default/objects/Account/fields/Client_internal_classification__c.field-meta.xml
<CustomField>
    <fullName>Client_internal_classification__c</fullName>
    <description>Total Company GDV  This field was previously a picklist type (Referrer, TTV &lt;$50m, TTV $50m - $1b, TTV &gt;$1b).</description>
    <inlineHelpText>Please enter the classification as a whole numerical value.  Abbreviated values are permitted (B - Billion, M - Million, K - Thousand) Eg 1M - Will automatically be converted to 1,000,000.</inlineHelpText>
    <label>Total GDV p.a.</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>DD Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>This field is used by the Salesforce integrator and should not be modified unless you understand the data-flow consequences</description>
    <inlineHelpText>WARNING This field is used by the Salesforce integrator.</inlineHelpText>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/deliveryTestCases.cls
/*
Author: Paul Swarnapandian
Last Updated: 08/05/15
This is the class for the delivery cloud test cases
*/

@isTest
public class deliveryTestCases {
    
    static Account testaccount = null;
    static Datetime dt = DateTime.parse('10/10/2014 12:00 AM');
    static testMethod void testUpdate(){
    
       
       System.debug('The test case for Delivery'); 
       setUpTestData();
       
       
       
     }
     public static void setUpTestData(){
         
         testaccount = new Account(Name = 'Account Test', Legal_Name__c = 'Account Test', 
         Client_Status__c = 'Prospect', IntegratorModifiedDate__c = system.now(), IsApi__c = true, Due_Diligence_Completed__c = dt); 
         //Client_internal_classification__c = 100000.00 );
         insert testaccount;
      
     }
}