force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>DD Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>This field is used by the Salesforce integrator and should not be modified unless you understand the data-flow consequences</description>
    <inlineHelpText>WARNING This field is used by the Salesforce integrator.</inlineHelpText>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Delivery_Phase__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Phase__c</fullName>
    <label>Delivery Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 - Pre-Implementation Kick-off</fullName>
            </value>
            <value>
                <fullName>1 - Set Up and Configuration</fullName>
            </value>
            <value>
                <fullName>2 - VAN Training</fullName>
            </value>
            <value>
                <fullName>3 - Funding</fullName>
            </value>
            <value>
                <fullName>4 - VAN Reporting and Reconciliation</fullName>
            </value>
            <value>
                <fullName>1 - Planning &amp; Preparation</fullName>
            </value>
            <value>
                <fullName>2 - Development ( API integration)</fullName>
            </value>
            <value>
                <fullName>3 - UAT</fullName>
            </value>
            <value>
                <fullName>4 - Live testing</fullName>
            </value>
            <value>
                <fullName>5 - Production cut over</fullName>
            </value>
            <value>
                <fullName>Unassigned Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <inlineHelpText>This field will display the Delivery Type that is selected in the related Opportunity.</inlineHelpText>
    <label>Delivery Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Enter_NDA_Developer_License_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Enter_NDA_Developer_License_Signed_Date__c</fullName>
    <inlineHelpText>Confirm paperwork has been returned and enter the date that the NDA/Developer documentation was signed.</inlineHelpText>
    <label>NDA/Developer License Signed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Pre_Kick_off_Questionnaire_Sent__c.field-meta.xml
<CustomField>
    <fullName>Pre_Kick_off_Questionnaire_Sent__c</fullName>
    <inlineHelpText>This field is automatically set when the Kick-off Questionnaire Task is set to Completed.</inlineHelpText>
    <label>Pre Kick-off Questionnaire Sent</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agoda Pro Portal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>eNett Gateway</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>No eNett Product</fullName>
            </value>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>VANs Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Related_Delivery_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Delivery_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Delivery Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Phase Tickets</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Field_Update__c/Case_Field_Update__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Basic Key/Value Lookup to keep application values to minimise hard-coding etc.</description>
    <label>Case Field Update</label>
</CustomObject>

force-app/main/default/objects/Case_Field_Update__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Field_Update__c/fields/Task_recordtype_name__c.field-meta.xml
<CustomField>
    <fullName>Task_recordtype_name__c</fullName>
    <label>Task recordtype name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>No. Just don&#39;t.</description>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>hey you there stop that.</description>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Delivery_NDA_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_NDA_Signed_Date__c</fullName>
    <inlineHelpText>This is a Date field, automatically updated from the relevant Delivery ticket record&#39;s &quot;Enter NDA Developer License Signed Date&quot; field</inlineHelpText>
    <label>Delivery NDA Signed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Phase__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Phase__c</fullName>
    <label>Delivery Phase</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Delivery - Desktop</fullName>
            </value>
            <value>
                <fullName>Delivery - API</fullName>
            </value>
            <value>
                <fullName>Delivery Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>Account Completed DD</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Implementation_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Implementation_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Implementation Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Delivery Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>eNett Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
                <default>true</default>
                <label>VANs</label>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Virtual Terminal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TESTtaskupdateticketANDTicketupdateOpp.cls
@isTest
public class TESTtaskupdateticketANDTicketupdateOpp  {
    static testMethod void runTESTtaskupdateticketANDTicketupdateOpp() {
        
        Datetime dt = DateTime.parse('10/10/2014 12:00 AM');

        Account testaccount = new Account(Name = 'Account Test', Legal_Name__c = 'Account Test', Client_Status__c = 'Prospect', IntegratorModifiedDate__c = system.now(), IsApi__c = true, Due_Diligence_Completed__c = dt);
        insert testaccount;
        
        Contact contactperson = new Contact(FirstName = 'Firsttest', LastName = 'Lastest', AccountId = testaccount.id , IsApi__c = true);
        insert contactperson ;
        
        Datetime ddt = testaccount.Due_Diligence_Completed__c;
        Date DueDiligenceDate = ddt.date();

        Opportunity Opp1 = new Opportunity(Name= 'Test Opp', AccountId = testaccount.id , Product__c = 'VANs', Type = 'New', CloseDate = date.valueOf('2014-01-01'), StageName = '1. Prospect', CurrencyIsoCode = 'USD', Primary_Implementation_Contact__c =contactperson.Id, Delivery_Type__c = null);
        /*insert Opp1;
        
        Case DeliveryTicket = new Case(AccountId = testaccount.id, Subject = Opp1.name, Related_Delivery_Opportunity__c = Opp1.id, ContactId = contactperson.Id , Status = 'Active', Priority = 'Not None');
        insert DeliveryTicket;
        
        Case_Field_Update__c fieldUpdateRecord = new Case_Field_Update__c(Name = '01290000000iEI4AAM', Field_Name__c = 'Pre_Kick_off_Questionnaire_Sent__c', Task_recordtype_name__c = 'API_Delivery_Introductory_Email');
        insert fieldUpdateRecord;
        
        Opp1.Delivery_Type__c = 'Delivery - Desktop';
        //update Opp1;
        
        Opp1.Delivery_Type__c = 'Delivery - API';
        //update Opp1;
        
        
        Task t1 = new Task(WhatId = DeliveryTicket.id, Subject = 'API Delivery - Send Pre Kick-off Questionnaire', Status = 'In Progress', Related_Account__c = testaccount.Name, Delivery_Phase__c = DeliveryTicket.Delivery_Phase__c, Delivery_Type__c = DeliveryTicket.Delivery_Type__c );
        insert t1;
        //System.AssertEquals('01290000000iEI4AAM', t1.RecordTypeId);
        System.AssertEquals(t1.Delivery_Phase__c,DeliveryTicket.Delivery_Phase__c);
        System.AssertEquals(t1.Related_Account__c,testaccount.Name);
        System.AssertEquals(t1.Delivery_Type__c , DeliveryTicket.Delivery_Type__c);
        
        
        DeliveryTicket.Enter_NDA_Developer_License_Signed_Date__c = Date.parse('22/01/2015');
        update DeliveryTicket;
        
        Opp1.Delivery_NDA_Signed_Date__c = Date.parse('22/01/2015');
        System.AssertEquals(DeliveryTicket.Enter_NDA_Developer_License_Signed_Date__c, Opp1.Delivery_NDA_Signed_Date__c);
        
        Id testtask1RecordTypeId = t1.RecordTypeId;
        //System.AssertEquals(testtask1RecordTypeId, '01290000000iEI4AAM');
        
        t1.Estimated_Effort_Minutes__c = 5;
        t1.Status = 'Completed';*/
        //update t1;
                
        }
}