force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Automatically populated. This field is only populated for accounts which are activated in client database.</inlineHelpText>
    <label>ECN</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hidden_CC_Address__c.field-meta.xml
<CustomField>
    <fullName>Hidden_CC_Address__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <label>Hidden CC Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hidden_Refresh_area__c.field-meta.xml
<CustomField>
    <fullName>Hidden_Refresh_area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Hidden Refresh area</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Status_Change__c.field-meta.xml
<CustomField>
    <fullName>Last_Status_Change__c</fullName>
    <description>Stores the last time the status changed -- used by the Case Business Hours Tools package.</description>
    <label>Last Status Change</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Trading_As__c.field-meta.xml
<CustomField>
    <fullName>Trading_As__c</fullName>
    <formula>Account.Trading_As__c</formula>
    <label>Trading As</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>hey you there stop that.</description>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Stop_Status__c/Stop_Status__c.object-meta.xml
<CustomObject>
    <description>A case status in which the &quot;clock should stop,&quot; i.e. time calculated in business hours should not be added to the &quot;Time With Support&quot; field.</description>
    <label>Stop Status</label>
    <nameField>
        <label>Stop Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stop Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TEST_CaseComments.cls
@istest
public with sharing class TEST_CaseComments {
    public static testMethod void testCaseCommentsDelete() {

		Profile p = [SELECT Id FROM Profile WHERE Name='Stefanini Service Desk User']; 
		User u = new User(Alias = 'CC', Email='casecomment@enett.com', EmailEncodingKey='UTF-8', LastName='Comment', LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', UserName='casecomment@enett.com'); 

		System.runAs(u) {

	        Account account = new Account(Name = 'eNett Service Desk TEST 1', Legal_Name__c = 'eNett Service Desk TEST 1', Trading_As__c = 'eNett Service Desk TEST 1', ECN__c = '000001', Client_Status__c = 'Prospect', IsApi__c = true);
	        insert account;
	        Contact contact = new Contact(FirstName = 'Enetts', LastName = 'Contacts', Account = [select id from Account where Account.Name = 'eNett Service Desk TEST 1'], IsApi__c = true);
	        insert contact;        
	        
	        Stop_Status__c ss = new Stop_Status__c(Name = 'Pending');
	        insert ss;

	        Case c = new Case();
	        c.Contact = [select id from contact where FirstName = 'Enetts' and LastName = 'Contacts'];
	        c.Status = 'Open';
	        c.Last_Status_Change__c = System.Now();
	        c.Hidden_Refresh_area__c = 1;
	        c.Hidden_CC_Address__c = 'benchen70@gmail.com; internalservice@enett.com';
	        c.Priority = 'Critical';
	        insert c;


	        casecomment ccom = new casecomment ();
	        ccom.commentBody = 'This is a Case Comment.';
	        ccom.parentid = c.id;
	        insert ccom;
	        

	        try {
	        	ccom.CommentBody = 'Changed the Description 1';
	        	update ccom;
	        }
	        catch (Exception e) {
	            Boolean exceptionThrown = e.getMessage().contains('Editing Ticket Comments is not permitted.')? true : false;
	            System.assertEquals(exceptionThrown, true);
	        }
	 

	        try {
	        	delete ccom;
	        }
	        catch (Exception e) {            
	            Boolean exceptionThrown = e.getMessage().contains('Deletion of Ticket Comments is not permitted.')? true : false;
	            System.assertEquals(exceptionThrown, true);
	        }   

		}
    }

}