force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Automatically populated. This field is only populated for accounts which are activated in client database.</inlineHelpText>
    <label>ECN</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Age_In_Business_Hours__c.field-meta.xml
<CustomField>
    <fullName>Case_Age_In_Business_Hours__c</fullName>
    <description>The total case age in business hours from open to close.</description>
    <inlineHelpText>The total case age in business hours from open to close.</inlineHelpText>
    <label>Case Age - Region Support Business Hours</label>
    <precision>16</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hidden_CC_Address__c.field-meta.xml
<CustomField>
    <fullName>Hidden_CC_Address__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <label>Hidden CC Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hidden_Refresh_area__c.field-meta.xml
<CustomField>
    <fullName>Hidden_Refresh_area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Hidden Refresh area</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Last_Status_Change__c.field-meta.xml
<CustomField>
    <fullName>Last_Status_Change__c</fullName>
    <description>Stores the last time the status changed -- used by the Case Business Hours Tools package.</description>
    <label>Last Status Change</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Time_With_Customer__c.field-meta.xml
<CustomField>
    <fullName>Time_With_Customer__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The time in business hours that this case spent in the hands of the customer.</description>
    <inlineHelpText>The time in business hours that this case spent in the hands of the customer.</inlineHelpText>
    <label>Time With Customer</label>
    <precision>16</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Time_With_Support__c.field-meta.xml
<CustomField>
    <fullName>Time_With_Support__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The time in business hours that this case spent with support.</description>
    <inlineHelpText>The time in business hours that this case spent with support.</inlineHelpText>
    <label>Time With Support</label>
    <precision>16</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Trading_As__c.field-meta.xml
<CustomField>
    <fullName>Trading_As__c</fullName>
    <formula>Account.Trading_As__c</formula>
    <label>Trading As</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>hey you there stop that.</description>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Stop_Status__c/Stop_Status__c.object-meta.xml
<CustomObject>
    <description>A case status in which the &quot;clock should stop,&quot; i.e. time calculated in business hours should not be added to the &quot;Time With Support&quot; field.</description>
    <label>Stop Status</label>
    <nameField>
        <label>Stop Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stop Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CalculateBusinessHoursAgesTest.cls
@istest
public class CalculateBusinessHoursAgesTest {
    public static testMethod void testBusinessHoursBucketer() {

        Account account = new Account(Name = 'eNett Service Desk TEST 1', Legal_Name__c = 'eNett Service Desk TEST 1', Trading_As__c = 'eNett Service Desk TEST 1', ECN__c = '000001', Client_Status__c = 'Prospect', IsApi__c = true);
        insert account;
        Contact contact = new Contact(FirstName = 'Enetts', LastName = 'Contacts', Account = [select id from Account where Account.Name = 'eNett Service Desk TEST 1'], IsApi__c = true);
        insert contact;        
        
        Stop_Status__c ss = new Stop_Status__c(Name = 'Pending');
        insert ss;
        

        
        Case c = new Case();
        c.Contact = [select id from contact where FirstName = 'Enetts' and LastName = 'Contacts'];
        c.Status = 'Open';
        c.Last_Status_Change__c = System.Now();
        c.Hidden_Refresh_area__c = 1;
        c.Hidden_CC_Address__c = 'benchen70@gmail.com; internalservice@enett.com';
        c.Priority = 'Critical';
        insert c;
        
        Solution sol = new Solution(SolutionName = 'Thank you for your ticket', SolutionNote = 'Good bye');
        insert sol;

        c.Status = 'Pending';
        Decimal z = c.Hidden_Refresh_area__c;
        c.Hidden_Refresh_area__c = z + 1;
        c.Hidden_CC_Address__c = 'benchen70@gmail.com; benchen70@outlook.com; internalservice@enett.com';
        update c;
        
        CaseSolution cs = new CaseSolution(CaseId = c.id, SolutionId = sol.id);
        insert cs;

        c.Status = 'Open';
        Decimal y = c.Hidden_Refresh_area__c;
        c.Hidden_Refresh_area__c = y + 1;
        c.Hidden_CC_Address__c = 'benchen70@gmail.com; benchen70@outlook.com; rod.crociani@hotmail.com; internalservice@enett.com';
        update c;

        System.assertNotEquals(c.Time_With_Customer__c,0);
        System.assertNotEquals(c.Time_With_Support__c,0);
        System.assertEquals(c.Case_Age_In_Business_Hours__c,null);
        

        c.Status = 'Pending';
        Decimal x = c.Hidden_Refresh_area__c;
        c.Hidden_Refresh_area__c = x + 1;
        c.Hidden_CC_Address__c = 'benchen70@gmail.com; benchen70@outlook.com; rod.crociani@hotmail.com; canyoucatchme1@gmail.com; internalservice@enett.com';
        update c;

        System.assertNotEquals(c.Time_With_Customer__c,0);
        System.assertNotEquals(c.Time_With_Support__c,0);
       

    }
}