force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>This field is used by the Salesforce integrator and should not be modified unless you understand the data-flow consequences</description>
    <inlineHelpText>WARNING This field is used by the Salesforce integrator.</inlineHelpText>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Account Changes</fullName>
            </value>
            <value>
                <fullName>Activations</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Browser Issue</fullName>
            </value>
            <value>
                <fullName>Client Report</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Delivery/Implementation</fullName>
            </value>
            <value>
                <fullName>Dropped Call</fullName>
            </value>
            <value>
                <fullName>EFT Account Changes</fullName>
            </value>
            <value>
                <fullName>EFT Payment Processing</fullName>
            </value>
            <value>
                <fullName>EFT Refunds</fullName>
            </value>
            <value>
                <fullName>EFT Training Request</fullName>
            </value>
            <value>
                <fullName>ePP</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>FreeNett Payment Processing</fullName>
            </value>
            <value>
                <fullName>Gateway Payment Processing</fullName>
            </value>
            <value>
                <fullName>Gateway Payment Status</fullName>
            </value>
            <value>
                <fullName>Gateway Refund</fullName>
            </value>
            <value>
                <fullName>Gateway Reporting</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Issues</fullName>
            </value>
            <value>
                <fullName>JIRA</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>New Request</fullName>
            </value>
            <value>
                <fullName>Notification</fullName>
            </value>
            <value>
                <fullName>Offboarding</fullName>
            </value>
            <value>
                <fullName>Outage</fullName>
            </value>
            <value>
                <fullName>Password</fullName>
            </value>
            <value>
                <fullName>Payment Status</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Product Request</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Abandon Registration</fullName>
            </value>
            <value>
                <fullName>Account Suspension</fullName>
            </value>
            <value>
                <fullName>Actual Chargeback</fullName>
            </value>
            <value>
                <fullName>Add Email</fullName>
            </value>
            <value>
                <fullName>Add Email Address</fullName>
            </value>
            <value>
                <fullName>Add FeeNett product</fullName>
            </value>
            <value>
                <fullName>Add new Currency</fullName>
            </value>
            <value>
                <fullName>Ad-Hoc</fullName>
            </value>
            <value>
                <fullName>Amend Customised Reports</fullName>
            </value>
            <value>
                <fullName>Amend Limits</fullName>
            </value>
            <value>
                <fullName>Amend Merchant Name</fullName>
            </value>
            <value>
                <fullName>Amend Report Subscription</fullName>
            </value>
            <value>
                <fullName>Amend VAN Issue</fullName>
            </value>
            <value>
                <fullName>API Configuration</fullName>
            </value>
            <value>
                <fullName>API Investigation</fullName>
            </value>
            <value>
                <fullName>Authorisation Cancellation</fullName>
            </value>
            <value>
                <fullName>Bank Account (DDR)</fullName>
            </value>
            <value>
                <fullName>Bank Fax - Auth Reversal</fullName>
            </value>
            <value>
                <fullName>Bank Fax - Auth Verification</fullName>
            </value>
            <value>
                <fullName>Banking</fullName>
            </value>
            <value>
                <fullName>Bank Query- Code Cancelation</fullName>
            </value>
            <value>
                <fullName>Bank Query- Confirm Transaction</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Business Details</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Cancel VAN issue</fullName>
            </value>
            <value>
                <fullName>Certificate Change</fullName>
            </value>
            <value>
                <fullName>Change</fullName>
            </value>
            <value>
                <fullName>Change Email Address</fullName>
            </value>
            <value>
                <fullName>Change Report Subscription</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Query</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Hidden_CC_Address__c.field-meta.xml
<CustomField>
    <fullName>Hidden_CC_Address__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <label>Hidden CC Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hidden_Refresh_area__c.field-meta.xml
<CustomField>
    <fullName>Hidden_Refresh_area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Hidden Refresh area</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agoda Pro Portal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>eNett Gateway</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>No eNett Product</fullName>
            </value>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>VANs Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>No. Just don&#39;t.</description>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>hey you there stop that.</description>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Stop_Status__c/Stop_Status__c.object-meta.xml
<CustomObject>
    <description>A case status in which the &quot;clock should stop,&quot; i.e. time calculated in business hours should not be added to the &quot;Time With Support&quot; field.</description>
    <label>Stop Status</label>
    <nameField>
        <label>Stop Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stop Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TESTFirstResponsetimeforKPITimerforTask.cls
@isTest 
private class TESTFirstResponsetimeforKPITimerforTask{
    static testMethod void TestFirstResponsetimeforTask() {
    
     Account account = new Account(Name = 'Account Test', Legal_Name__c = 'Account Test', Client_Status__c = 'Prospect', IntegratorModifiedDate__c = system.now(), IsApi__c = true);
     insert account;
     Contact contact = new Contact(FirstName = 'Test', LastName = 'Test', Account = [select id from Account where Account.Name = 'Account Test'], IsApi__c = true);
     insert contact;
     Stop_Status__c ss = new Stop_Status__c(Name = 'Pending');
     insert ss; 
     
     BusinessHours LondonHours = [select Id from BusinessHours where Name = 'London' ];
     Id LondonHoursid = LondonHours.Id;
        
     Case c = new Case (Account = [select id from Account where Name = 'Account Test'], Contact = [select id from Contact where FirstName = 'Test' and LastName = 'Test'], Status = 'Open', Origin = 'Call', Type = 'Problem', Product__c = 'VANs', Category__c = 'VANs', Description__c = 'Query', Subject = 'New problem to solve for helpdesk', Priority = 'Critical', Hidden_Refresh_area__c = 1, Hidden_CC_Address__c = 'benchen70@gmail.com; internalservice@enett.com ', BusinessHoursId = LondonHoursid );
        
     insert c; 
     Id ticketId = c.Id;
     system.Debug('he ticketid is ' + ticketId); 
     
     Task t = new Task (WhatId = ticketId, Subject = 'Email', OwnerId = '00590000000riL4', Type = 'Email', Status = 'Completed', Priority = 'Normal');
     System.Debug('this what Id umber for ticket is now ' + t.whatId);
     insert t;
     
     }
     }