force-app/main/default/objects/Account/fields/Client_internal_classification__c.field-meta.xml
<CustomField>
    <fullName>Client_internal_classification__c</fullName>
    <description>Total Company GDV  This field was previously a picklist type (Referrer, TTV &lt;$50m, TTV $50m - $1b, TTV &gt;$1b).</description>
    <inlineHelpText>Please enter the classification as a whole numerical value.  Abbreviated values are permitted (B - Billion, M - Million, K - Thousand) Eg 1M - Will automatically be converted to 1,000,000.</inlineHelpText>
    <label>Total GDV p.a.</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>DD Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>This field is used by the Salesforce integrator and should not be modified unless you understand the data-flow consequences</description>
    <inlineHelpText>WARNING This field is used by the Salesforce integrator.</inlineHelpText>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <inlineHelpText>This field will display the Delivery Type that is selected in the related Opportunity.</inlineHelpText>
    <label>Delivery Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Estimated_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Completion_Date__c</fullName>
    <inlineHelpText>This is the date that the delivery owner has estimated to complete the delivery.</inlineHelpText>
    <label>Estimated Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Justification_of_Change_to_Date__c.field-meta.xml
<CustomField>
    <fullName>Justification_of_Change_to_Date__c</fullName>
    <label>Justification of Change to Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agoda Pro Portal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>eNett Gateway</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>No eNett Product</fullName>
            </value>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>VANs Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Related_Delivery_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Delivery_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Delivery Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Phase Tickets</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IntegratorModifiedDate__c.field-meta.xml
<CustomField>
    <fullName>IntegratorModifiedDate__c</fullName>
    <description>No. Just don&#39;t.</description>
    <label>IntegratorModifiedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>hey you there stop that.</description>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Delivery_type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Delivery - Desktop</fullName>
            </value>
            <value>
                <fullName>Delivery - API</fullName>
            </value>
            <value>
                <fullName>Delivery Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>Account Completed DD</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Estimated_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Completion_Date__c</fullName>
    <inlineHelpText>This is the date that the delivery owner has forecast for the completion of the delivery.</inlineHelpText>
    <label>Estimated Completion Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Implementation_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Implementation_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Implementation Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Delivery Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>eNett Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
                <default>true</default>
                <label>VANs</label>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Virtual Terminal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestValidateCaseCompletionDate.cls
/*
Author: Paul Swarnapandian
Last Updated: 11/05/2015
Company: SMS M&T

*/

@isTest
public class TestValidateCaseCompletionDate {

    static testMethod void testUpdate(){
       setUpTestData();
    }
     public static void setUpTestData(){
        
        Datetime dt = DateTime.parse('10/10/2014 12:00 AM');
        Account testaccount = new Account(Name = 'Account Test', Legal_Name__c = 'Account Test', 
        Client_Status__c = 'Prospect', IntegratorModifiedDate__c = system.now(), IsApi__c = true, Due_Diligence_Completed__c = dt);//, Client_internal_classification__c = 100000.00 );
        insert testaccount;
        
        Contact contactperson = new Contact(FirstName = 'Firsttest', LastName = 'Lastest', AccountId = testaccount.id, IsApi__c = true);
        insert contactperson ;
        
        /*Opportunity Opp = new Opportunity(Name= 'Test Opp', AccountId = testaccount.id, Product__c = 'VANs', 
        Type = 'New', CloseDate = date.valueOf('2014-01-01'), 
        StageName = '1. Prospect', CurrencyIsoCode = 'USD', Primary_Implementation_Contact__c = contactperson.Id, 
        Delivery_Type__c = 'Delivery - Desktop', Region__c= 'Americas');
        insert Opp;
        
        Case tkt = new Case (Subject = 'Delivery - ' + Opp.Name, Status = 'Active', AccountId = testaccount.id, Priority = 'Not None',
        ContactId = contactperson.Id, Related_Delivery_Opportunity__c = Opp.Id, Estimated_Completion_Date__c = System.Today() - 1);
        insert tkt;
        
        Task task = new Task (Subject = 'Delivery Estimated Completion Date', Status = 'Not Started', 
        Priority = 'High', Type = 'Task', WhatId = tkt.id, ActivityDate = System.Today()+2);
        insert task;
        
        tkt.Estimated_Completion_Date__c = System.Today() + 1;
        tkt.Justification_of_Change_to_Date__c = 'Test Validate Case Completion Date';
        
        update tkt;
        
        task.Estimated_Effort_Minutes__c = 2;
        task.Status = 'Completed';
        System.debug('The id is ' + task.WhatId);
        System.debug('The Case id is ' + tkt.id);*/
        
        // This is to test the Desktop Training Seession Event Task
        /*Task trainingTask = new Task (Subject = 'Desktop Delivery - Create Desktop Training Session Event', Status = 'Not Started', 
        Priority = 'High', Type = 'Task', WhatId = tkt.id, ActivityDate = System.Today()+2);
        insert trainingTask ;
        trainingTask.status = 'Completed';
        
        // This is to test the Desktop Delivery - Confirm date of Funding Task
        Task fundingTask = new Task (Subject = 'Desktop Delivery - Confirm date of Funding Task', Status = 'Not Started', 
        Priority = 'High', Type = 'Task', WhatId = tkt.id, ActivityDate = System.Today()+2);
        insert fundingTask;
        fundingTask.status = 'Completed';
        
         // This is to test the API Delivery - Send Demo API ECN details Test Scenario and VANs Setting Quest
        Task demoAPITask = new Task (Subject = 'API Delivery - Send Demo API ECN details Test Scenario and VANs Setting Quest', Status = 'Not Started', 
        Priority = 'High', Type = 'Task', WhatId = tkt.id, ActivityDate = System.Today()+2);
        insert demoAPITask;
        demoAPITask.status = 'Completed';
        
         // This is to test the API Del Delivery Completed
        Task delCompletedTask = new Task (Subject = 'API Del Delivery Completed', Status = 'Not Started', 
        Priority = 'High', Type = 'Task', WhatId = tkt.id, ActivityDate = System.Today()+2);
        insert delCompletedTask;
        delCompletedTask.status = 'Completed';
        
        
        // This is to test the API Delivery - Reporting Training Session Task
        Task reportTask = new Task (Subject = 'API Del Delivery Completed', Status = 'Not Started', 
        Priority = 'High', Type = 'Task', WhatId = tkt.id, ActivityDate = System.Today()+2);
        insert reportTask;
        reportTask.status = 'Completed';
        

        // This is to test the API Delivery - UAT Testing Checkpoint Task
        Task uatTask = new Task (Subject = 'API Delivery - UAT Testing Checkpoint Task', Status = 'Not Started', 
        Priority = 'High', Type = 'Task', WhatId = tkt.id, ActivityDate = System.Today()+2);
        insert uatTask;
        uatTask.status = 'Completed';
        
        // This is to test the API Delivery - Enter all Milestone Projected Values
        Task milestoneTask = new Task (Subject = 'API Delivery - Enter all Milestone Projected Values', Status = 'Not Started', 
        Priority = 'High', Type = 'Task', WhatId = tkt.id, ActivityDate = System.Today()+2);
        insert milestoneTask;
        milestoneTask.status = 'Completed';*/
        
        // This is to test the API Delivery - Confirm Completion of All Stages of Delivery
        /*Task allStagesTask = new Task (Subject = 'API Delivery - Confirm Completion of All Stages of Delivery', Status = 'Not Started', 
        Priority = 'High', Type = 'Task', WhatId = tkt.id, ActivityDate = System.Today()+2);
        insert allStagesTask;
        allStagesTask.status = 'Completed';
        
        try{
        update task;*/
        /*update fundingTask;
        update trainingTask;
        update demoAPITask;
        update delCompletedTask;
        update reportTask;
        update uatTask;
        update milestoneTask;*/
        //update allStagesTask;
        //System.debug('The case date is ' + tkt.Estimated_Completion_Date__c);
        //}
        //catch (Exception e){
        //    System.debug ('The error is ' + e.getMessage());
        //}
        
    }
    

}