force-app/main/default/objects/Account/fields/Client_internal_classification__c.field-meta.xml
<CustomField>
    <fullName>Client_internal_classification__c</fullName>
    <description>Total Company GDV  This field was previously a picklist type (Referrer, TTV &lt;$50m, TTV $50m - $1b, TTV &gt;$1b).</description>
    <inlineHelpText>Please enter the classification as a whole numerical value.  Abbreviated values are permitted (B - Billion, M - Million, K - Thousand) Eg 1M - Will automatically be converted to 1,000,000.</inlineHelpText>
    <label>Total GDV p.a.</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Client_Status__c.field-meta.xml
<CustomField>
    <fullName>Client_Status__c</fullName>
    <label>Client Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Registration in progress</fullName>
            </value>
            <value>
                <fullName>Due diligence in progress</fullName>
            </value>
            <value>
                <fullName>Contract in progress</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>DD Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <inlineHelpText>Automatically populated based on the Registered business name.</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/API_Delivery_Category__c.field-meta.xml
<CustomField>
    <fullName>API_Delivery_Category__c</fullName>
    <label>API Delivery Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>API - API Integration Remote</fullName>
                <default>true</default>
                <label>API - API Integration Remote</label>
            </value>
            <value>
                <fullName>API - Complex Large Business Onsite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Delivery_Category__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Category__c</fullName>
    <label>Delivery Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Desktop - Low Touch Self Sufficient</fullName>
            </value>
            <value>
                <fullName>Desktop - High Touch Training / Consultation</fullName>
            </value>
            <value>
                <fullName>API - API Integration Remote</fullName>
            </value>
            <value>
                <fullName>API - Complex Large Business Onsite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Delivery_Category_Benchmark_Days__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Category_Benchmark_Days__c</fullName>
    <label>Delivery Category Benchmark Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Delivery_Phase__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Phase__c</fullName>
    <label>Delivery Phase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 - Pre-Implementation Kick-off</fullName>
            </value>
            <value>
                <fullName>1 - Set Up and Configuration</fullName>
            </value>
            <value>
                <fullName>2 - VAN Training</fullName>
            </value>
            <value>
                <fullName>3 - Funding</fullName>
            </value>
            <value>
                <fullName>4 - VAN Reporting and Reconciliation</fullName>
            </value>
            <value>
                <fullName>1 - Planning &amp; Preparation</fullName>
            </value>
            <value>
                <fullName>2 - Development ( API integration)</fullName>
            </value>
            <value>
                <fullName>3 - UAT</fullName>
            </value>
            <value>
                <fullName>4 - Live testing</fullName>
            </value>
            <value>
                <fullName>5 - Production cut over</fullName>
            </value>
            <value>
                <fullName>Unassigned Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <inlineHelpText>This field will display the Delivery Type that is selected in the related Opportunity.</inlineHelpText>
    <label>Delivery Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Phase_3_Notes__c.field-meta.xml
<CustomField>
    <fullName>Phase_3_Notes__c</fullName>
    <label>Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agoda Pro Portal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>eNett Gateway</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>No eNett Product</fullName>
            </value>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>VANs Billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Related_Delivery_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Delivery_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Delivery Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Delivery Phase Tickets</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>hey you there stop that.</description>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Delivery_Category_Benchmarks__c/Delivery_Category_Benchmarks__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Delivery Category Benchmarks</label>
</CustomObject>

force-app/main/default/objects/Delivery_Category_Benchmarks__c/fields/Days__c.field-meta.xml
<CustomField>
    <fullName>Days__c</fullName>
    <label>Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery_Category_Benchmarks__c/fields/Delivery_Category__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Category__c</fullName>
    <label>Delivery Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/attainable_ttv_monthly__c.field-meta.xml
<CustomField>
    <fullName>attainable_ttv_monthly__c</fullName>
    <label>Attainable GDV (monthly)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Category_Benchmark_Days__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Category_Benchmark_Days__c</fullName>
    <label>Delivery Category Benchmark Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Phase__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Phase__c</fullName>
    <label>Delivery Phase</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Delivery - Desktop</fullName>
            </value>
            <value>
                <fullName>Delivery - API</fullName>
            </value>
            <value>
                <fullName>Delivery Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Due_Diligence_Completed__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Completed__c</fullName>
    <label>Account Completed DD</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GDV_Change_Justification__c.field-meta.xml
<CustomField>
    <fullName>GDV_Change_Justification__c</fullName>
    <label>GDV Change Justification</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Implementation_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Implementation_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Implementation Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Delivery Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>eNett Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
                <default>true</default>
                <label>VANs</label>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>Virtual Terminal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TESTCheckExistingDeliveryTicketsFour.cls
@isTest(SeeAllData=true)
private class TESTCheckExistingDeliveryTicketsFour {
    static testMethod void runTestCheckExistingDeliveryTicketsFour () {
    
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator (no expiry)']; 
        UserRole r = [SELECT Id FROM UserRole WHERE Name = 'Global Service Desk Level 2'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='Australia/Sydney', UserName='z@testorg.com', UserRoleId = r.Id);
      
        System.runAs(u){

            Datetime dt = DateTime.parse('10/10/2014 12:00 AM');
            Date dtDate = dt.Date();
            Date contractenddate = date.valueOf('2014-01-01');
            
            Delivery_Category_Benchmarks__c deliverybenchmark = new Delivery_Category_Benchmarks__c(Name = 'Desktop - Low', Delivery_Category__c  = 'Desktop - Low Touch Self Sufficient', Days__c = 20);
            insert deliverybenchmark;
            Delivery_Category_Benchmarks__c deliverybenchmark1 = new Delivery_Category_Benchmarks__c(Name = 'API - Remote', Delivery_Category__c  = 'API - API Integration Remote', Days__c = 35);
            insert deliverybenchmark1;
            Delivery_Category_Benchmarks__c deliverybenchmark2 = new Delivery_Category_Benchmarks__c(Name = 'Desktop - High', Delivery_Category__c  = 'Desktop - High Touch Training / Consultation', Days__c = 45);
            insert deliverybenchmark2;
            Delivery_Category_Benchmarks__c deliverybenchmark3 = new Delivery_Category_Benchmarks__c(Name = 'API - Complex', Delivery_Category__c  = 'API - Complex Large Business Onsite', Days__c = 70);
            insert deliverybenchmark3;
     
     
    // third  account - DD NOT completed
            Account testaccount = new Account(Name = 'Account Test', Legal_Name__c = 'Account Test', Client_Status__c = 'Prospect', IsApi__c = true, Due_Diligence_Completed__c = null);//, Client_internal_classification__c = 1000.00);
            insert testaccount;
            id testaccountid = testaccount.id;
            Contact contactperson = new Contact(FirstName = 'Firsttest', LastName = 'Lastest', AccountId = testaccount.id , IsApi__c = true);
            insert contactperson ;
            id contactpersonId = contactperson.Id;
            
    // opportunity - Delivery type API - then completed DD
            
            Opportunity Opp1 = new Opportunity(Name= 'Test Opp1', AccountId = testaccount.id , Product__c = 'VANs', Type = 'New',  CloseDate = contractenddate, StageName = '1. Prospect', CurrencyIsoCode = 'USD', Primary_Implementation_Contact__c =contactperson.Id, Delivery_Type__c = 'Delivery - API');//, attainable_ttv_monthly__c = 1, GDV_Change_Justification__c = '');
            insert Opp1;
            
          //  Opp1.attainable_ttv_monthly__c = 2;
           // Opp1.GDV_Change_Justification__c = 'reason alive';
            //update Opp1;
    
            Case DeliveryTicket1 = new Case(AccountId = testaccount.id, Subject = Opp1.name, Related_Delivery_Opportunity__c = Opp1.id, ContactId = contactperson.Id , Status = 'Active', Delivery_Phase__c = '0 - Pre-Implementation Kick-off', RecordTypeId = '01290000000iE8V', Delivery_Category__c = deliverybenchmark1.Delivery_Category__c, Delivery_Category_Benchmark_Days__c = deliverybenchmark1.Days__c, Delivery_Type__c = Opp1.Delivery_Type__c);
            insert DeliveryTicket1;
            
            testaccount.Due_Diligence_Completed__c = date.valueOf('2014-01-01');
            
            
            DeliveryTicket1.API_Delivery_Category__c = deliverybenchmark3.Delivery_Category__c;
            update DeliveryTicket1;
            
            DeliveryTicket1.Phase_3_Notes__c = 'Morgan Freeman';
            update DeliveryTicket1;
            
            DeliveryTicket1.Phase_3_Notes__c = 'Not  Freeman';
            update DeliveryTicket1;
            
            DeliveryTicket1.Status = 'Pending';
            update  DeliveryTicket1;
            
    //this below tests the ticket deletion
            try{
                Delete DeliveryTicket1;
            }
            catch(System.DmlException ex){
                }
            }
        }
}