force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Åland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
                <default>true</default>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyCode__c</fullName>
    <label>CurrencyCode</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CurrencyName__c.field-meta.xml
<CustomField>
    <fullName>CurrencyName__c</fullName>
    <label>Currency</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_Region_2__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region_2__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>Second level sub region for the country</description>
    <inlineHelpText>Second level sub region for the country</inlineHelpText>
    <label>Sub Region 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>First level sub region for the country</description>
    <inlineHelpText>First level sub region for the country</inlineHelpText>
    <label>Sub Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/CountryMappings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Country, ISO Code and Region.  Source for data Ref: http://data.okfn.org/data/core/country-codes</description>
    <label>Country</label>
</CustomObject>

force-app/main/default/objects/CountryMappings__c/fields/currency_alphabetic_code__c.field-meta.xml
<CustomField>
    <fullName>currency_alphabetic_code__c</fullName>
    <label>ISO 4217 currency code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/currency_name__c.field-meta.xml
<CustomField>
    <fullName>currency_name__c</fullName>
    <label>ISO 4217 name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/EFT_Subscription_Fee__c.field-meta.xml
<CustomField>
    <fullName>EFT_Subscription_Fee__c</fullName>
    <label>EFT Subscription Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/ISO2__c.field-meta.xml
<CustomField>
    <fullName>ISO2__c</fullName>
    <externalId>true</externalId>
    <label>ISO2</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/ISO3__c.field-meta.xml
<CustomField>
    <fullName>ISO3__c</fullName>
    <externalId>true</externalId>
    <label>ISO3</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/Sub_Region_2__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region_2__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>The second-level of sub region for the country</description>
    <inlineHelpText>The second-level of sub region for the country</inlineHelpText>
    <label>Sub Region 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>First-level sub region for the country</description>
    <inlineHelpText>First-level sub region for the country</inlineHelpText>
    <label>Sub Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Bus Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/EFT_Subscription_Fee__c.field-meta.xml
<CustomField>
    <fullName>EFT_Subscription_Fee__c</fullName>
    <description>The monthly price the customer will pay for EFT</description>
    <label>EFT Subscription Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Sub_Region_2__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region_2__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>Second level sub region for the country</description>
    <inlineHelpText>Second level sub region for the country</inlineHelpText>
    <label>Sub Region 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>First level sub region for the country</description>
    <inlineHelpText>First level sub region for the country</inlineHelpText>
    <label>Sub Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius, Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/StaticUtilsTest.cls
@isTest (SeeAllData = true)
public class StaticUtilsTest {
    //Null object should return null or object without country as a field
    @isTest static void TestNull(){
        StaticUtils.PopulateCountryFields(null);
        //Case object doesn't have country as a field
        Case c = new Case();
        StaticUtils.PopulateCountryFields(c);
    }

    //Object with country as a field but no value or an invalid country name in it 
    @isTest static void TestWrongCountry(){
        Registration__c r = new Registration__c(Country__c = 'Utopia',Region__c = 'EMEA',EFT_Subscription_Fee__c=123);
        StaticUtils.PopulateCountryFields(r);
        System.AssertEquals('EMEA',r.Region__c,'Object country-related info got updated even though the country name is invalid');
    }
    
    //Happy Path 1
    @isTest static void TestHappyPathCountryFields(){
        //get custom settings
        Account acc = new Account(Country__c = 'Australia');
        CountryMappings__c info = CountryMappings__c.getInstance((string)acc.get('Country__c'));
        String iso2 = info.ISO2__c, iso3 = info.ISO3__c, currencyName = info.currency_name__c, currencyCode = info.currency_alphabetic_code__c,
            region = info.Region__c, subRegion = info.Sub_Region__c, subRegion2 = info.Sub_Region_2__c;
        //do the deed
        StaticUtils.PopulateCountryFields(acc);
		//check the fields are updated
		System.AssertEquals(iso2,acc.CountryCode2__c);
        System.AssertEquals(iso3,acc.CountryCode3__c);
        System.AssertEquals(currencyName,acc.CurrencyName__c);
        System.AssertEquals(currencyCode,acc.CurrencyCode__c);
        System.AssertEquals(region,acc.Region__c);
        System.AssertEquals(subRegion,acc.Sub_Region__c);
        System.AssertEquals(subRegion2,acc.Sub_Region_2__c);
    }
}