force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Åland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
                <default>true</default>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CurrencyCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyCode__c</fullName>
    <label>CurrencyCode</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CurrencyName__c.field-meta.xml
<CustomField>
    <fullName>CurrencyName__c</fullName>
    <label>Currency</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Standard_TCs_Template_EFT__c.field-meta.xml
<CustomField>
    <fullName>Standard_TCs_Template_EFT__c</fullName>
    <formula>Reference_Registration__r.Standard_TCs_Template_EFT__c</formula>
    <label>Standard TCs Template EFT</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Standard_TCs_Template_VANs__c.field-meta.xml
<CustomField>
    <fullName>Standard_TCs_Template_VANs__c</fullName>
    <formula>Reference_Registration__r.Standard_TCs_template_VANs__c</formula>
    <label>Standard TCs Template VANs</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_Region_2__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region_2__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>Second level sub region for the country</description>
    <inlineHelpText>Second level sub region for the country</inlineHelpText>
    <label>Sub Region 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>First level sub region for the country</description>
    <inlineHelpText>First level sub region for the country</inlineHelpText>
    <label>Sub Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/CountryMappings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Country, ISO Code and Region.  Source for data Ref: http://data.okfn.org/data/core/country-codes</description>
    <label>Country</label>
</CustomObject>

force-app/main/default/objects/CountryMappings__c/fields/Chargeback_Fee_With_Document__c.field-meta.xml
<CustomField>
    <fullName>Chargeback_Fee_With_Document__c</fullName>
    <label>Chargeback Fee With Document</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/currency_alphabetic_code__c.field-meta.xml
<CustomField>
    <fullName>currency_alphabetic_code__c</fullName>
    <label>ISO 4217 currency code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/currency_name__c.field-meta.xml
<CustomField>
    <fullName>currency_name__c</fullName>
    <label>ISO 4217 name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/EFT_Default_Payment__c.field-meta.xml
<CustomField>
    <fullName>EFT_Default_Payment__c</fullName>
    <label>EFT Default Payment</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/EFT_Subscription_Fee__c.field-meta.xml
<CustomField>
    <fullName>EFT_Subscription_Fee__c</fullName>
    <label>EFT Subscription Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/EFT_Transaction_Fee__c.field-meta.xml
<CustomField>
    <fullName>EFT_Transaction_Fee__c</fullName>
    <label>EFT Transaction Fee</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/eNett_Account_Fee__c.field-meta.xml
<CustomField>
    <fullName>eNett_Account_Fee__c</fullName>
    <inlineHelpText>Replacing eNett Payments Platform Fee (VANs Subscription Fee)</inlineHelpText>
    <label>eNett Account Fee</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/ISO2__c.field-meta.xml
<CustomField>
    <fullName>ISO2__c</fullName>
    <externalId>true</externalId>
    <label>ISO2</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/ISO3__c.field-meta.xml
<CustomField>
    <fullName>ISO3__c</fullName>
    <externalId>true</externalId>
    <label>ISO3</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/Sub_Region_2__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region_2__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>The second-level of sub region for the country</description>
    <inlineHelpText>The second-level of sub region for the country</inlineHelpText>
    <label>Sub Region 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>First-level sub region for the country</description>
    <inlineHelpText>First-level sub region for the country</inlineHelpText>
    <label>Sub Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryMappings__c/fields/VANs_Subscription_Fee__c.field-meta.xml
<CustomField>
    <fullName>VANs_Subscription_Fee__c</fullName>
    <description>Monthly Price of VANs</description>
    <label>VANs Subscription Fee</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Bus Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/EFT_Default_Payment__c.field-meta.xml
<CustomField>
    <fullName>EFT_Default_Payment__c</fullName>
    <label>EFT Default Payment</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/EFT_Subscription_Fee__c.field-meta.xml
<CustomField>
    <fullName>EFT_Subscription_Fee__c</fullName>
    <description>The monthly price the customer will pay for EFT</description>
    <label>EFT Subscription Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/EFT_Transaction_Fee__c.field-meta.xml
<CustomField>
    <fullName>EFT_Transaction_Fee__c</fullName>
    <label>EFT Transaction Fee</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/eNett_Account_Fee__c.field-meta.xml
<CustomField>
    <fullName>eNett_Account_Fee__c</fullName>
    <inlineHelpText>Replacing eNett Payments Platform Fee (VANs Subscription Fee)</inlineHelpText>
    <label>eNett Account Fee</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>VirtualTerminal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Standard_TCs_Template_EFT__c.field-meta.xml
<CustomField>
    <fullName>Standard_TCs_Template_EFT__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Standard TCs Template EFT</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document_Template__c.Product__c</field>
            <operation>equals</operation>
            <value>eNett EFT</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Registrations (Standard TCs Template EFT)</relationshipLabel>
    <relationshipName>Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Standard_TCs_template_VANs__c.field-meta.xml
<CustomField>
    <fullName>Standard_TCs_template_VANs__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Standard TCs Template VANs</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Document_Template__c.Product__c</field>
            <operation>equals</operation>
            <value>VANs</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Sub_Region_2__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region_2__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>Second level sub region for the country</description>
    <inlineHelpText>Second level sub region for the country</inlineHelpText>
    <label>Sub Region 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region__c</fullName>
    <defaultValue>&quot;None&quot;</defaultValue>
    <description>First level sub region for the country</description>
    <inlineHelpText>First level sub region for the country</inlineHelpText>
    <label>Sub Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/VANs_Subscription_Fee__c.field-meta.xml
<CustomField>
    <fullName>VANs_Subscription_Fee__c</fullName>
    <description>The monthly price of VANs for the Customer</description>
    <label>VANs Subscription Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Aland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia, Plurinational State of</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius, Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>New Zealand</fullName>
    </customValue>
    <masterLabel>Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/StaticUtils.cls
public class StaticUtils {
    //this is to populate country related info based on the country list custom setting
    public static void PopulateCountryFields( sObject obj ){
        if (obj != null){
            //don't proceed if the object has no country field
            if(obj.getSobjectType().getDescribe().fields.getMap().keySet().contains('country__c')){
                
                //Surajsingh Thakur : PDS-2913 : Additional EFT ECN automatically assigned incorrect Country - Start
                CountryMappings__c info = NULL;
                
                if((obj instanceOf Account) && ((string)obj.get('Country__c')==NULL || (string)obj.get('Country__c') == '')){
                    List<Account> parents = [Select id, Country__c from Account Where id =:(string)obj.get('ParentId') LIMIT 1];  
                    
                    if(parents.size()>0){
                        Account parent = parents[0];
                        info = CountryMappings__c.getInstance(parent.Country__c); 
                        if(info!=NULL){
                            obj.put('Country__c', info.Name);
                        }
                    }
                }
                
                else if(obj instanceOf Account){
                    if((string)obj.get('Country__c')!=NULL && (string)obj.get('Country__c')!=''){
                        info = CountryMappings__c.getInstance((string)obj.get('Country__c'));
                        if(info!=NULL){
                            obj.put('Country__c', info.Name);
                        }
                    }
                }
                //Surajsingh Thakur : PDS-2913 : Additional EFT ECN automatically assigned incorrect Country - End
                
                //don't proceed if the country name is invalid
                if(info != null){
                    obj.put('CountryCode2__c', info.ISO2__c);
                    obj.put('CountryCode3__c', info.ISO3__c);
                    obj.put('CurrencyName__c', info.currency_name__c);
                    obj.put('CurrencyCode__c', info.currency_alphabetic_code__c);
                    obj.put('Region__c', info.Region__c);
                    obj.put('Sub_Region__c', info.Sub_Region__c);
                    obj.put('Sub_Region_2__c', info.Sub_Region_2__c);}
            }
        }   
    }
    
    //this method is only applicable to Registration__c -- why are we accepting sObject?
    public static void PopulateRegSubscriptionFields(sObject obj, Boolean countryChanged ) {
        String country, products;
        if (obj != null){
            //don't proceed if the object has no country or products field
            if(obj.getSobjectType().getDescribe().fields.getMap().keySet().contains('country__c') &&
               obj.getSobjectType().getDescribe().fields.getMap().keySet().contains('product__c')){
                   country = (string)obj.get('Country__c');
                   products = (string)obj.get('Product__c');
                   CountryMappings__c info = CountryMappings__c.getInstance(country);
                   //don't proceed if the country name is invalid
                   if(info != null){
                       obj.put('Region__c', info.Region__c);
                       obj.put('Sub_Region__c', info.Sub_Region__c);
                       obj.put('Sub_Region_2__c', info.Sub_Region_2__c);
                       obj.put('Standard_TCs_Template_EFT__c', GetStandardTCTemplate.getStandardTCTemplate((country == 'Australia' || country == 'New Zealand') ? country : info.Region__c, 'eNett EFT'));
                       obj.put('Standard_TCs_template_VANs__c', GetStandardTCTemplate.getStandardTCTemplate((country == 'Australia' || country == 'New Zealand') ? country : info.Region__c, 'VANs'));
                       if(countryChanged){
                           //SF-4883 Add condition checking if products is not null to cater for a registration which does not have a product 
                           if(products != null){
                               obj.put('EFT_Subscription_Fee__c', (!products.contains('eNett EFT') || info.EFT_Subscription_Fee__c == 0) ? null : info.EFT_Subscription_Fee__c);
                               obj.put('EFT_Transaction_Fee__c',  (!products.contains('eNett EFT')) ? null : info.EFT_Transaction_Fee__c);
                               obj.put('EFT_Default_Payment__c', (!products.contains('eNett EFT')) ? null : info.EFT_Default_Payment__c);
                               obj.put('VANs_Subscription_Fee__c', (!products.contains('VANs')) ? null : info.VANs_Subscription_Fee__c);
                               obj.put('eNett_Account_Fee__c', (!products.contains('VANs')) ? null : info.eNett_Account_Fee__c);
                               obj.put('Chargeback_Fee_With_Document__c', (!products.contains('VANs')) ? null : info.Chargeback_Fee_With_Document__c);
                               obj.put('Chargeback_Fee_Without_Document__c', (!products.contains('VANs')) ? null : info.Chargeback_Fee_Without_Document__c);
                               obj.put('Subscription_Fee_Currency__c', info.Enett_Default_Currency__c);
                               obj.put('Subscription_Fee_Symbol__c', info.Enett_Default_Currency_Symbol__c);   
                           } 
                       }
                   }
               }
        }   
    }    
}