force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Åland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
                <default>true</default>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Do_Not_Contact__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Once checked a message will appear at the top of the Account page to alert users not to contact this client.</inlineHelpText>
    <label>Do Not Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/CountryMappings__c/CountryMappings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Country, ISO Code and Region.  Source for data Ref: http://data.okfn.org/data/core/country-codes</description>
    <label>Country</label>
</CustomObject>

force-app/main/default/objects/CountryMappings__c/fields/Category_1_Country__c.field-meta.xml
<CustomField>
    <fullName>Category_1_Country__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Category 1 Country</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountControllerExtension.cls
public with sharing class AccountControllerExtension {

    public boolean hasMessages(){
        return ApexPages.getMessages().size() > 0;
    }
    
    public boolean isSalesProfile(){
        string profileName = [Select Id,Name from Profile where Id=:UserInfo.getProfileId() LIMIT 1].Name;
        return profileName.toUpperCase().contains('SALES');
    }
    
    public AccountControllerExtension(ApexPages.StandardController stdController) {

        Account theAccount = [Select Country__c, Do_Not_Contact__c from Account where Id = :stdController.getRecord().Id];

// *** SF-1366 Removed reference to Category 1 Country
//        if (theAccount <> null) {
//            CountryMappings__c theCountry = [SELECT Id, Category_1_Country__c from CountryMappings__c WHERE Name = :theAccount.Country__c LIMIT 1];
//            if (!theCountry.Category_1_Country__c)
//                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'The Country associated with this Account is not a Category 1 Country and therefore registration cannot be processed.'));
//        }
//        else {
//                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'A Category 1 Country must be associated with this Account otherwise registration cannot be processed.'));
//        }
        if (theAccount == null)
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'A Country should be associated with this Account.'));
        
        if (theAccount.Do_Not_Contact__c == true) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Please DO NOT CONTACT this client. Email aml@enett.com for further information.'));
            }    

    }
}