force-app/main/default/objects/Account/fields/Due_Diligence_Risk_Rating__c.field-meta.xml
<CustomField>
    <fullName>Due_Diligence_Risk_Rating__c</fullName>
    <inlineHelpText>Populated by the AML team during the due diligence process.</inlineHelpText>
    <label>Risk Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Risk_Rating__c.field-meta.xml
<CustomField>
    <fullName>Risk_Rating__c</fullName>
    <inlineHelpText>Automatically populated based on the risk rating selected in the Risk Assessment record.</inlineHelpText>
    <label>Risk Rating</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Risk_Rating_Evidence__c/Risk_Rating_Evidence__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRiskAssessment</customHelpPage>
    <label>Risk Assessment</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Risk Assessment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Risk_Rating_Evidence__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipName>Risk_Rating_Evidence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Risk_Rating_Evidence__c/fields/Risk_Rating__c.field-meta.xml
<CustomField>
    <fullName>Risk_Rating__c</fullName>
    <label>Risk Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RiskRatingsUtilityTest.cls
@isTest
public class RiskRatingsUtilityTest {
    
    testmethod static void testRiskRatingFalse(){
        Registration__c reg1 = eNettTestUtility.createRegistration('compName');
        Risk_Rating_Evidence__c rre1 = new Risk_Rating_Evidence__c(Risk_Rating__c = 'High', Registration__c = reg1.Id);
        insert rre1;
        Account acc1 = eNettTestUtility.createAccount('testAccount');
        acc1.Due_Diligence_Risk_Rating__c = 'High';
        update acc1;
        
        // Perform test and verify
        Test.startTest();
        System.assertEquals(false,RiskRatingsUtility.checkRiskRatingDowngrade(reg1.Id, acc1.Id));
        Test.stopTest();
    }
    
    @isTest static void testRiskRatingTrue(){
        Registration__c reg2 = eNettTestUtility.createRegistration('compName2');
        Risk_Rating_Evidence__c rre2 = new Risk_Rating_Evidence__c(Risk_Rating__c = 'Low', Registration__c = reg2.Id);
        insert rre2;
        Account acc2 = eNettTestUtility.createAccount('testAccount');
        acc2.Due_Diligence_Risk_Rating__c = 'High';
        update acc2;
        
        // Perform test and verify
        Test.startTest();
        System.assertEquals(true,RiskRatingsUtility.checkRiskRatingDowngrade(reg2.Id, acc2.Id));
        Test.stopTest();        
    }
}