force-app/main/default/objects/Account/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Automatically populated. This field is only populated for accounts which are activated in client database.</inlineHelpText>
    <label>ECN</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GDPR_Masking__c/GDPR_Masking__c.object-meta.xml
<CustomObject>
    <label>GDPR Masking</label>
    <nameField>
        <displayFormat>GD-{0000}</displayFormat>
        <label>GDPR Data Subject Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDPR Maskings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GDPR_Masking__c/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <label>ECN</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GDPR_Masking__c/fields/GDPR_status__c.field-meta.xml
<CustomField>
    <fullName>GDPR_status__c</fullName>
    <description>GDPR Status of ECN</description>
    <label>GDPR status</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GDPR.cls
/**
* This class contains all the webservices developed for SF integration with GDPR systems.  
  @author : Surajsingh Thakur
  @version : 1.0
  @update : -
**/

@RestResource(urlMapping='/GDPRMaskECN/*')
global with sharing class GDPR{

   /*
      A REST HttpPost class for the GDPR subscriber to send ECNs for data masking.
      GDPR subscriber will send one ECN at a time. Upon receiving that ECN, a record of GDPR_Masking__c will be created.
   */
   @HttpPost
   global static void doPost() {
	
     try{
        //Instantoiating the HttpRequest
        RestRequest req = RestContext.request;

        //Instanciating GDPR_Data_Subject__c object record.
        GDPR_Masking__c dataSubject = new GDPR_Masking__c();
        String ECN =  String.valueOf(req.params.get('ECN'));
       	List<Account> accounts = [SELECT Id from Account where ECN__C =: ECN];
       	if(accounts.size() > 0){
       		dataSubject.ECN__c = ECN;
       		dataSubject.GDPR_status__C = 'New';
           	insert dataSubject;
       	}else{
            EmailUtils.sendAlertEmail('GDPR request for invalid ECN : '+ECN, 'GDPR request for an invalid ECN number is found');
       	}
     }catch(Exception e){
           System.debug('#####Exception in GDPR - GDPRMaskECN HttpPost : '+e.getMessage());
           EmailUtils.sendAlertEmail('Exception in GDPR record creation - GDPRMaskECN HttpPost', e.getMessage() );
      }
    }
}