force-app/main/default/objects/Account/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Automatically populated. This field is only populated for accounts which are activated in client database.</inlineHelpText>
    <label>ECN</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TransactionalData__c/TransactionalData__c.object-meta.xml
<CustomObject>
    <label>Transactional Data</label>
    <nameField>
        <label>Transaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactional Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TransactionalData__c/fields/DaySettledValue__c.field-meta.xml
<CustomField>
    <fullName>DaySettledValue__c</fullName>
    <label>Daily Settled Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TransactionalData__c/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <label>ECN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TransactionalData__c/fields/LinkedAccount__c.field-meta.xml
<CustomField>
    <fullName>LinkedAccount__c</fullName>
    <label>Linked Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactional Data</relationshipLabel>
    <relationshipName>Transactional_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TransactionalData__c/fields/ReportDate__c.field-meta.xml
<CustomField>
    <fullName>ReportDate__c</fullName>
    <description>The date the report was actually made for; not necessarily the date the data was copied!</description>
    <label>Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UpdateAccountTransactionDateTest.cls
@isTest
public class UpdateAccountTransactionDateTest {
    @isTest static void LastTransactionNull() {
        
      Account acc = eNettTestUtility.createAccount('testAccount1');
      
      TransactionalData__c tran=new TransactionalData__C();
      
      tran.Name='testTran1';
      tran.ECN__C= acc.ECN__c;
      tran.LinkedAccount__c=acc.Id;
      tran.ReportDate__c=date.newInstance(2014, 08, 22);
      tran.DaySettledValue__c = 20000;
      insert tran;
      
      tran.ReportDate__c=date.newInstance(2014, 08, 25);
      update tran;
      
    }
}