force-app/main/default/objects/Account/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <inlineHelpText>Automatically populated. This field is only populated for accounts which are activated in client database.</inlineHelpText>
    <label>ECN</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_Channel__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Channel__c</fullName>
    <label>Relationship Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>F2F (client’s office)</fullName>
            </value>
            <value>
                <fullName>F2F (eNett office, other event)</fullName>
            </value>
            <value>
                <fullName>Remote (non face to face)</fullName>
            </value>
            <value>
                <fullName>External Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action</label>
    <nameField>
        <displayFormat>ACTION-{00000}</displayFormat>
        <label>Action Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Action__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <formula>Related_To__r.Contact.FirstName  &amp;  &quot; &quot;  &amp; Related_To__r.Contact.LastName</formula>
    <label>Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <label>Related To</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Actions</relationshipLabel>
    <relationshipName>Actions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Alternative_Email_Adress__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Email_Adress__c</fullName>
    <inlineHelpText>This email address should be filled in when a contact has more than 1 email address setting, which needs to be recorded</inlineHelpText>
    <label>Alternative Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Alternative_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Mobile__c</fullName>
    <label>Alternative Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Alternative_Phone__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Phone__c</fullName>
    <label>Alternative Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FEmail__c.field-meta.xml
<CustomField>
    <fullName>FEmail__c</fullName>
    <label>FEmail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Financial_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Financial_Email_Address__c</fullName>
    <label>Financial Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <inlineHelpText>This field is automatically populated by the Client system integration.</inlineHelpText>
    <label>Job Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Master administrator</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Delivery Implementation</fullName>
            </value>
            <value>
                <fullName>Operational / Technical</fullName>
            </value>
            <value>
                <fullName>Operational / Technical SMEs</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Secondary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email_Address__c</fullName>
    <label>Secondary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SEmail__c.field-meta.xml
<CustomField>
    <fullName>SEmail__c</fullName>
    <label>SEmail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UEmail__c.field-meta.xml
<CustomField>
    <fullName>UEmail__c</fullName>
    <label>UEmail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/User_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>User_Email_Address__c</fullName>
    <label>User Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/GDPR_Masking__c/GDPR_Masking__c.object-meta.xml
<CustomObject>
    <label>GDPR Masking</label>
    <nameField>
        <displayFormat>GD-{0000}</displayFormat>
        <label>GDPR Data Subject Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GDPR Maskings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GDPR_Masking__c/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <label>ECN</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GDPR_Masking__c/fields/GDPR_status__c.field-meta.xml
<CustomField>
    <fullName>GDPR_status__c</fullName>
    <description>GDPR Status of ECN</description>
    <label>GDPR status</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inbound_Email__c/Inbound_Email__c.object-meta.xml
<CustomObject>
    <label>Inbound Email</label>
    <nameField>
        <displayFormat>EML-{000000}</displayFormat>
        <label>Inbound Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inbound_Email__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Inbound Emails</relationshipLabel>
    <relationshipName>Inbound_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inbound_Email__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Ticket</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Inbound Emails</relationshipLabel>
    <relationshipName>Inbound_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inbound_Email__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Inbound Emails</relationshipLabel>
    <relationshipName>Inbound_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inbound_Email__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Relationship_Channel__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Channel__c</fullName>
    <label>Relationship Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>F2F (client’s office)</fullName>
            </value>
            <value>
                <fullName>F2F (eNett office, other event)</fullName>
            </value>
            <value>
                <fullName>Remote (non face to face)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GDPRAutomationProcessTest.cls
/*
*  This is Test class for trigger GDPRAutomationProcessTrigger.apxt 
 *  This class contains the test methods for trigger handler class GDPRAutomationProcessTriggerHandler.apxc
 *  @author  : Kishore Potla
 *  @version : 1.0
 *  @update  : 
*/
@isTest public class GDPRAutomationProcessTest {
    
    @istest private static void customerTest(){
        //CREATE TEST DATA
        Account acc = new Account(Name = 'Test Account',
                                  ECN__c = '9999');
        insert acc;
        
        Contact primaryCont = new Contact (Firstname = 'Test Primary',
                                           Lastname = 'Contact',
                                           Birthdate = date.today(),
                                           Department = 'Accounting',
                                           Email = 'test@gmail.com',
                                           Fax = '832482482',
                                           MailingStreet = '123 ABC Street',
                                           MailingPostalCode = '3323',
                                           MailingState = 'State',
                                           MailingCity = 'City',
                                           MailingCountry = 'Country',
                                           Primary_Email_Address__c = 'primary@gmail.com',
                                           Secondary_Email_Address__c = 'secondary@gmail.com',
                                           Financial_Email_Address__c = 'financial@gmail.com',
                                           Alternative_Email_Adress__c = 'alternative@gmail.com',
                                           User_Email_Address__c = 'user@gmail.com',
                                           FEmail__c = 'femail@gmail.com',
                                           SEmail__c = 'semail@gmail.com',
                                           UEmail__c = 'uemail@gmail.com',
                                           Alternative_Mobile__c = '3234234131',
                                           Alternative_Phone__c = '80820948290',
                                           Phone = '88889999',
                                           MobilePhone = '85038290482',
                                           HomePhone = '47394723',
                                           OtherPhone = '34242342342',
                                           Job_Role__c = 'Primary',
                                           Salutation = 'Mr',
                                           AccountId = acc.Id);
        insert primaryCont;
        
        Contact secondaryCont = new Contact (Firstname = 'Test Secondary',
                                             Lastname = 'Contact',
                                             Email = 'test@gmail.com',
                                             Primary_Email_Address__c = 'test@gmail.com',
                                             Secondary_Email_Address__c = 'test@gmail.com',
                                             Financial_Email_Address__c = 'test@gmail.com',
                                             Phone = '88889999',
                                             MobilePhone = '85038290482',
                                             HomePhone = '47394723',
                                             Job_Role__c = 'Secondary',
                                             AccountId = acc.Id);
        insert secondaryCont;
        
        Case testCase = new Case (AccountId = acc.Id,
                                  ContactId = secondaryCont.Id,
                                  Status = 'New',
                                  Priority = 'Should have');
        insert testCase;
        
        CaseComment testComment = new CaseComment(ParentId = testCase.Id,
                                                  CommentBody = 'test@gmail.com');
        insert testComment;
        
        Lead testLead = new Lead (FirstName = 'test',
                                  LastName = 'Lead',
                                  Email = 'test@gmail.com', 
                                  Company = 'testCompany',
                                  IsConverted = true,
                                  Relationship_Channel__C = 'F2F (client’s office)',
                                  ConvertedAccountId = acc.id);
        insert testLead;
        
        Action__c testAction = new Action__c (Related_To__c  = testCase.Id);
        insert testAction;
        
        Inbound_Email__c testInboundEmail = new Inbound_Email__c(Account__c = acc.Id,
                                                                 Contact__c = secondaryCont.Id,
                                                                 Case__c = testCase.id,
                                                                 From__c = 'test@gmail.com');
        insert testInboundEmail;
        
        Id [] fixedSearchResults= new Id[6];
        fixedSearchResults[0] = primaryCont.Id;
        fixedSearchResults[1] = secondaryCont.Id;
        fixedSearchResults[2] = testCase.Id;
        fixedSearchResults[3] = testComment.Id;
        fixedSearchResults[4] = testAction.Id;
        fixedSearchResults[5] = testInboundEmail.Id;
    
        Test.setFixedSearchResults(fixedSearchResults);
        
        //PERFORM TEST
        test.startTest();
        GDPR_Masking__c sub = new GDPR_Masking__c(ECN__c = '9999', GDPR_Status__C = 'New');
        insert sub;
        test.stopTest();
        
        //ASSERTION
        //List<Contact> resultPrimary
        Account resultAcc = [SELECT Id, 
                             (SELECT Id, Job_Role__c, Birthdate, Department, Email, Fax, HomePhone, MobilePhone, Firstname, Lastname,
                              MailingStreet, MailingPostalCode, MailingState, MailingCity, MailingCountry, OtherPhone, Phone,
                              Alternative_Email_Adress__c, Alternative_Mobile__c, Alternative_Phone__c, FEmail__c, Financial_Email_Address__c,
                              Primary_Email_Address__c, Secondary_Email_Address__c, Salutation, SEmail__c, UEmail__c, User_Email_Address__c FROM Contacts)
                             FROM Account WHERE ECN__c = '9999' LIMIT 1];
        
        if (resultAcc.Contacts != NULL){
            System.assertEquals(1, resultAcc.Contacts.size());
            for (Contact resultContact : resultAcc.Contacts){
                if(resultContact.Job_Role__c == 'Primary'){
                    System.assertEquals(NULL, resultContact.Birthdate);
                    System.assertEquals('XXXX', resultContact.Department);
                    System.assertEquals('axxx@enett.com', resultContact.Email.toLowerCase());
                    System.assertEquals('XXXXXXXXXX', resultContact.Fax);
                    System.assertEquals('XXXXXXXX', resultContact.HomePhone);
                    System.assertEquals('XXXXXXXXXX', resultContact.MobilePhone);
                    System.assertEquals('XXXX', resultContact.FirstName);
                    System.assertEquals('XXXX', resultContact.LastName);
                    System.assertEquals('XXXX', resultContact.MailingStreet);
                    System.assertEquals('XXXX', resultContact.MailingPostalCode);
                    System.assertEquals('XXXX', resultContact.MailingState);
                    System.assertEquals('XXXX', resultContact.MailingCity);
                    System.assertEquals('XXXX', resultContact.MailingCountry);
                    System.assertEquals('XXXXXXXX', resultContact.OtherPhone);
                    System.assertEquals('XXXXXXXX', resultContact.Phone);
                    System.assertEquals('axxx@enett.com', resultContact.Alternative_Email_Adress__c);
                    System.assertEquals('XXXXXXXXXX', resultContact.Alternative_Mobile__c);
                    System.assertEquals('XXXXXXXX', resultContact.Alternative_Phone__c);
                    System.assertEquals('aXXX@enett.com', resultContact.FEmail__c);
                    System.assertEquals('aXXX@enett.com', resultContact.SEmail__c);
                    System.assertEquals('aXXX@enett.com', resultContact.UEmail__c);
                    System.assertEquals('axxx@enett.com', resultContact.Financial_Email_Address__c);
                    System.assertEquals('axxx@enett.com', resultContact.Primary_Email_Address__c);
                    System.assertEquals('axxx@enett.com', resultContact.Secondary_Email_Address__c);
                    System.assertEquals('axxx@enett.com', resultContact.User_Email_Address__c);
                    System.assertEquals('XXXX', resultContact.Salutation);
                    System.assertEquals(true, resultContact.Job_Role__c.contains('Primary'));
                }else if(resultContact.Job_Role__c == 'Secondary'){
                    System.assertEquals('XXXX', resultContact.FirstName);
                    System.assertEquals('XXXX', resultContact.LastName);
                    System.assertEquals('axxx@enett.com', resultContact.Financial_Email_Address__c);
                    System.assertEquals('axxx@enett.com', resultContact.Primary_Email_Address__c);
                    System.assertEquals('axxx@enett.com', resultContact.Secondary_Email_Address__c);
                    System.assertEquals('XXXXXXXX', resultContact.Phone);
                    System.assertEquals('XXXXXXXX', resultContact.HomePhone);
                    System.assertEquals('XXXXXXXXXX', resultContact.MobilePhone);
                    System.assertEquals(true, resultContact.Job_Role__c.contains('Secondary'));
                }
            }
        }
        System.assertEquals(0, [SELECT Id FROM Case WHERE AccountId =: resultAcc.Id].size());
        System.assertEquals(0, [SELECT Id FROM CaseComment WHERE CommentBody = 'test@gmail.com'].size());
        System.assertEquals(0, [SELECT Id FROM Lead WHERE Email = 'test@gmail.com'].size());
        System.assertEquals(0, [SELECT Id FROM Action__c].size());
        System.assertEquals(0, [SELECT Id FROM Inbound_Email__c WHERE Account__c =: resultAcc.Id].size());
    }
}