force-app/main/default/objects/Account/fields/eNett_products__c.field-meta.xml
<CustomField>
    <fullName>eNett_products__c</fullName>
    <label>eNett Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>VirtualTerminal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <description>A customer using VAN or EFT- client can be travel or corporate</description>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <inlineHelpText>This field is automatically populated by the Client system integration.</inlineHelpText>
    <label>Job Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Master administrator</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Delivery Implementation</fullName>
            </value>
            <value>
                <fullName>Operational / Technical</fullName>
            </value>
            <value>
                <fullName>Operational / Technical SMEs</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Left Account</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/BatchCommunityUsers.cls
/**
    Description : This batch class coverts all contacts with status = 'Active' and belonging to accounts
                  having both 'EFT' and 'VANS' products will be converted to community users.
    Jira        : SF-4733
    @author :     Surajsingh Thakur  
*/

global class BatchCommunityUsers implements Database.Batchable<sObject>, Database.Stateful {
    
    global integer count = 0;

    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        List<String> desiredProducts = new List<String>();
        desiredProducts.add('VANs');
        desiredProducts.add('eNett EFT');
        
        //Query all contacts ith status = 'Active' and belonging to accounts having both 'EFT' and 'VANS' products
        String query = 'Select Id, Job_Role__c, Account.OwnerId, Email, LastName, FirstName, Phone, MobilePhone, MailingStreet, MailingCity, MailingState, MailingCountry, MailingPostalCode, account.eNett_products__c From Contact Where account.eNett_products__c includes (\'VANs\',\'eNett EFT\') AND Status__c = \'Active\' AND Account.OwnerId!=NULL ';
        return Database.getQueryLocator(query);
    }
   
    global void execute(Database.BatchableContext BC, List<Contact> communityContacts) {
        
        //Query Community Profile 'Customer Community Login User_VANS'
        Profile communityVANProfile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Login User_VANS' Limit 1];
        System.debug('#####communityVANProfile = '+communityVANProfile);
        //Query Community Profile 'Customer Community Login User_EFT'
        Profile communityEFTProfile = [SELECT Id FROM Profile WHERE Name = 'Customer Community Login User_EFT' Limit 1];
        System.debug('#####communityEFTProfile = '+communityEFTProfile);
        Boolean sendUserEmail = false;
        Boolean allOrNone = false;
        
        List<User> newUsers = new List<User>();
        
        for (Contact contact : communityContacts) {
            String alias = contact.LastName;
            if (alias!=NULL && alias.length() > 8) {
                alias = alias.substring(0, 8);
            }
            String nickName = contact.Email;
            if (nickName!=NULL && nickName.length() > 40) {
                nickName = nickName.substring(0, 40);
            }
        
            User newUser = new User(
                    UserName = contact.Email,
                    LastName = contact.LastName,
                    FirstName = contact.FirstName,
                    Email = contact.Email,
                    phone = contact.Phone,
                    MobilePhone = contact.MobilePhone,
                    Street = contact.MailingStreet,
                    City = contact.MailingCity,
                    State = contact.MailingState,
                    Country = contact.MailingCountry,
                    PostalCode = contact.MailingPostalCode,
                    CommunityNickName = nickName,
                    Alias = alias,
        
                    /* link to the contact and to the account through the contact... */
                    ContactId = contact.Id,
                    
                    /* various user settings */
                    emailencodingkey = 'UTF-8',
                    languagelocalekey = 'en_US',
                    localesidkey = 'en_AU',
                    timezonesidkey = 'Australia/Sydney'
                    
            );
            
            //VAN customers will be assigned to VAN specific profile
            if((contact.account.eNett_products__c).contains('VANs')){
                newUser.ProfileId = communityVANProfile.id; 
            }
            
            //EFT customers will be assigned to EFT specific profile
            else if((contact.account.eNett_products__c).contains('eNett EFT')){
                newUser.ProfileId = communityEFTProfile.id;  
            }
        
            Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.EmailHeader.triggerUserEmail = sendUserEmail;
            newUser.setOptions(dmo);
            
            newUsers.add(newUser);
            count++;

        }
        
        //Insert new Community User
        if (!newUsers.isEmpty()) {
            try{
                Database.SaveResult[] results = Database.insert(newUsers, allOrNone);
            }
            catch(Exception e){
                System.debug('#####Exception = '+e.getMessage()+e.getLineNumber());
            }
        }
    }   
    
    
    global void finish(Database.BatchableContext BC) {
        }
}