force-app/main/default/objects/Account/fields/Financial_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Financial_Contact_Email__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Financial job role</description>
    <label>Financial Contact Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Financial_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Financial_Contact_First_Name__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Financial job role</description>
    <label>Financial Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Financial_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Financial_Contact_Last_Name__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Financial job role</description>
    <label>Financial Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Email_Address__c</fullName>
    <label>Primary Contact Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_First_Name__c</fullName>
    <label>Primary Contact First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Id__c</fullName>
    <label>Primary Contact Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Last_Name__c</fullName>
    <label>Primary Contact Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Phone__c</fullName>
    <label>Primary Contact Phone</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Title__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Title__c</fullName>
    <label>Primary Contact Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reference_Registration__c.field-meta.xml
<CustomField>
    <fullName>Reference_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Contact_Email__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Secondary job role</description>
    <label>Secondary Contact Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Contact_First_Name__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Secondary job role</description>
    <label>Secondary Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Contact_Last_Name__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Secondary job role</description>
    <label>Secondary Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Financial_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Financial_Email_Address__c</fullName>
    <label>Financial Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <inlineHelpText>This field is automatically populated by the Client system integration.</inlineHelpText>
    <label>Job Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Master administrator</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Delivery Implementation</fullName>
            </value>
            <value>
                <fullName>Operational / Technical</fullName>
            </value>
            <value>
                <fullName>Operational / Technical SMEs</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Secondary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email_Address__c</fullName>
    <label>Secondary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <inlineHelpText>This field is automatically populated by the Eloqua integration.</inlineHelpText>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Business Owner/Proprietor</fullName>
            </value>
            <value>
                <fullName>Chairperson</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>CIO</fullName>
            </value>
            <value>
                <fullName>CMO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Travel Consultant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Business Owner/Proprietor</fullName>
            </value>
            <value>
                <fullName>Chairperson</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>CIO</fullName>
            </value>
            <value>
                <fullName>CMO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Travel Consultant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Reference_Registration__c.field-meta.xml
<CustomField>
    <fullName>Reference_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>From Lead</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>From Lead</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <inlineHelpText>e.g. CEO, Director, Manager</inlineHelpText>
    <label>Job Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>From Lead</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>From Lead</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Miss</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Mr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactTriggerHandler.cls
/* This is the handler class for ContactTrigger
 */
public class ContactTriggerHandler{    
    public void onAfterDelete(List<Contact> contacts){
        updateContactInfoOnRelatedRecords(contacts, true);
    }
    public void onAfterInsert(List<Contact> contacts){
        preventContactDuplicates(contacts, false);
        //SF-5316 31/10/2018 Jasmine - No need to update contact on insert because lead mappings already collect needed data.
        //LeadUtility cls already does the update and if it triggers this trigger governor limit will be exceeded.
        //updateContactInfoOnRelatedRecords(contacts, false);
    }
    public void onAfterUpdate(List<Contact> contacts){
        preventContactDuplicates(contacts, true);
        updateContactInfoOnRelatedRecords(contacts, false);
    }
    public void onUndelete(List<Contact> contacts){
        updateContactInfoOnRelatedRecords(contacts, false);
    }
    /* Originally an individual trigger
     * Transferred into this handler class
	 */ 
    private void preventContactDuplicates(List<Contact> contacts, Boolean isUpdate){
        if (!checkRecursive.runOnce() && isUpdate) {
            return;
        }   
        Set<ID> AccountIDs = new Set<ID>();
        // Grab related Accounts
        for(Contact c : contacts) {
            AccountIDs.add(c.AccountId);
        }
        
        // Select Contacts with type of 'Primary','Secondary' or 'Financial' for relevant accounts
        List<Contact> AccountContacts = [
            SELECT Id, Job_Role__c, AccountID 
            FROM Contact 
            WHERE AccountId in :AccountIDs
            AND Job_Role__c INCLUDES ('Primary','Secondary','Financial') ];
        
        // Iterate Accounts/Contacts/Types and compare, removing any duplicates
        SET<Id> updateIds = new SET<Id>();
        
        if(!AccountContacts.isEmpty()) {
            for(Contact c : contacts) {
                if (String.isNotEmpty(c.Job_Role__c)) {
                    for(String selectedType : c.Job_Role__c.split(';')) {
                        // Iterate through the other Account Contacts, removing instances Type of our new/updated Contact
                        Integer j = 0;
                        while (j < AccountContacts.size()) {
                            //If it's our current contact = ignore!
                            if (AccountContacts.get(j).AccountID == c.AccountId && AccountContacts.get(j).Job_Role__c.contains(selectedType) && AccountContacts.get(j).Id != c.Id) {
                                if (selectedType == 'Primary' || selectedType == 'Secondary' || selectedType == 'Financial') {
                                    AccountContacts.get(j).Job_Role__c = AccountContacts.get(j).Job_Role__c.remove(selectedType + ';');
                                    AccountContacts.get(j).Job_Role__c = AccountContacts.get(j).Job_Role__c.remove(selectedType);
                                }
                                if (selectedType == 'Primary') AccountContacts.get(j).Primary_Email_Address__c = null;
                                if (selectedType == 'Secondary') AccountContacts.get(j).Secondary_Email_Address__c = null;
                                if (selectedType == 'Financial') AccountContacts.get(j).Financial_Email_Address__c = null;                            
                                updateIds.add(AccountContacts.get(j).Id);
                            }
                            j++;
                        }
                    }
                }
            }
        }
        
        List<Contact> modifiedAccountContacts = new List<Contact>();
        for (Contact c : AccountContacts) {
            if (updateIds.contains(c.Id))
                modifiedAccountContacts.add(c);
        }
        
        if (!modifiedAccountContacts.isEmpty()) update modifiedAccountContacts;
    }
    /*
* After Insert, After Update, After Delete, After UnDelete*
* We have primary, secondary and financial contact info under account 
* We have primary contact info under rego
* The purpose of this is when we change the contact info, this will update the account and rego as well
* Ticket: SF-5132
* Author: Ronnie Yang
*/
    private void updateContactInfoOnRelatedRecords(List<Contact> contacts, Boolean isDelete){
        //get a list of accounts to update based on the contacts list
        //feels like there's a cleaner way
        List<Id> accIds = new List<Id>();
        List<Id> regoIds = new List<Id>();
        //get accounts that own the contacts
        for(Contact c : contacts){
            accIds.add(c.AccountId);
        }
        Map<Id, Account> accMap = new Map<Id, Account>([SELECT Id, Reference_Registration__c, Primary_Contact_Email_Address__c, Primary_Contact_First_Name__c,
                                                        Primary_Contact_Last_Name__c, Primary_Contact_Id__c, Primary_Contact_Phone__c,
                                                        Primary_Contact_Title__c, Secondary_Contact_First_Name__c, Secondary_Contact_Last_Name__c,
                                                        Secondary_Contact_Email__c, Financial_Contact_First_Name__c, Financial_Contact_Last_Name__c,
                                                        Financial_Contact_Email__c
                                                        FROM Account
                                                        WHERE Id IN: accIds]);
        //get the reference rego based on the accounts
        for(Account a: accMap.values()){
            regoIds.add(a.Reference_Registration__c);
        }
        Map<Id, Registration__c> regoMap = new Map<Id, Registration__c>([SELECT Id, First_Name__c, Last_Name__c, Job_Title__c, Email__c, Phone__c, Salutation__c
                                                                         FROM Registration__c
                                                                         WHERE Id IN: regoIds]);
        //start updating
       
        List<Account> accsToUpdateList = new List<Account>();
        Map<Id, Account> accsToUpdateMap = new Map<Id, Account>(); 
        List<Registration__c> regosToUpdate = new List<Registration__c>();
        for(Contact c: contacts){
            //no point updating if the contact has no applicable roles
            //no point updating if the contact is not linked to an account
            if(c.Job_Role__c != NULL && c.AccountId != NULL){
                //find the contact's parent account and its reference rego
                //Kishore Potla - PDS-3406: error in current system while updating list of contacts of same account 
                Account parent;
                if(accsToUpdateMap.containsKey(c.AccountId)){
                    parent = accsToUpdateMap.get(c.AccountId);
                }else{
                    parent = accMap.get(c.AccountId);
                }               
                Registration__c referenceReg = regoMap.get(parent.Reference_Registration__c);
                // Because you can't delete a primary contact so isDelete condition is not applied here like the secondary/financial part
                if(c.Job_Role__c.contains('Primary')){
                    if(referenceReg != NULL){
                        //update reg
                        referenceReg.First_Name__c = c.FirstName;
                        referenceReg.Last_Name__c = c.LastName;
                        referenceReg.Job_Title__c = c.Title__c;
                        referenceReg.Email__c = c.Primary_Email_Address__c;
                        referenceReg.Phone__c = c.Phone;
                        referenceReg.Salutation__c = c.Salutation;
                        regosToUpdate.add(referenceReg);
                    }
                    //update account
                    parent.Primary_Contact_Email_Address__c = c.Primary_Email_Address__c;
                    parent.Primary_Contact_First_Name__c = c.FirstName;
                    parent.Primary_Contact_Last_Name__c = c.LastName;
                    parent.Primary_Contact_Id__c = c.Id;
                    parent.Primary_Contact_Phone__c = c.Phone;
                    parent.Primary_Contact_Title__c = c.Salutation;
                }
                if(c.Job_Role__c.contains('Secondary')){
                    parent.Secondary_Contact_First_Name__c = isDelete ? '' : c.FirstName;
                    parent.Secondary_Contact_Last_Name__c = isDelete ? '' : c.LastName;
                    parent.Secondary_Contact_Email__c = isDelete ? '' : c.Secondary_Email_Address__c;
                }
                if(c.Job_Role__c.contains('Financial')){
                    parent.Financial_Contact_First_Name__c = isDelete ? '' : c.FirstName;
                    parent.Financial_Contact_Last_Name__c = isDelete ? '' : c.LastName;
                    parent.Financial_Contact_Email__c = isDelete ? '' : c.Financial_Email_Address__c;
                }
                accsToUpdateMap.put(parent.id, parent);
            }
        }
        accsToUpdateList = accsToUpdateMap.values();
        //to avoid null pointer
        if(accsToUpdateList.size() > 0){
            SavePoint sp = Database.setSavepoint();
            try{
                Database.DMLOptions dmo = new Database.DMLOptions();
                //allowing partial processing
                dmo.optAllOrNone = false;
                
                List<Database.SaveResult> saveResults = Database.update(new List<Account>(accsToUpdateList), dmo);
                for(Integer i = 0; i < saveResults.size(); i++){
                    Database.SaveResult saveResult = saveResults[i];
                    if(!saveResult.isSuccess()){
                        for(Database.Error err: saveResult.getErrors()){
                            System.debug('####ERROR WHILE PROCESSING ACCOUNT: ' + err.getMessage());
                        }
                    }
                }
            }catch (Exception e){
                //rollback if something else is wrong
                Database.rollback(sp);
                System.debug('####ERROR ENCOUNTERED: ' + e.getMessage());
                throw e;
            }
        }
        if(regosToUpdate.size() > 0){
            SavePoint sp = Database.setSavepoint();
            try{
                Database.DMLOptions dmo = new Database.DMLOptions();
                //allowing partial processing
                dmo.optAllOrNone = false;
                
                List<Database.SaveResult> saveResults = Database.update(regosToUpdate, dmo);
                for(Integer i = 0; i < saveResults.size(); i++){
                    Database.SaveResult saveResult = saveResults[i];
                    if(!saveResult.isSuccess()){
                        for(Database.Error err: saveResult.getErrors()){
                            System.debug('####ERROR WHILE PROCESSING ACCOUNT: ' + err.getMessage());
                        }
                    }
                }
            }catch (Exception e){
                //rollback if something else is wrong
                Database.rollback(sp);
                System.debug('####ERROR ENCOUNTERED: ' + e.getMessage());
                throw e;
            }
        }           
    }
}