force-app/main/default/objects/Account/fields/Financial_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Financial_Contact_Email__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Financial job role</description>
    <label>Financial Contact Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Financial_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Financial_Contact_First_Name__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Financial job role</description>
    <label>Financial Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Financial_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Financial_Contact_Last_Name__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Financial job role</description>
    <label>Financial Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Email_Address__c</fullName>
    <label>Primary Contact Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_First_Name__c</fullName>
    <label>Primary Contact First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Id__c</fullName>
    <label>Primary Contact Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Last_Name__c</fullName>
    <label>Primary Contact Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Phone__c</fullName>
    <label>Primary Contact Phone</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Title__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Title__c</fullName>
    <label>Primary Contact Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Contact_Email__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Secondary job role</description>
    <label>Secondary Contact Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Contact_First_Name__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Secondary job role</description>
    <label>Secondary Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Contact_Last_Name__c</fullName>
    <description>This is updated automatically when a contact linked to this account is set to the Secondary job role</description>
    <label>Secondary Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Financial_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Financial_Email_Address__c</fullName>
    <label>Financial Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <inlineHelpText>This field is automatically populated by the Client system integration.</inlineHelpText>
    <label>Job Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Master administrator</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Delivery Implementation</fullName>
            </value>
            <value>
                <fullName>Operational / Technical</fullName>
            </value>
            <value>
                <fullName>Operational / Technical SMEs</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Secondary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email_Address__c</fullName>
    <label>Secondary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <inlineHelpText>This field is automatically populated by the Eloqua integration.</inlineHelpText>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Business Owner/Proprietor</fullName>
            </value>
            <value>
                <fullName>Chairperson</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>CIO</fullName>
            </value>
            <value>
                <fullName>CMO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Travel Consultant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>From Lead</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>From Lead</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <inlineHelpText>e.g. CEO, Director, Manager</inlineHelpText>
    <label>Job Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>From Lead</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>From Lead</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Miss</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Mr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactTriggerHandlerTest.cls
@isTest
public class ContactTriggerHandlerTest {
    //SF-5316 3/11/2018 Jasmine - Since afterInsert method has been disabled in SF-5316, this test method
    //will be disabled to prevent itself from failing during deployment
    /*private static testMethod void updateContactInfoOnRelatedRecordsTestInsert(){
        Account testAcc = eNettTestUtility.createAccount('Test Account');
        Registration__c testReg = eNettTestUtility.createRegistration('Test Company', testAcc.Id);
        Contact testContact = eNettTestUtility.createContact(testAcc.Id); 
        testAcc = [SELECT Id, Primary_Contact_Email_Address__c, Primary_Contact_First_Name__c,
                   Primary_Contact_Last_Name__c, Primary_Contact_Id__c, Primary_Contact_Phone__c,
                   Primary_Contact_Title__c, Secondary_Contact_First_Name__c, Secondary_Contact_Last_Name__c,
                   Secondary_Contact_Email__c, Financial_Contact_First_Name__c, Financial_Contact_Last_Name__c,
                   Financial_Contact_Email__c
                   FROM Account WHERE Id=: testAcc.Id];
        testReg = [SELECT Id, Account__c, First_Name__c, Last_Name__c, Job_Role__c, Email__c, Phone__c, Salutation__c
                   FROM Registration__c WHERE Account__c=: testAcc.Id];
        //check contact info on account
        System.assertEquals(testContact.Primary_Email_Address__c, testAcc.Primary_Contact_Email_Address__c);
        System.assertEquals(testContact.FirstName, testAcc.Primary_Contact_First_Name__c);
        System.assertEquals(testContact.LastName, testAcc.Primary_Contact_Last_Name__c);
        System.assertEquals(testContact.Id, testAcc.Primary_Contact_Id__c);
        System.assertEquals(testContact.Phone, testAcc.Primary_Contact_Phone__c);
        System.assertEquals(testContact.Salutation, testAcc.Primary_Contact_Title__c);
        System.assertEquals(testContact.FirstName, testAcc.Secondary_Contact_First_Name__c);
        System.assertEquals(testContact.LastName, testAcc.Secondary_Contact_Last_Name__c);
        System.assertEquals(testContact.Secondary_Email_Address__c, testAcc.Secondary_Contact_Email__c);
        System.assertEquals(testContact.FirstName, testAcc.Financial_Contact_First_Name__c);
        System.assertEquals(testContact.LastName, testAcc.Financial_Contact_Last_Name__c);
        System.assertEquals(testContact.Financial_Email_Address__c, testAcc.Financial_Contact_Email__c);
        //check contact info on rego
        System.assertEquals(testContact.FirstName, testReg.First_Name__c);
        System.assertEquals(testContact.LastName, testReg.Last_Name__c);
        System.assertEquals(testContact.Title__c, testReg.Job_Role__c);
        System.assertEquals(testContact.Primary_Email_Address__c, testReg.Email__c);
        System.assertEquals(testContact.Phone, testReg.Phone__c);
        System.assertEquals(testContact.Salutation, testReg.Salutation__c);  
    }*/
    private static testMethod void updateContactInfoOnRelatedRecordsTestUpdate(){
        Account testAcc = eNettTestUtility.createAccount('Test Account');
        Registration__c testReg = eNettTestUtility.createRegistration('Test Company', testAcc.Id);
        Contact testContact = eNettTestUtility.createContact(testAcc.Id); 
        testContact.FirstName = 'Updated FirstName';
        testContact.LastName = 'Updated LastName';
        testContact.Primary_Email_Address__c = 'updatedprimary@email.com';
        testContact.Secondary_Email_Address__c = 'updatedsecondary@email.com';
        testContact.Financial_Email_Address__c = 'updatedfinancial@email.com';
        testContact.Salutation = 'Mr';
        testContact.Title__c = 'boss';
        update testContact;
        testAcc = [SELECT Id, Primary_Contact_Email_Address__c, Primary_Contact_First_Name__c,
                   Primary_Contact_Last_Name__c, Primary_Contact_Id__c, Primary_Contact_Phone__c,
                   Primary_Contact_Title__c, Secondary_Contact_First_Name__c, Secondary_Contact_Last_Name__c,
                   Secondary_Contact_Email__c, Financial_Contact_First_Name__c, Financial_Contact_Last_Name__c,
                   Financial_Contact_Email__c
                   FROM Account WHERE Id=: testAcc.Id];
        testReg = [SELECT Id, Account__c, First_Name__c, Last_Name__c, Job_Title__c, Email__c, Phone__c, Salutation__c
                   FROM Registration__c WHERE Account__c=: testAcc.Id];
        //check contact info on account
        System.assertEquals(testContact.Primary_Email_Address__c, testAcc.Primary_Contact_Email_Address__c);
        System.assertEquals(testContact.FirstName, testAcc.Primary_Contact_First_Name__c);
        System.assertEquals(testContact.LastName, testAcc.Primary_Contact_Last_Name__c);
        System.assertEquals(testContact.Id, testAcc.Primary_Contact_Id__c);
        System.assertEquals(testContact.Phone, testAcc.Primary_Contact_Phone__c);
        System.assertEquals(testContact.Salutation, testAcc.Primary_Contact_Title__c);
        System.assertEquals(testContact.FirstName, testAcc.Secondary_Contact_First_Name__c);
        System.assertEquals(testContact.LastName, testAcc.Secondary_Contact_Last_Name__c);
        System.assertEquals(testContact.Secondary_Email_Address__c, testAcc.Secondary_Contact_Email__c);
        System.assertEquals(testContact.FirstName, testAcc.Financial_Contact_First_Name__c);
        System.assertEquals(testContact.LastName, testAcc.Financial_Contact_Last_Name__c);
        System.assertEquals(testContact.Financial_Email_Address__c, testAcc.Financial_Contact_Email__c);
        //check contact info on rego
        System.assertEquals(testContact.FirstName, testReg.First_Name__c);
        System.assertEquals(testContact.LastName, testReg.Last_Name__c);
        System.assertEquals(testContact.Title__c, testReg.Job_Title__c);
        System.assertEquals(testContact.Primary_Email_Address__c, testReg.Email__c);
        System.assertEquals(testContact.Phone, testReg.Phone__c);
        System.assertEquals(testContact.Salutation, testReg.Salutation__c);
    }
    
    private static testMethod void updateContactInfoOnRelatedRecordsTestDelete(){
        Account testAcc = eNettTestUtility.createAccount('Test Account');
        Contact testContact = eNettTestUtility.createContact(testAcc.Id); 
        //bypassing the inability to delete primary contact
        eNettTestUtility.createContact(testAcc.Id); 
        testContact.Job_Role__c = 'Secondary; Financial';
        update testContact;
        delete testContact;
        testAcc = [SELECT Id, Secondary_Contact_First_Name__c, Secondary_Contact_Last_Name__c,
                   Secondary_Contact_Email__c, Financial_Contact_First_Name__c, Financial_Contact_Last_Name__c,
                   Financial_Contact_Email__c
                   FROM Account WHERE Id=: testAcc.Id];
        //check contact info on account -- primary info can't be deleted so not verifying rego
        System.assertEquals(NULL, testAcc.Secondary_Contact_First_Name__c);
        System.assertEquals(NULL, testAcc.Secondary_Contact_Last_Name__c);
        System.assertEquals(NULL, testAcc.Secondary_Contact_Email__c);
        System.assertEquals(NULL, testAcc.Financial_Contact_First_Name__c);
        System.assertEquals(NULL, testAcc.Financial_Contact_Last_Name__c);
        System.assertEquals(NULL, testAcc.Financial_Contact_Email__c);
        
        //test undelete
        undelete testContact;
        testAcc = [SELECT Id, Secondary_Contact_First_Name__c, Secondary_Contact_Last_Name__c,
                   Secondary_Contact_Email__c, Financial_Contact_First_Name__c, Financial_Contact_Last_Name__c,
                   Financial_Contact_Email__c
                   FROM Account WHERE Id=: testAcc.Id];
        //check contact info on account -- primary info can't be deleted so not verifying rego
        System.assertEquals(testContact.FirstName, testAcc.Secondary_Contact_First_Name__c);
        System.assertEquals(testContact.LastName, testAcc.Secondary_Contact_Last_Name__c);
        System.assertEquals(testContact.Secondary_Email_Address__c, testAcc.Secondary_Contact_Email__c);
        System.assertEquals(testContact.FirstName, testAcc.Financial_Contact_First_Name__c);
        System.assertEquals(testContact.LastName, testAcc.Financial_Contact_Last_Name__c);
        System.assertEquals(testContact.Financial_Email_Address__c, testAcc.Financial_Contact_Email__c);
    }
}