force-app/main/default/objects/Account/fields/IsApi__c.field-meta.xml
<CustomField>
    <fullName>IsApi__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t mess with this or else</description>
    <inlineHelpText>Don&#39;t mess with this or else</inlineHelpText>
    <label>IsApi</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Referrer_Code__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Code__c</fullName>
    <label>Introducer / Referrer Code (ECN)</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Referrer_Name__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Name__c</fullName>
    <label>Introducer / Referrer Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>About Payments</fullName>
            </value>
            <value>
                <fullName>Adyen</fullName>
            </value>
            <value>
                <fullName>Agoda</fullName>
            </value>
            <value>
                <fullName>Air Asia</fullName>
            </value>
            <value>
                <fullName>Axess International Network, Inc</fullName>
            </value>
            <value>
                <fullName>Blue Team Travel Network SRL</fullName>
            </value>
            <value>
                <fullName>CCRA International</fullName>
            </value>
            <value>
                <fullName>CEE Travel System</fullName>
            </value>
            <value>
                <fullName>Club Travel SA</fullName>
            </value>
            <value>
                <fullName>Computop</fullName>
            </value>
            <value>
                <fullName>Conferma</fullName>
            </value>
            <value>
                <fullName>Contac Services</fullName>
            </value>
            <value>
                <fullName>Cornerstone</fullName>
            </value>
            <value>
                <fullName>Dolphin Dynamics</fullName>
            </value>
            <value>
                <fullName>Flightgenius</fullName>
            </value>
            <value>
                <fullName>Gant Travel Management</fullName>
            </value>
            <value>
                <fullName>Gateway</fullName>
            </value>
            <value>
                <fullName>Geo Travel Network Di Geo Spa</fullName>
            </value>
            <value>
                <fullName>Globalcollect</fullName>
            </value>
            <value>
                <fullName>Globalstar</fullName>
            </value>
            <value>
                <fullName>Hitchhiker</fullName>
            </value>
            <value>
                <fullName>Hotelzon</fullName>
            </value>
            <value>
                <fullName>IGA Voyages</fullName>
            </value>
            <value>
                <fullName>Juniper</fullName>
            </value>
            <value>
                <fullName>Manor</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Mr Orange</fullName>
            </value>
            <value>
                <fullName>Multicom</fullName>
            </value>
            <value>
                <fullName>Navitas</fullName>
            </value>
            <value>
                <fullName>Orchestra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <description>A Company (eNett client or non eNett client) refers eNett products to other companies.</description>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/ReferrerCodes__c/ReferrerCodes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ReferrerCodes</label>
</CustomObject>

force-app/main/default/objects/ReferrerCodes__c/fields/ReferrerCode__c.field-meta.xml
<CustomField>
    <fullName>ReferrerCode__c</fullName>
    <description>This holds the ReferrerCode (ECN) for the referrers listed in the Introducer/Referrer Name on the Lead</description>
    <label>ReferrerCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestAccountContactIntegration.cls
@isTest
private class TestAccountContactIntegration {

    static testMethod void TestAccountInsertSetsValues() {
        // related to http://jira/browse/SF-961
        List<ReferrerCodes__c> upsertList = new List<ReferrerCodes__c>();
        upsertList.add(new ReferrerCodes__c(Name='Test',ReferrerCode__c='403525'));
//      upsertList.add(new ReferrerCodes__c(Name='Test1',ReferrerCode__c='403896'));
//      upsertList.add(new ReferrerCodes__c(Name='Test2',ReferrerCode__c='402005'));
//      upsertList.add(new ReferrerCodes__c(Name='Test3',ReferrerCode__c='400469'));
//      upsertList.add(new ReferrerCodes__c(Name='Test4',ReferrerCode__c='403894'));
        upsertList.add(new ReferrerCodes__c(Name='Test5',ReferrerCode__c='N/A'));
        upsert upsertList;
        
        //Privlidges User Account - Integration User is used to insert stuff so create a teprary Integration User account ( linked to Admin No Expiry Profile )
        Profile  adminProfile = [select id , Name from Profile where UserType = 'Standard' and UserLicense.Name = 'Salesforce' and Name = 'System Administrator (no expiry)'];
        string profileName = adminProfile.Name.deleteWhitespace();

        User theUser = new User(alias = 'TestUser',
                                email = profileName + '@testorg.com',
                                emailencodingkey = 'UTF-8',
                                lastname = profileName,
                                languagelocalekey = 'en_US',
                                localesidkey = 'en_US',
                                profileid = adminProfile.Id,
                                timezonesidkey = 'America/Los_Angeles',
                                username = profileName + '@testorg.com');

        insert theUser;
        system.assertNotEquals(null, theUser.Id);

        system.runas(theUser){
            for (ReferrerCodes__c rec : upsertList)
                if(rec.ReferrerCode__c != 'N/A'){
                    Account testAccount = new Account( Name = rec.Name, Referrer_Code__c = rec.ReferrerCode__c, IsApi__c = true );
                    insert testAccount;
                
                    system.assertNotEquals(null, testAccount.Id);
                    //system.assertEquals(rec.Name, [select Referrer_Name__c from Account where Id = :testAccount.Id].Referrer_Name__c, 'Referrer Name should match ' + rec);
            }
       }
    }
}