force-app/main/default/objects/Account/fields/RBA_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>RBA_Address_Line_1__c</fullName>
    <label>Reg Bus Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>RBA_Address_Line_2__c</fullName>
    <label>Reg Bus Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_City__c.field-meta.xml
<CustomField>
    <fullName>RBA_City__c</fullName>
    <label>Reg Bus City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_Country__c.field-meta.xml
<CustomField>
    <fullName>RBA_Country__c</fullName>
    <label>Reg Bus Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_Postcode__c.field-meta.xml
<CustomField>
    <fullName>RBA_Postcode__c</fullName>
    <label>Reg Bus Postcode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RBA_State_Province__c.field-meta.xml
<CustomField>
    <fullName>RBA_State_Province__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reg Bus State Province</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.RBA_Country__c</field>
            <operation>equals</operation>
            <valueField>State_Detail__c.Country_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Detail__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler{
    public void OnAfterUpdate(Map<Id, Account> accMap){
        /**
		* After an account has been updated, 
		* this will loop through all its reporting child additional ECNs,
	    * ensuring that the registered addresses are updated to be the same.
		@author : Ronnie Yang
		@ticket : SF-5165
		**/
        List<Account> childAccs = [SELECT Id, RBA_Address_Line_1__c, RBA_Address_Line_2__c, RBA_City__c, 
                                   RBA_Country__c, RBA_Postcode__c, RBA_State_Province__c, Parent.Id
                                   FROM Account 
                                   WHERE Parent.Id IN:accMap.keySet()];
        for(Account a : childAccs){
            Account parent= accMap.get(a.Parent.Id);
            a.RBA_Address_Line_1__c = parent.RBA_Address_Line_1__c;
            a.RBA_Address_Line_2__c = parent.RBA_Address_Line_2__c;
            a.RBA_City__c = parent.RBA_City__c;
            a.RBA_Country__c = parent.RBA_Country__c;
            a.RBA_Postcode__c = parent.RBA_Postcode__c;
            a.RBA_State_Province__c = parent.RBA_State_Province__c;
        }
        update childAccs;
    }
}