force-app/main/default/objects/Account/fields/Reference_Registration__c.field-meta.xml
<CustomField>
    <fullName>Reference_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reference Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/eNett_Contract__c.object-meta.xml
<CustomObject>
    <label>eNett Contract</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>eNett Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eNett Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/eNett_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eNett Contract</relationshipLabel>
    <relationshipName>eNett_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Account_Region__c.field-meta.xml
<CustomField>
    <fullName>Account_Region__c</fullName>
    <formula>TEXT(Account_Name__r.Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/APAC_Country__c.field-meta.xml
<CustomField>
    <fullName>APAC_Country__c</fullName>
    <formula>IF ( Account_Region__c = &quot;APAC&quot;, ( IF(Account_Country__c = &quot;Australia&quot;, &quot;Australia&quot;, &quot;Other&quot;) ), &quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>APAC Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Country_Product__c.field-meta.xml
<CustomField>
    <fullName>Country_Product__c</fullName>
    <description>Used for filtering the Drawloop Client Agreements.  Note: the asterisk is used to save a client agreement against only the VANs contract when both VANs and EFT contracts are generated.</description>
    <formula>CASE(Account_Name__r.Reference_Registration__r.Country__c, &#39;Australia&#39;, &#39;A&#39;, &#39;New Zealand&#39;, &#39;NZ&#39;, &#39;Other&#39;) 
+ &#39;-&#39; 
+ IF(INCLUDES(Account_Name__r.Reference_Registration__r.Product__c, &#39;eNett EFT&#39;), &#39;E&#39;, &#39;&#39;)
+ IF(INCLUDES(Account_Name__r.Reference_Registration__r.Product__c, &#39;VANs&#39;), &#39;V&#39;, &#39;&#39;)
+ IF(AND(INCLUDES(Account_Name__r.Reference_Registration__r.Product__c, &#39;eNett EFT&#39;),INCLUDES(Account_Name__r.Reference_Registration__r.Product__c, &#39;VANs&#39;), ISPICKVAL(eNett_Product__c, &#39;VANs&#39;)),&#39;*&#39;,&#39;&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country / Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/eNett_Product__c.field-meta.xml
<CustomField>
    <fullName>eNett_Product__c</fullName>
    <label>eNett Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Path_To_T_Cs__c.field-meta.xml
<CustomField>
    <fullName>Path_To_T_Cs__c</fullName>
    <description>Contains the path to the version of the T&amp;Cs relevant to this contract.</description>
    <label>Path To T&amp;Cs</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Generic_Lookups__c/Generic_Lookups__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Basic Key/Value Lookup to keep application values to minimise hard-coding etc.</description>
    <label>Generic Lookups</label>
</CustomObject>

force-app/main/default/objects/Generic_Lookups__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/generateContracts.cls
global class generateContracts {  

    @InvocableMethod
    webservice static void generateContract(List<Id> contractIDs) {
        List<Id> filteredIds = new List<Id>();
        for (eNett_Contract__c ct : [SELECT id, Account_Name__r.Reference_Registration__c, country_product__c FROM eNett_Contract__c WHERE Id in :contractIDs]) {
            if (ct.country_product__c != 'A-EV' && ct.country_product__c != 'NZ-EV' && ct.Account_Name__c != null && ct.Account_Name__r.Reference_Registration__c != null)
                ClientAgreementController.savePDF(ct.Account_Name__r.Reference_Registration__c, ct.Id);
                //filteredIds.add(ct.id);
        }
        
        //if (!filteredIds.isEmpty()) {
        //    generateContracts.batchGenerate(filteredIds, UserInfo.getSessionID());
        //}

    }

    @future(callout=true)
    public static void batchGenerate(LIST<ID> contractIDs, String sessionID) { 

        final ID DDPId = Generic_Lookups__c.getInstance('Standard_Agreement_DDP').Value__c;
        final ID deliveryId = Generic_Lookups__c.getInstance('Standard_Agreement_DDP_Delivery').Value__c;


        Loop.loopMessage lm = new Loop.loopMessage();
        for (ID contractId : contractIDs) {
            lm.requests.add(new Loop.loopMessage.loopMessageRequest(contractId, DDPId, new Map<string, string>{'deploy' => deliveryId}));
        }
        lm.sessionId = sessionID;
        lm.sendAllRequests();
    }

    /* Obsolete PoC
    public static void setTCsVersion(LIST<ID> contractIDs) { 

        // Map containing the latest versions of the T&Cs for each region
        Map<string,ContentDocument> versionMap = new Map<string,ContentDocument>();
        for( ContentDocument cd : [ Select Id,Title, LatestPublishedVersionId from ContentDocument where Title Like 'eNett - Client Agreement%']){
            versionMap.put( cd.Title, cd );
        } 

        Id TCVersionID = null;
        List<eNett_Contract__c> contrUpdate = new LIST<eNett_Contract__c>();

        for (eNett_Contract__c contr : [select Id, Country_Product__c, Account_Region__c, APAC_Country__c, eNett_Product__c from eNett_Contract__c  where Id in :contractIDs]) {

            TCVersionID = null;

            if (contr.Country_Product__c == 'A-V') TCVersionID = versionMap.get('eNett - Client Agreement AUS VANs only').LatestPublishedVersionId;
            else if ( contr.Country_Product__c == 'A-E') TCVersionID = versionMap.get('eNett - Client Agreement AUS EFT only').LatestPublishedVersionId;
            else if ( contr.Country_Product__c == 'A-EV') TCVersionID = versionMap.get('eNett - Client Agreement AUS EFT and VANs').LatestPublishedVersionId;
            else if ( contr.Country_Product__c == 'A-EV*') TCVersionID = versionMap.get('eNett - Client Agreement AUS EFT and VANs').LatestPublishedVersionId;
            else if ( contr.Country_Product__c == 'NZ-V') TCVersionID = versionMap.get('eNett - Client Agreement NZ VANs Only').LatestPublishedVersionId;
            else if ( contr.Country_Product__c == 'NZ-E') TCVersionID = versionMap.get('eNett - Client Agreement NZ EFT only').LatestPublishedVersionId;
            else if ( contr.Country_Product__c == 'NZ-EV') TCVersionID = versionMap.get('eNett - Client Agreement NZ EFT and VANs').LatestPublishedVersionId;
            else if ( contr.Country_Product__c == 'NZ-EV*') TCVersionID = versionMap.get('eNett - Client Agreement NZ EFT and VANs').LatestPublishedVersionId;
            else TCVersionID = versionMap.get('eNett - Terms and Conditions Rest of the world').LatestPublishedVersionId;

            contr.Path_To_T_Cs__c = URL.getSalesforceBaseUrl().toExternalForm() + '/' + TCVersionID;
            contrUpdate.add(contr);
        }
        database.update(contrUpdate, false);
    }*/

}