force-app/main/default/objects/Account/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>External Registration</fullName>
            </value>
            <value>
                <fullName>Internal Registration - Re Reg</fullName>
            </value>
            <value>
                <fullName>Internal Registration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Left Account</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/eNett_Contract__c/eNett_Contract__c.object-meta.xml
<CustomObject>
    <label>eNett Contract</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>eNett Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eNett Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/eNett_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eNett Contract</relationshipLabel>
    <relationshipName>eNett_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard T&amp;Cs</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Contract not required</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Internal Transacting</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Incentive_Type__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Type__c</fullName>
    <label>Incentive Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>% of Interchange</fullName>
            </value>
            <value>
                <fullName>Fixed % (BPS)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Rebate_Type__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Type__c</fullName>
    <label>Rebate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flat</fullName>
            </value>
            <value>
                <fullName>Tiered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Flight</fullName>
                <default>true</default>
                <label>In Flight</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Subscription_Fee__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Fee__c</fullName>
    <inlineHelpText>Enter “zero” if you are waiving the subscription fee, otherwise enter the value to be charged.</inlineHelpText>
    <label>Subscription Fee</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/attainable_ttv_monthly__c.field-meta.xml
<CustomField>
    <fullName>attainable_ttv_monthly__c</fullName>
    <label>Attainable GDV (monthly)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard T&amp;Cs</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Contract not required</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Internal Transacting</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rebate_Type__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Type__c</fullName>
    <inlineHelpText>What type of rebate structure is being proposed?</inlineHelpText>
    <label>Rebate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tiered - % of Interchange</fullName>
            </value>
            <value>
                <fullName>Tiered - BPS</fullName>
            </value>
            <value>
                <fullName>Straight - % of Interchange</fullName>
            </value>
            <value>
                <fullName>Straight - BPS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <description>This holds the Registration saved on the Completion of the Opportunity Qualify Task</description>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AML Internal Registration</fullName>
            </value>
            <value>
                <fullName>eNett Online Registration</fullName>
            </value>
            <value>
                <fullName>Registration not required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <businessProcess>eNett sales</businessProcess>
    <description>Contract progression: Negotiation, Terms Approved Internally, Pending Client Approval, Contract Signed/ On Hold</description>
    <label>Contract</label>
</RecordType>

force-app/main/default/objects/Process_Task__c/Process_Task__c.object-meta.xml
<CustomObject>
    <label>Process Task</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Process Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Tasks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Task__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>eNett_Contract__r.Account_Name__r.Name</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Agreement_Term_Years__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Term_Years__c</fullName>
    <inlineHelpText>Regional Sales and Legal Approval will be required for entries other than 1,2,3,4,or 5 years.</inlineHelpText>
    <label>Agreement Term (Years)</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Attainable_TTV_Monthly__c.field-meta.xml
<CustomField>
    <fullName>Attainable_TTV_Monthly__c</fullName>
    <label>Attainable GDV Monthly</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Chargeback_Processing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Chargeback_Processing_Fee__c</fullName>
    <inlineHelpText>This is required in order to generate a contract document.</inlineHelpText>
    <label>Chargeback Processing Fee</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard T&amp;Cs</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Contract not required</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Internal Transacting</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/eNett_Contract__c.field-meta.xml
<CustomField>
    <fullName>eNett_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Looks up the &#39;eNett Contract&#39; record to which this Task record is related to.</description>
    <inlineHelpText>Looks up the &#39;eNett Contract&#39; record to which this Task record is related to.</inlineHelpText>
    <label>eNett Contract</label>
    <referenceTo>eNett_Contract__c</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Incentive_Type__c.field-meta.xml
<CustomField>
    <fullName>Incentive_Type__c</fullName>
    <label>Incentive Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>% of Interchange</fullName>
            </value>
            <value>
                <fullName>Fixed %</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Interchange_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interchange_Amount__c</fullName>
    <inlineHelpText>Please input the % of interchange based on the tier level here (usually between 20-50)</inlineHelpText>
    <label>% Interchange Amount</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Process Tasks</relationshipLabel>
    <relationshipName>Process_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Rebate_Type__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Type__c</fullName>
    <label>Rebate Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flat</fullName>
            </value>
            <value>
                <fullName>Tiered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AML Internal Registration</fullName>
            </value>
            <value>
                <fullName>eNett Online Registration</fullName>
            </value>
            <value>
                <fullName>Registration not required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Waiting on someone else</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TEST_ProcessTasks.cls
@isTest
public class TEST_ProcessTasks {
    

    @testSetup 
    static void setupCommonData(){

        System.debug('>>>>>>>>>> Creating Data');

        Account testAccount = TEST_DataFactory.createAccount();
        insert testAccount;
        System.assert(testAccount.Id != null, 'Account not inserted.');

        //Check if a contract was created
//      String contractId = [select Id from eNEtt_Contract__c where Account_Name__c = :testAccount.Id].Id;
//      System.assert(contractId != null, 'Contract not inserted.');

        Contact testContact = TEST_DataFactory.createContact(testAccount.Id);
        insert testContact;
    }

    /**********************************************************************************************
        Test Deal Arrangement Task.
    **********************************************************************************************/

    private static void createDATask(integer intAmnt ){


        Account a = [SELECT Id FROM Account WHERE Name = 'Account Test'];
        System.debug('>>>>>>>>>> Account = ' + a);


        //Check if an Opportunity was created
        String OpportunityId = [select Id from Opportunity where AccountId = :a.Id LIMIT 1].Id;
        System.assert(OpportunityId != null, 'Opportunity not inserted.');

        //Find the QO Task
        Process_Task__c QOTask = [select Id from Process_Task__c where Opportunity__c = :OpportunityId LIMIT 1];
        System.assert(QOTask.Id != null, 'QO Task not inserted.');

        // Complete the Qualify Opp Task
        QOTask.Registration_Type__c = 'AML Internal Registration';
        QOTask.Contract_Type__c ='Custom';
        QOTask.Attainable_TTV_Monthly__c = 1000;
        QOTask.Status__c = 'In Progress';
        update QOTask;

        QOTask.Status__c = 'Completed';
        update QOTask;

        //Check if a contract was created
        String contractId = [select Id from eNEtt_Contract__c where Account_Name__c = :a.Id].Id;
        System.assert(contractId != null, 'Contract not inserted.');

        //Find the Deal Arrangement Task
        Process_Task__c DATask = [select Id from Process_Task__c where eNett_Contract__c = :contractId and Subject__c = 'Contract - Deal Arrangement' LIMIT 1];
        System.assert(DATask.Id != null, 'DA Task not inserted.');

        DATask.Rebate_Type__c = 'Flat';
        DATask.Incentive_Type__c = '% of Interchange';
        DATask.Interchange_Amount__c = intAmnt;
        DATask.Agreement_Term_Years__c = 2;
        DATask.Chargeback_Processing_Fee__c = 2;
        DATask.Subscription_Fee__c = 2;
        DATask.Status__c = 'Completed';
        update DATask;


        // Delete to give some coverage to PT_noDeleteTask.trigger
        delete DATask;

    }

    /**********************************************************************************************
        Complete Deal Arrangement Tasks at different Levels.
    **********************************************************************************************/

    static testmethod void TEST_Trigger_TaskAfter_DA1() {
      //createDATask(2);
    }

    //@isTest static void TEST_Trigger_TaskAfter_DA2() {
    //  createDATask(30);
    //}

    //@isTest static void TEST_Trigger_TaskAfter_DA3() {
    //  createDATask(45);
    //}

    //@isTest static void TEST_Trigger_TaskAfter_DA4() {
    //  createDATask(55);
    //}
    
}