force-app/main/default/objects/Account/fields/T_C_Accepted_Date__c.field-meta.xml
<CustomField>
    <fullName>T_C_Accepted_Date__c</fullName>
    <inlineHelpText>Automatically set based on the date the standard T&amp;Cs were accepted by the customer.</inlineHelpText>
    <label>T&amp;C Accepted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/eNett_Contract__c.object-meta.xml
<CustomObject>
    <label>eNett Contract</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>eNett Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>eNett Contract</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/eNett_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>eNett Contract</relationshipLabel>
    <relationshipName>eNett_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/eNett_Contract__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard T&amp;Cs</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Contract not required</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Internal Transacting</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/eNettContractControllerExtension.cls
public with sharing class eNettContractControllerExtension {
    
    public eNettContractControllerExtension(ApexPages.StandardController stdController) {
        
        eNett_Contract__c theContract = [Select Contract_Type__c, Account_Name__c From eNett_Contract__c where Id = :stdController.getRecord().Id];
        if (String.isBlank(theContract.Contract_Type__c)) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'This Contract will not proceed without a valid Contract Type. Registration is responsible for populating this field.')); }

        Account theAccount = [Select T_C_Accepted_Date__c From Account where Id = :theContract.Account_Name__c];
        if ( theContract.Contract_Type__c == 'Standard T&Cs' && theAccount.T_C_Accepted_Date__c == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'This Contract will not proceed without a valid T & C Accepted Date on the Account. This field will be automatically set by the Registration system.')); }            
    }
}