force-app/main/default/objects/Director__c/Director__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpDirectors</customHelpPage>
    <label>Director</label>
    <nameField>
        <displayFormat>DIR-{000000}</displayFormat>
        <label>Director ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Directors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Director__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Directors</relationshipLabel>
    <relationshipName>Directors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ObjectReferenceIds__c/ObjectReferenceIds__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>For storing SF Ids of custom field etc which need to be referenced by javascript buttons</description>
    <label>Object Reference Ids</label>
</CustomObject>

force-app/main/default/objects/ObjectReferenceIds__c/fields/Director_Active_Registration__c.field-meta.xml
<CustomField>
    <fullName>Director_Active_Registration__c</fullName>
    <label>Director Active Registration</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjectReferenceIds__c/fields/Director_Object_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Director_Object_Prefix__c</fullName>
    <label>Director Object Prefix</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ObjectReferenceIds__c/fields/Director_Registration__c.field-meta.xml
<CustomField>
    <fullName>Director_Registration__c</fullName>
    <label>Director Registration</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Private Company</fullName>
            </value>
            <value>
                <fullName>Public Company</fullName>
            </value>
            <value>
                <fullName>Sole Trader</fullName>
            </value>
            <value>
                <fullName>Trusts/Foundation</fullName>
            </value>
            <value>
                <fullName>Regulated Firm</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Association/Club</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PopUpDialog_DirectorExts.cls
public class PopUpDialog_DirectorExts {

    public class deactivate extends PopUpDialogController.contExt {

        private Director__c dir {get; set;}

        public deactivate(Id recId) {
            dir = new Director__c(Id = recId);
        }       
        
        public override String runProcess() {
            dir.Active__c = false;
            update dir;
            return null;
        }
  
        public override String showConfirmMsg() {
            return 'You are about to deactivate the Director for this Registration. Are you sure you want to continue?';
        }

    }    
    
    public class newDirector extends PopUpDialogController.contExt {

        private Registration__c reg {get; set;}

        public newDirector(Id recId) {
            reg = [SELECT Id, Name, Business_Type__c FROM Registration__c WHERE Id = :recId];
        }

        public override String runValidation() {
            if (reg.Business_Type__c == 'Partnership' || reg.Business_Type__c == 'Sole Trader')
                return 'Cannot add a director to this business type';
            return null;
        }

        public override String runProcess() {
            String return_URL = null;
            ObjectReferenceIds__c objRef = ObjectReferenceIds__c.getOrgDefaults();
            return_URL = '/' + objRef.Director_Object_Prefix__c;
            return_URL += '/e?CF' + objRef.Director_Active_Registration__c + '=' + reg.Name;
            return_URL += '&CF' + objRef.Director_Active_Registration__c + '_lkid=' + reg.Id;
            return_URL += '&CF' + objRef.Director_Registration__c + '=' + reg.Name;
            return_URL += '&CF' + objRef.Director_Registration__c + '_lkid=' + reg.Id;
            return_URL += '&retURL=/%2F' + reg.Id+ '&nooverride=1';
            return return_URL;
        }
 
        public override String showConfirmMsg() {
            return 'You are about to create a new director. Are you sure you want to continue?';
        }

    }    

}