force-app/main/default/objects/Director__c/Director__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpDirectors</customHelpPage>
    <label>Director</label>
    <nameField>
        <displayFormat>DIR-{000000}</displayFormat>
        <label>Director ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Directors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Director__c/fields/PEP__c.field-meta.xml
<CustomField>
    <fullName>PEP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PEP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Director__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Directors</relationshipLabel>
    <relationshipName>Directors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Journal__c/Journal__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpJournals</customHelpPage>
    <label>DD Journal</label>
    <nameField>
        <label>Journal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DD Journal</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Journal__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipName>Internal_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PEP__c/PEP__c.object-meta.xml
<CustomObject>
    <label>PEP</label>
    <nameField>
        <displayFormat>PEP-{0000}</displayFormat>
        <label>PEP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PEPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PEP__c/fields/Director__c.field-meta.xml
<CustomField>
    <fullName>Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director</label>
    <referenceTo>Director__c</referenceTo>
    <relationshipLabel>PEPs</relationshipLabel>
    <relationshipName>PEPs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PEP__c/fields/In_office__c.field-meta.xml
<CustomField>
    <fullName>In_office__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If the PEP is still in office</inlineHelpText>
    <label>In office</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PEP__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Principal Signatory PEPs</relationshipLabel>
    <relationshipName>PEPs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/PEP__c.field-meta.xml
<CustomField>
    <fullName>PEP__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This option must be selected if the Principal Signatory has been identified as PEP.  If selected, PEP details are added in the Principal Signatory PEPs section.</inlineHelpText>
    <label>PEP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registered_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Registered_Company_Name__c</fullName>
    <label>Registered Company Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestFieldAuditTriggers.cls
@istest
public class TestFieldAuditTriggers {

    public static testMethod void testFieldAuditTriggers() {

        // This provides minimal code coverage to allow trigger deployment => should be updated to actually test field auditing

        Registration__c reg = new Registration__c(Registered_Company_Name__c='ACME Travel');
        insert reg;
        
        Director__c dr = new Director__c(Registration__c = reg.Id);
        insert dr;

        Journal__c jn = new Journal__c(Registration__c = reg.Id);
        insert jn;

        PEP__c pep = new PEP__c(In_office__c = true);
        insert pep;
        
        update dr;
        update jn;
        update pep;        
    }
    
}