force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Additional ECN</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Channel Agreement</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>eNett Internal</fullName>
            </value>
            <value>
                <fullName>eNett Internal Demo</fullName>
            </value>
            <value>
                <fullName>eNett Internal Transacting</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>Referred Client</fullName>
            </value>
            <value>
                <fullName>Referrer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Bank_Account__c/Registration_Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Registration Bank Account</label>
    <nameField>
        <displayFormat>RBA-{000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Bank_Account__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payable</fullName>
            </value>
            <value>
                <fullName>Receivable</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration_Bank_Account__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Registration_Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Bank_Account__c/fields/Verification__c.field-meta.xml
<CustomField>
    <fullName>Verification__c</fullName>
    <formula>verFlag__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration_Bank_Account__c/recordTypes/Funding.recordType-meta.xml
<RecordType>
    <fullName>Funding</fullName>
    <active>true</active>
    <label>Funding</label>
</RecordType>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpVerification</customHelpPage>
    <label>Verification</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Verification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Evidence_Type__c.field-meta.xml
<CustomField>
    <fullName>Evidence_Type__c</fullName>
    <label>Evidence Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered Company Name</fullName>
            </value>
            <value>
                <fullName>Registered Business Number</fullName>
            </value>
            <value>
                <fullName>Trading Name</fullName>
            </value>
            <value>
                <fullName>Business Address</fullName>
            </value>
            <value>
                <fullName>Principal Signatory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Purpose__c.field-meta.xml
<CustomField>
    <fullName>Purpose__c</fullName>
    <label>Purpose</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ADD</fullName>
            </value>
            <value>
                <fullName>EDD</fullName>
            </value>
            <value>
                <fullName>PEP</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Other (Provide Note)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipName>Company_Information_Evidence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Registration_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Registration_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration Bank Account</label>
    <referenceTo>Registration_Bank_Account__c</referenceTo>
    <relationshipName>Information_Evidence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvocableMethodsTest.cls
@isTest
public class InvocableMethodsTest {
    
    @isTest static void testAccountTypeFunding(){
        //Data Setup
        Registration__c testReg = eNettTestUtility.createRegistration('testCompany');
        List<Id> regIds = new List<Id>();
        regIds.add(testReg.Id);
        Registration_Bank_Account__c testBankAccount = eNettTestUtility.createRegistrationBankAccount(testReg.Id);
        testBankAccount.Account_Type__c ='Funding';
        update testBankAccount;
        Verification__c testVer = new Verification__c(Registration_Bank_Account__c = testBankAccount.Id,
                                                     Evidence_Type__c = 'Trading Name',
                                                     Purpose__c = 'ADD');
        insert testVer;
        
        //Perform Test
        test.startTest();
        InvocableMethods.SetAccountsAndVersToReadOnly(regIds);
        test.stopTest();
        
        //Verify Test
        List<Registration_Bank_Account__c> testbAs = [SELECT Account_Type__c FROM Registration_Bank_Account__c
                                                      WHERE Registration__c IN :regIds];
        System.assertEquals(testbAs[0].Account_Type__c, 'Funding');
        List<Verification__c> testVer2 = [SELECT Id, RecordTypeId FROM Verification__c WHERE Registration_Bank_Account__c IN :regIds ];
        if (testVer2.size() > 0){
			System.assertEquals(testVer2[0].RecordTypeId, '01290000001Iirn');
        }
    }
    
        @isTest static void testAccountTypeNotFunding(){
        //Data Setup
        Registration__c testReg = eNettTestUtility.createRegistration('testCompany');
        List<Id> regIds = new List<Id>();
        regIds.add(testReg.Id);
        Registration_Bank_Account__c testBankAccount = eNettTestUtility.createRegistrationBankAccount(testReg.Id);
        testBankAccount.Account_Type__c ='Billing';
        update testBankAccount;
        Verification__c testVer = new Verification__c(Registration_Bank_Account__c = testBankAccount.Id,
                                                     Evidence_Type__c = 'Business Address',
                                                     Purpose__c = 'PEP');
        insert testVer;
        
        //Perform Test
        test.startTest();
        InvocableMethods.SetAccountsAndVersToReadOnly(regIds);
        test.stopTest();
        
        //Verify Test
        List<Registration_Bank_Account__c> testbAs = [SELECT Account_Type__c FROM Registration_Bank_Account__c
                                                      WHERE Registration__c IN :regIds];
        System.assertEquals(testbAs[0].Account_Type__c, 'Billing');
        List<Verification__c> testVer2 = [SELECT Id, RecordTypeId FROM Verification__c WHERE Registration_Bank_Account__c IN :regIds ];
        if (testVer2.size() > 0){
			System.assertEquals(testVer2[0].RecordTypeId, '01290000001Iirn');
        }
    }
}