force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Products</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VANs</fullName>
            </value>
            <value>
                <fullName>feeNett</fullName>
            </value>
            <value>
                <fullName>VirtualTerminal</fullName>
            </value>
            <value>
                <fullName>eNett EFT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RemoveProductReg.cls
global class RemoveProductReg {

    @InvocableMethod (label='Remove Product Registration')
    global static void RemoveProductFromReg (LIST<RemoveProductActionRequest> requests) {

        SET<Id> regIds = new SET<Id>();
        MAP<Id, Registration__c> regMap = new MAP<Id, Registration__c>();
        LIST<Registration__c> regsUpdate = new LIST<Registration__c>();
    
        for (RemoveProductActionRequest request : requests) {
            regIds.add(request.RegId);
        }
        
        for (Registration__c a : [SELECT Id, product__c FROM Registration__c WHERE Id IN: regIds]) {
            regMap.put(a.Id, a);
        }

        Registration__c reg;
        LIST<String> products;

        for (RemoveProductActionRequest request : requests) {
            reg = regMap.get(request.RegId);
            products = new LIST<String>();
            for (String p : reg.product__c.split(';')) {
                if (p != request.productName) {
                    products.add(p);
                }
            }
            reg.product__c = String.join(products, ';');
            regsUpdate.add(reg);
        }
        
        update regsUpdate;
    }
    
    global class RemoveProductActionRequest {
        @InvocableVariable(required=true)
        public ID RegId;

        @InvocableVariable(required=true)
        public String productName;
    }
    
}