force-app/main/default/objects/DD_Config__c/DD_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>DD Configuration</label>
</CustomObject>

force-app/main/default/objects/DD_Config__c/fields/Can_Approve_High_Risk_DD__c.field-meta.xml
<CustomField>
    <fullName>Can_Approve_High_Risk_DD__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When ticked, this user/profile can approve high risk DD tasks.</description>
    <label>Can Approve High Risk DD?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Due_Diligence_Approval__c/Due_Diligence_Approval__c.object-meta.xml
<CustomObject>
    <label>Due Diligence Approval</label>
    <nameField>
        <displayFormat>DDA-{000000}</displayFormat>
        <label>Approval ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Due Diligence Approval</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Due_Diligence_Approval__c/fields/Risk_Rating__c.field-meta.xml
<CustomField>
    <fullName>Risk_Rating__c</fullName>
    <formula>Registration__r.Risk_Rating__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Risk Rating</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Due_Diligence_Approval__c/fields/Submitted_By__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Submitted By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Due_Diligence_Approval</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PopUpDialog_DDApprovalExts.cls
public class PopUpDialog_DDApprovalExts {

    public class approve extends PopUpDialogController.contExt {
        private Due_Diligence_Approval__c ddAppr {get; set;}
        Id userId;
        Boolean rightToApprove;
        
       
        public approve(Id recId) {
            ddAppr = PopUpDialog_DDApprovalExts.loadDDApproval(recId);
            DD_Config__c ddConfig = DD_Config__c.getInstance(UserInfo.getUserId());
            rightToApprove = ddConfig.Can_Approve_High_Risk_DD__c;
        }    
            
        public override String runValidation() {
            return null;
        }
   
        public override String showConfirmMsg() {
            return null;
        }
    
    }

    public static Due_Diligence_Approval__c loadDDApproval(Id recId) {
        Due_Diligence_Approval__c ddA;
        ddA = [SELECT Id, Submitted_By__c, Risk_Rating__c
               FROM Due_Diligence_Approval__c
               WHERE Id = :recId];
        return ddA;
    }

}