force-app/main/default/objects/Lead/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State of</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Notes_History__c.field-meta.xml
<CustomField>
    <fullName>Lead_Notes_History__c</fullName>
    <label>Lead Notes History</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referrer_Code__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Code__c</fullName>
    <label>Introducer / Referrer Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Referrer_Name__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Name__c</fullName>
    <label>Introducer / Referrer Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>About Payments</fullName>
            </value>
            <value>
                <fullName>Adyen</fullName>
            </value>
            <value>
                <fullName>Agoda</fullName>
            </value>
            <value>
                <fullName>Air Asia</fullName>
            </value>
            <value>
                <fullName>Axess International Network, Inc</fullName>
            </value>
            <value>
                <fullName>Blue Team Travel Network SRL</fullName>
            </value>
            <value>
                <fullName>CCRA International</fullName>
            </value>
            <value>
                <fullName>CEE Travel System</fullName>
            </value>
            <value>
                <fullName>Club Travel SA</fullName>
            </value>
            <value>
                <fullName>Computop</fullName>
            </value>
            <value>
                <fullName>Conferma</fullName>
            </value>
            <value>
                <fullName>Contac Services</fullName>
            </value>
            <value>
                <fullName>Cornerstone</fullName>
            </value>
            <value>
                <fullName>Dolphin Dynamics</fullName>
            </value>
            <value>
                <fullName>Flightgenius</fullName>
            </value>
            <value>
                <fullName>Gant Travel Management</fullName>
            </value>
            <value>
                <fullName>Gateway</fullName>
            </value>
            <value>
                <fullName>Geo Travel Network Di Geo Spa</fullName>
            </value>
            <value>
                <fullName>Globalcollect</fullName>
            </value>
            <value>
                <fullName>Globalstar</fullName>
            </value>
            <value>
                <fullName>HitchHiker</fullName>
            </value>
            <value>
                <fullName>Hotelzon</fullName>
            </value>
            <value>
                <fullName>IGA Voyages</fullName>
            </value>
            <value>
                <fullName>Juniper</fullName>
            </value>
            <value>
                <fullName>Manor</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Mr Orange</fullName>
            </value>
            <value>
                <fullName>Multicom</fullName>
            </value>
            <value>
                <fullName>Navitas</fullName>
            </value>
            <value>
                <fullName>Orchestra</fullName>
            </value>
            <value>
                <fullName>Travelport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Americas</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/Referrer.recordType-meta.xml
<RecordType>
    <fullName>Referrer</fullName>
    <active>true</active>
    <businessProcess>Leads eNett</businessProcess>
    <description>A Company (eNett client or non eNett client) refers eNett products to other companies.</description>
    <label>Referrer</label>
</RecordType>

force-app/main/default/objects/ReferrerCodes__c/ReferrerCodes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ReferrerCodes</label>
</CustomObject>

force-app/main/default/objects/ReferrerCodes__c/fields/ReferrerCode__c.field-meta.xml
<CustomField>
    <fullName>ReferrerCode__c</fullName>
    <description>This holds the ReferrerCode (ECN) for the referrers listed in the Introducer/Referrer Name on the Lead</description>
    <label>ReferrerCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TEST_Trigger_PopulateLeadDetails.cls
@isTest
private class TEST_Trigger_PopulateLeadDetails {
    
    @isTest static void test_PopulateLeadDetails() {
    	
    	
    	insert new ReferrerCodes__c(Name = 'Agoda', ReferrerCode__c = 'Agoda');
    	insert new ReferrerCodes__c(Name = 'Travelport', ReferrerCode__c = 'Travelport');

        /***********************************************
            Test the Insert behaviour with Notes
        ***********************************************/

        // Setup a Lead with notes
        Lead theLead_Notes = new Lead(  Company = 'TestCompany1',
                                    LastName = 'TestLast1',
                                    FirstName = 'TestFirst1',
                                    Brand_Name__c = 'Test Brand1',
                                    LeadSource = 'Other',
                                    Country__c = 'Australia',
                                    Referrer_Name__c = 'Agoda',
                                    Lead_Notes__c = 'A Note'
                                );

        // Insert our Lead
        insert theLead_Notes;
        System.assert(theLead_Notes.Id != null, 'Lead not inserted.');


        /***********************************************
            Test the Insert behaviour without Notes
        ***********************************************/

        // Setup our Lead
        Lead theLead = new Lead(    Company = 'ZZZZCompany',
                                    LastName = 'ZZZZCompany',
                                    FirstName = 'TestFirst1',
                                    Brand_Name__c = 'Test Brand2',
                                    LeadSource = 'Other',
                                    Country__c = 'Australia',
                                    Referrer_Name__c = 'Agoda'
                                );

        // Insert our Lead
        insert theLead;
        System.assert(theLead.Id != null, 'Lead not inserted.');

        // Requery the Lead
        Lead chkLead = [Select  Id, 
                                Country__c, 
                                Region__c, 
                                Referrer_Name__c, 
                                Referrer_Code__c, 
                                Lead_Notes__c, 
                                Lead_Notes_History__c 
                        from Lead where Id = :theLead.Id];

        // Validate our Insert fields
        System.AssertNotEquals(null, chkLead.Referrer_Code__c, 'Lead Referrer Code not assigned.');


        /***********************************************
            Test the Update behaviour
        ***********************************************/

        // Save or initial values
        string oldReferrerCode = chkLead.Referrer_Code__c;
        string oldNotesHistory = chkLead.Lead_Notes_History__c;

        // Set the values for update
        chkLead.Country__c = 'United States';
        chkLead.Referrer_Name__c = 'Travelport';
        chkLead.Lead_Notes__c = 'Notes';

        // Update the Lead
        update chkLead;

        // Requery Lead and Validate fields
        Lead chkLeadAfter = [Select     Id, 
                                Country__c, 
                                Region__c, 
                                Referrer_Name__c, 
                                Referrer_Code__c, 
                                Lead_Notes__c, 
                                Lead_Notes_History__c 
                        from Lead where Id = :theLead.Id];

        System.Assert(chkLeadAfter.Referrer_Code__c <> null && chkLeadAfter.Referrer_Code__c <> oldReferrerCode, 'Lead ReferrerCode not updated on update of Lead.');
        System.AssertEquals(null, chkLeadAfter.Lead_Notes__c, 'Lead notes not cleared.');
        System.Assert(chkLeadAfter.Lead_Notes_History__c <> null && chkLeadAfter.Lead_Notes_History__c <> oldNotesHistory, 'Lead Notes History not updated on update of Lead.');


        /***********************************************
            Run another test for Update behaviour with 
            notes appended.
            Added for test coverage.
        ***********************************************/

        chkLeadAfter.Lead_Notes__c = 'MoreNotes';
        update chkLeadAfter;
    }
    
}