force-app/main/default/objects/Opportunity/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Delivery - Desktop</fullName>
            </value>
            <value>
                <fullName>Delivery - API</fullName>
            </value>
            <value>
                <fullName>Delivery Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <formula>Account.ECN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ECN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Record_Outcome_Created__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Outcome_Created__c</fullName>
    <label>Opportunity Record Outcome Created</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Record_Outcome_Due__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Outcome_Due__c</fullName>
    <label>Opportunity Record Outcome Due</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Record_Outcome_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Record_Outcome_Name__c</fullName>
    <label>Opportunity Record Outcome Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/Process_Task__c.object-meta.xml
<CustomObject>
    <label>Process Task</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Process Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Tasks</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Task__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>eNett_Contract__r.Account_Name__r.Name</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/Delivery_Type__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Type__c</fullName>
    <label>Delivery Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery - Desktop</fullName>
            </value>
            <value>
                <fullName>Delivery - API</fullName>
            </value>
            <value>
                <fullName>Delivery Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Task__c/fields/ECN__c.field-meta.xml
<CustomField>
    <fullName>ECN__c</fullName>
    <label>ECN</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Process_Task__c/recordTypes/Opportunity_Record_Opportunity_Outcome.recordType-meta.xml
<RecordType>
    <fullName>Opportunity_Record_Opportunity_Outcome</fullName>
    <active>true</active>
    <label>Opportunity Record Opportunity Outcome</label>
</RecordType>

force-app/main/default/classes/ScheduledCreateOppRecordOutcomeTasks.cls
global class ScheduledCreateOppRecordOutcomeTasks implements Schedulable {

    global void execute(SchedulableContext sc) {
        List<Process_Task__c> oppTaskList = new List<Process_Task__c>();
        List<Opportunity> oppUpdates = new List<Opportunity>();
        Map<string,RecordType> recTypeMap = FutureCalls.mapRecordTypes('Process_Task__c');
        
        Date today_plus_1month = date.today().addDays(30);
        for (Opportunity opp : [SELECT Id, OwnerId, Account_Name__c, Delivery_type__c, ECN__c, Opportunity_Record_Outcome_Due__c, Opportunity_Record_Outcome_Created__c
                                FROM Opportunity 
                                WHERE Opportunity_Record_Outcome_Due__c = :today_plus_1month]) {
            if (opp.Opportunity_Record_Outcome_Created__c == null) {
                oppTaskList.add(
                    PT_Utils.createOpportunityPT(opp.OwnerId, recTypeMap.get('Opportunity_Record_Opportunity_Outcome').Id, opp.Account_Name__c, 
                                                 opp.Delivery_type__c, opp.ECN__c, 'Opportunity - Record Opportunity Outcome', 
                                                 opp.Id, opp.Opportunity_Record_Outcome_Due__c)
                );
                opp.Opportunity_Record_Outcome_Created__c = System.today();
                opp.Opportunity_Record_Outcome_Name__c = 'Opportunity - Record Opportunity Outcome';
                oppUpdates.add(opp);
            }
        }
        if (!oppTaskList.isEmpty()) insert oppTaskList;
        if (!oppUpdates.isEmpty()) update oppUpdates;
    }
    
    public static string defaultSchedule = '0 0 * * * ?';
   
    public static void schedule() {
        ScheduledCreateOppRecordOutcomeTasks.schedule(defaultSchedule);
    }

    public static void schedule(string sch) {
        ScheduledCreateOppRecordOutcomeTasks m = new ScheduledCreateOppRecordOutcomeTasks();
        system.schedule('ScheduledCreateRecordOppOutcomeTasks', sch, m);
    }

}