force-app/main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <label>Contact Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Operational</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Financial_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Financial_Email_Address__c</fullName>
    <label>Financial Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <inlineHelpText>This field is automatically populated by the Client system integration.</inlineHelpText>
    <label>Job Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Master administrator</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Delivery Implementation</fullName>
            </value>
            <value>
                <fullName>Operational / Technical</fullName>
            </value>
            <value>
                <fullName>Operational / Technical SMEs</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_Address__c</fullName>
    <label>Primary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Secondary_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Email_Address__c</fullName>
    <label>Secondary Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <inlineHelpText>This field is automatically populated by the Eloqua integration.</inlineHelpText>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administration</fullName>
            </value>
            <value>
                <fullName>Business Owner/Proprietor</fullName>
            </value>
            <value>
                <fullName>Chairperson</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>CIO</fullName>
            </value>
            <value>
                <fullName>CMO</fullName>
            </value>
            <value>
                <fullName>COO</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Travel Consultant</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <label>Agreement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard T&amp;Cs</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>From Lead</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>From Lead</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>From Lead</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>From Lead</description>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Miss</fullName>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Mr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateContactJobRole.cls
public class UpdateContactJobRole {

    @InvocableMethod
    public static void UpdateContactJobRoleFromReg (LIST<ID> regIds) {
    
        MAP<Id, Registration__c> accIdRegMap = new MAP<Id, Registration__c>();
        Registration__c reg;
        LIST<Contact> contUpdates = new LIST<Contact>();
        LIST<Contact> newContacts = new LIST<Contact>();
        //SET<Id> accsWithMatchingContacts = new SET<Id>();
        
        for (Registration__c r : [SELECT Id, Salutation__c, First_Name__c, Last_Name__c, Job_Role__c, Account__c, Email__c, Phone__c FROM Registration__c WHERE Id IN :regIds AND Agreement_Type__c = 'Affiliate']) {
            If (r.Account__c != null) {
                accIdRegMap.put(r.Account__c, r);
            }
        }
        
        /*
        for (Contact c : [SELECT Id, FirstName, LastName, AccountId FROM Contact WHERE AccountId IN :accIdRegMap.keySet()]) {           
            reg = accIdRegMap.get(c.AccountId);
            If (c.FirstName == reg.First_Name__c && c.LastName == reg.Last_Name__c) {
                if (c.Contact_Type__c != reg.Job_Role__c) {
                    c.Contact_Type__c = reg.Job_Role__c;
                    contUpdates.add(c);
                }
                accsWithMatchingContacts.add(c.AccountId);
            }   
        }
        */

        for (Id aId : accIdRegMap.keySet()) {
            //if (!accsWithMatchingContacts.contains(aId)) {
                reg = accIdRegMap.get(aId);
                newContacts.add(new Contact(Salutation = reg.Salutation__c,
                                            FirstName = reg.First_Name__c,
                                            LastName = reg.Last_Name__c,
                                            Email = reg.Email__c,
                                            Primary_Email_Address__c = reg.Email__c,
                                            Secondary_Email_Address__c = reg.Email__c,
                                            Financial_Email_Address__c = reg.Email__c,
                                            Phone = reg.Phone__c,
                                            Job_Role__c = 'Primary; Secondary; Financial',
                                            AccountId = reg.Account__c,
                                            Title__c = reg.Job_Role__c));
            //}
        }
        
        
        //update contUpdates;
        insert newContacts;
    }

}