force-app/main/default/objects/CountryMappings__c/CountryMappings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Country, ISO Code and Region.  Source for data Ref: http://data.okfn.org/data/core/country-codes</description>
    <label>Country</label>
</CustomObject>

force-app/main/default/objects/CountryMappings__c/fields/Category_1_Country__c.field-meta.xml
<CustomField>
    <fullName>Category_1_Country__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Category 1 Country</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Åland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
                <default>true</default>
                <label>Australia</label>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia, Plurinational State</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/eNett.recordType-meta.xml
<RecordType>
    <fullName>eNett</fullName>
    <active>true</active>
    <businessProcess>eNett sales</businessProcess>
    <label>eNett</label>
</RecordType>

force-app/main/default/classes/OpportunityControllerExtension.cls
public with sharing class OpportunityControllerExtension {
    
    public OpportunityControllerExtension(ApexPages.StandardController stdController) {
        
    	String Message;
        Message = '';

        Opportunity theOpportunity = [Select LeadSource, CampaignId, Country__c From Opportunity where Id = :stdController.getRecord().Id];
        if ((theOpportunity.LeadSource == 'eNett Campaign' || theOpportunity.LeadSource == 'Partner Campaign' || theOpportunity.LeadSource == 'Industry Event') && string.IsBlank(theOpportunity.CampaignId)) {
			Message = 'Please link this Opportunity to a Campaign.';
        }            

// *** SF-1366 Removed reference to Category 1 Country
//		if (CountryMappings__c.getInstance(theOpportunity.Country__c).Category_1_Country__c == false) {
//			if (String.isBlank(Message)) {
//				Message = 'The Country associated with this Opportunity is not a Category 1 Country and therefore registration cannot be processed.'; }
//			else {
//				Message = 'This Opportunity is not linked to a Campaign and is not associated with a Category 1 Country.';
//			}
//        }

        if (String.isNotBlank(Message)) ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, Message));

    }
}