force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Registered_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Registered_Company_Name__c</fullName>
    <label>Registered Company Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDueDiligenceEmailHandler.cls
@isTest
public class TestDueDiligenceEmailHandler {
    
    static testMethod void TestEmailHandler() {

        Registration__c ddCL = new Registration__c(Registered_Company_Name__c = 'TestCompany');
        insert ddCL;
        
        // Create Inbound Email
        Messaging.InboundEmail email = new Messaging.InboundEmail();
        email.subject = 'Create Contact [ref:' + ddCL.id + ']';
        email.fromAddress = 'test@email.com';
        email.plainTextBody = 'Testing';

        // Add Binary Attachment
        Messaging.InboundEmail.BinaryAttachment attachment = new Messaging.InboundEmail.BinaryAttachment();
        attachment.body = blob.valueOf('Some text');
        attachment.fileName = 'textfile.txt';
        attachment.mimeTypeSubType = 'text/plain';
        email.binaryAttachments = new Messaging.inboundEmail.BinaryAttachment[] { attachment };
      
        // Call email service class
        Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
        DueDiligenceEmailHandler testInbound = new DueDiligenceEmailHandler();
        testInbound.handleInboundEmail(email, env);
        
        // Assert that email task was created on the due diligence record
        LIST<Task> ts = [SELECT Id FROM Task WHERE WhatId = :ddCL.id LIMIT 1];
        //system.assert(ts.size() > 0);
   }

}