force-app/main/default/objects/RegoSettings__c/RegoSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This needs to be set for use by the External Rego.</description>
    <label>Rego Settings</label>
</CustomObject>

force-app/main/default/objects/RegoSettings__c/fields/sfdcHostAccountSetup__c.field-meta.xml
<CustomField>
    <fullName>sfdcHostAccountSetup__c</fullName>
    <label>Host Account setup Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegoSettings__c/fields/sfdcHostName__c.field-meta.xml
<CustomField>
    <fullName>sfdcHostName__c</fullName>
    <label>SF Host Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Detail__c/State_Detail__c.object-meta.xml
<CustomObject>
    <label>State Detail</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PostRefreshCtrlTest.cls
@isTest (seeAllData = true) 
public class PostRefreshCtrlTest {
    //Test PostRefreshCtrl constructor
    @isTest static void testPostRefreshCtrlConstructor(){
        PostRefreshCtrl prc = new PostRefreshCtrl();
    }
    
    //Test changeEmail method
    @isTest static void testChangeEmail(){
        
        Test.startTest();
        PostRefreshCtrl prc = new PostRefreshCtrl();
        prc.changeEmail();
        Test.stopTest();
        
        List<Group> selectedGroup = [SELECT Id,Name FROM Group WHERE Name LIKE '%System Admin/Developer%' LIMIT 1];
        List<GroupMember> groupMember = [SELECT GroupId,Id,UserOrGroupId FROM GroupMember WHERE GroupId =: selectedGroup];
        List<Id> userIdList = new List<Id>();
        for (GroupMember gm : groupMember){
            userIdList.add(gm.UserOrGroupId);
        }
        List<User> testuserList = [SELECT Id, ProfileId, Email FROM User WHERE Id IN: userIdList];
        //Can't test profile as this change is execute 1 hour later, might cause the test to fail
        //Profile sysAd = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        for (User u : testuserList){
            System.assertEquals(u.Email.indexof('.invalid'), -1);
            //System.assertEquals(u.ProfileId, sysAd.Id);
        }
    }
    
    //Test activateAndDeactivateUsers method
    @isTest static void activateAndDeactivateUsers(){
        //Run this test case only in Sandboxes.
        Organization org = [SELECT isSandbox FROM Organization LIMIT 1];
        if(org.IsSandbox){
            Test.startTest();
            PostRefreshCtrl prc = new PostRefreshCtrl();
            prc.activateAndDeactivateUsers();
            Test.stopTest();
            
            String[] activateAndDeactiveUsers = new String[]{'salesforce.testautomation@enett.com%','sf_deploy_prd@enett.com%','sf_deploy_tst@enett.com%'};
            List<User> activateDeactivateUserList = [SELECT Id, Email, IsActive from USER WHERE EMAIL LIKE :activateAndDeactiveUsers];
            for(User actDeactuser : activateDeactivateUserList){
                if(actDeactuser.Email.contains('salesforce.testautomation@enett.com')){
                    System.assertEquals(actDeactuser.IsActive, TRUE); 
                }
                else if(actDeactuser.Email.contains('sf_deploy_prd@enett.com')){
                    System.assertEquals(actDeactuser.IsActive, FALSE); 
                }
                else if(actDeactuser.Email.contains('sf_deploy_tst@enett.com')){ 
                    System.assertEquals(actDeactuser.IsActive, TRUE); 
                }
            }
        } 
    }
    
     //Test changeProfile method
    @isTest static void testChangeProfile(){
        //Run this test case only in Sandboxes.
        Organization org = [SELECT isSandbox FROM Organization LIMIT 1];
        if(org.IsSandbox){
            Test.startTest();
            PostRefreshCtrl prc = new PostRefreshCtrl();
            prc.changeProfile();
            Test.stopTest();
            
            List<Group> selectedGroup = [SELECT Id,Name FROM Group WHERE Name LIKE '%System Admin/Developer%' LIMIT 1];
            List<GroupMember> groupMember = [SELECT GroupId,Id,UserOrGroupId FROM GroupMember WHERE GroupId =: selectedGroup];
            List<Id> userIdList = new List<Id>();
            for (GroupMember gm : groupMember){
                userIdList.add(gm.UserOrGroupId);
            }
            List<User> testuserList = [SELECT Id, ProfileId, Email FROM User WHERE Id IN: userIdList];
            Profile sysAd = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
            for (User u : testuserList){
                System.assertEquals(u.ProfileId, sysAd.Id);
            }
        }
    }
    
    //Test updateSiteSetting method
    @isTest static void testUpdateSiteSetting(){
        
        Test.startTest();
        PostRefreshCtrl prc = new PostRefreshCtrl();
        prc.updateSiteSetting();
        Test.stopTest();
        
        RegoSettings__c testrs = [SELECT Id, Name, sfdcHostName__c, sfdcHostAccountSetup__c FROM RegoSettings__c];
        String sandboxName = UserInfo.getUserName().substringAfterLast('.');
        Site st = [SELECT Id, Subdomain, urlPathPrefix FROM Site WHERE Name = 'eNettRegistration' LIMIT 1];
        String subDomain = st.Subdomain;
        String urlPathPrefix = st.urlPathPrefix;
        Organization org = [SELECT Id, InstanceName FROM Organization LIMIT 1];
        String instanceName = org.InstanceName.toLowerCase();
        String correctURL = sandboxName + '-' + subDomain + '.' + instanceName + '.force.com/' + urlPathPrefix;
        
        //SF-5182 04/09/2018 Jasmine - Temporary took out this assessment so unit test works while waiting for My Domain to be implemented 
        //System.assertEquals(correctURL, testrs.sfdcHostName__c);
        //System.assertEquals(correctURL, testrs.sfdcHostAccountSetup__c);
    }
    
    //Test updateMessageDialog method
    @isTest static void testUpdateMessageDialog(){
        
        Test.startTest();
        PostRefreshCtrl prc = new PostRefreshCtrl();
        prc.updateMessageDialog();
        Test.stopTest();
        
        List<bigiant_dialog__bDialog__c> dialogList = [SELECT Id FROM bigiant_dialog__bDialog__c];
        System.assertNotEquals(0, dialogList.size());
        Organization myOrg = [SELECT Id,InstanceName From Organization];
        String instanceName = myOrg.InstanceName.toLowerCase();
        String correctURL = 'https://c.' + instanceName + '.visual.force.com/apex/PopUpDialog';
        bigiant_dialog__bDialog__c testDialog = [SELECT Id, bigiant_dialog__Content_url__c FROM bigiant_dialog__bDialog__c
                                                 WHERE bigiant_dialog__Title__c = 'Message Dialog' LIMIT 1];
        //SF-5182 04/09/2018 Jasmine - Temporary took out this assessment so unit test works while waiting for My Domain to be implemented 
        //System.assertEquals(correctURL, testDialog.bigiant_dialog__Content_url__c);
    }

    //Test createStateDetails method
    @isTest static void testCreateStateDetails(){
        Test.startTest();
        PostRefreshCtrl prc = new PostRefreshCtrl();
        prc.createStateDetails();
        Test.stopTest();

        List<State_Detail__c> sdList = [SELECT Id FROM State_Detail__c];
        System.assertNotEquals(0,sdList.size());
    }
}