force-app/main/default/objects/Beneficial_Owner__c/Beneficial_Owner__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpBeneficialOwner</customHelpPage>
    <label>Beneficial Owner</label>
    <nameField>
        <displayFormat>BEN-{000000}</displayFormat>
        <label>Beneficial Owner ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficial Owners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Beneficial_Owner__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Beneficial Owners</relationshipLabel>
    <relationshipName>Beneficial_Owners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HierarchyControllerTest.cls
@isTest public class HierarchyControllerTest {
    @isTest static void testRun(){
        //Data Setup
        Registration__c testReg = eNettTestUtility.createRegistration('testComp');
        Beneficial_Owner__c testBO = eNettTestUtility.createBeneficialOwner(testReg.Id);
        
        //Test Perform
        test.startTest();
        HierarchyController.loadBenHier(testReg.Id);
        test.stopTest();
        
        //Verify Test
        System.assertEquals(1, [SELECT Id FROM Beneficial_Owner__c WHERE Registration__c =: testReg.Id].size());
    }
}