force-app/main/default/objects/Beneficial_Owner__c/Beneficial_Owner__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpBeneficialOwner</customHelpPage>
    <label>Beneficial Owner</label>
    <nameField>
        <displayFormat>BEN-{000000}</displayFormat>
        <label>Beneficial Owner ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Beneficial Owners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Beneficial_Owner__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Beneficial Owners</relationshipLabel>
    <relationshipName>Beneficial_Owners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Beneficial_Owner__c/fields/Verification__c.field-meta.xml
<CustomField>
    <fullName>Verification__c</fullName>
    <formula>verFlag__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Beneficial_Owner__c/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <description>The beneficial owner is a corporate entity (further information required)</description>
    <label>Business</label>
</RecordType>

force-app/main/default/objects/Director__c/Director__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpDirectors</customHelpPage>
    <label>Director</label>
    <nameField>
        <displayFormat>DIR-{000000}</displayFormat>
        <label>Director ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Directors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Director__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Directors</relationshipLabel>
    <relationshipName>Directors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpRegistration</customHelpPage>
    <label>Registration</label>
    <nameField>
        <displayFormat>REG-{000000}</displayFormat>
        <label>Registration ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration_Bank_Account__c/Registration_Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Registration Bank Account</label>
    <nameField>
        <displayFormat>RBA-{000000}</displayFormat>
        <label>Bank Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registration Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration_Bank_Account__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Registration_Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registration_Bank_Account__c/fields/Verification__c.field-meta.xml
<CustomField>
    <fullName>Verification__c</fullName>
    <formula>verFlag__c &gt; 0</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Verification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <customHelpPage>HelpVerification</customHelpPage>
    <label>Verification</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Verification ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verification</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Attachment_Status__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Status__c</fullName>
    <formula>if(Attachment_Count__c = 0,&quot;No Attachment&quot;,
if(Attachment_Count__c = 1,&quot;Document Attached&quot;,
&quot;Multiple Attachments&quot; ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Attachment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Beneficial_Owner__c.field-meta.xml
<CustomField>
    <fullName>Beneficial_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficial Owner</label>
    <referenceTo>Beneficial_Owner__c</referenceTo>
    <relationshipName>Information_Evidence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Director__c.field-meta.xml
<CustomField>
    <fullName>Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Director</label>
    <referenceTo>Director__c</referenceTo>
    <relationshipName>Information_Evidence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Evidence_Type__c.field-meta.xml
<CustomField>
    <fullName>Evidence_Type__c</fullName>
    <label>Evidence Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Registered Company Name</fullName>
            </value>
            <value>
                <fullName>Registered Business Number</fullName>
            </value>
            <value>
                <fullName>Trading Name</fullName>
            </value>
            <value>
                <fullName>Business Address</fullName>
            </value>
            <value>
                <fullName>Principal Signatory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipName>Company_Information_Evidence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Registration_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Registration_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration Bank Account</label>
    <referenceTo>Registration_Bank_Account__c</referenceTo>
    <relationshipName>Information_Evidence</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RegistrationInfo.cls
public class RegistrationInfo {
/*
    public list <registration__c> thisRegDetails {get;set;}
    public list <Beneficial_Owner__c> benOwn {get;set;}
    public list <Director__c> dir {get;set;}
    public list <Registration_Bank_Account__c> bank {get;set;}
    public list <Verification__c> ver {get;set;}
    public list <Verification__c> compName {get;set;}
    public list <Verification__c> busAdd {get;set;}
    public list <Verification__c> regNum {get;set;}
    public list <Verification__c> traNam {get;set;}
    public list <Verification__c> priSig {get;set;}
    
    public Id thisReg = ApexPages.currentPage().getParameters().get('Id');

    public RegistrationInfo(ApexPages.StandardController controller) {
    
    thisRegDetails=[SELECT id,name,zPepCountBeneficialOwner__c,zPepCountDirector__c FROM Registration__c WHERE id = :thisReg LIMIT 1];
    
    compName = new List <Verification__c> ();
    busAdd = new List <Verification__c> ();
    regNum = new List <Verification__c> ();
    traNam = new List <Verification__c> ();
    priSig = new List <Verification__c> ();
    
    benOwn=[SELECT id,name,Active__c FROM beneficial_owner__c WHERE Active__c = TRUE AND Registration__c = :thisReg 
        AND of_Verified_Records__c <= 1];
    dir=[SELECT id,name,Active__c FROM Director__c WHERE Active__c = TRUE AND Registration__c = :thisReg
        AND of_Verified_Records__c <= 1];      
    bank=[SELECT id, name,Active__c FROM Registration_Bank_Account__c WHERE Active__c = TRUE AND Registration__c = :thisReg
        AND of_Verified_Records__c <= 1];
    ver=[SELECT id,name,Evidence_Type__c,Attachment_Status__c FROM Verification__c WHERE Registration__c = :thisReg];
        FOR (Verification__c v : ver) {
            IF (v.Evidence_Type__c == 'Registered Company Name' & v.Attachment_Status__c != 'Document Attached') {compName.add(v);}
            IF (v.Evidence_Type__c == 'Business Address' & v.Attachment_Status__c != 'Document Attached') {busAdd.add(v);}
            IF (v.Evidence_Type__c == 'Registered Business Number' & v.Attachment_Status__c != 'Document Attached') {regNum.add(v);}
            IF (v.Evidence_Type__c == 'Trading Name' & v.Attachment_Status__c != 'Document Attached') {traNam.add(v);}
            IF (v.Evidence_Type__c == 'Principal Signatory' & v.Attachment_Status__c != 'Document Attached') {priSig.add(v);}
        }
    }
    */
}